### PR TITLE
Handle java multipart form data on requests in test Helpers

### LINKED ISSUE #11496: java testing: RequestBuilder.bodyMultipart does not work
### Play Version

2.8.18

### API

Java

### Operating System

Linux tr-XPS-9320 5.14.0-1051-oem #58-Ubuntu SMP Fri Aug 26 05:50:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)

### Library Dependencies

N.A.

### Expected Behavior

1. Call a route in a unittest via` play.test.Helpers.route(Application, RequestBuilder) `using a `Requestbuilder` with a body added with `play.mvc.Http.RequestBuilder.bodyMultipart(Map<String, String[]>, List<FilePart>)`.
2. The called Controller method should be able to read the body via 
`MultipartFormData<TemporaryFile> body=request.body().asMultipartFormData();`

### Actual Behavior

When calling the route, an error is thrown:

```
[error] Test controllers.HomeControllerTest.testIndex failed: java.lang.NullPointerException: Element must not be null, rule 2.13, took 2.347 sec
[error]     at akka.stream.impl.ReactiveStreamsCompliance$.elementMustNotBeNullException(ReactiveStreamsCompliance.scala:49)
[error]     at akka.stream.impl.ReactiveStreamsCompliance$.requireNonNullElement(ReactiveStreamsCompliance.scala:75)
[error]     at akka.stream.impl.fusing.GraphStages$SingleSource.<init>(GraphStages.scala:272)
[error]     at akka.stream.scaladsl.Source$.single(Source.scala:406)
[error]     at play.api.test.EssentialActionCaller.call(Helpers.scala:270)
[error]     at play.api.test.EssentialActionCaller.call$(Helpers.scala:259)
[error]     at play.api.test.Helpers$.call(Helpers.scala:672)
[error]     at play.api.test.RouteInvokers.route(Helpers.scala:292)
[error]     at play.api.test.RouteInvokers.route$(Helpers.scala:287)
[error]     at play.api.test.Helpers$.route(Helpers.scala:672)
[error]     at play.api.test.RouteInvokers.jRoute(Helpers.scala:279)
[error]     at play.api.test.RouteInvokers.jRoute$(Helpers.scala:278)
[error]     at play.api.test.Helpers$.jRoute(Helpers.scala:672)
[error]     at play.api.test.Helpers.jRoute(Helpers.scala)
[error]     at play.test.Helpers.route(Helpers.java:473)
[error]     at play.test.Helpers.route(Helpers.java:459)
[error]     at controllers.HomeControllerTest.testIndex(HomeControllerTest.java:32)
```

The reason is that `RequestBuilder.bodyMultipart` stores the `body` in `RequestBody` as `MultipartFormData` and `play.api.test.RouteInvokers.jRoute` (line 278) gets the content via `RequestBody.asBytes()`, which does not handle `MultipartFormData`, as is documented in its Javadoc. So it returns null, which triggers the listed error.

### Reproducible Test Case

Starting from `sbt new playframework/play-java-seed.g8`:

`routes`:

```
# An example controller showing a sample home page
GET     /                           controllers.HomeController.index()
POST     /test                           controllers.HomeController.test(request: Request)

# Map static resources from the /public folder to the /assets URL path
GET     /assets/*file               controllers.Assets.versioned(path="/public", file: Asset)
```

`HomeController.java`:

```
package controllers;

import play.mvc.*;
import play.mvc.Http.Request;
import play.libs.Files.TemporaryFile;
import play.mvc.Http.MultipartFormData;

/**
 * This controller contains an action to handle HTTP requests
 * to the application's home page.
 */
public class HomeController extends Controller {

    public Result index() {
        return ok(views.html.index.render());
    }

    public Result test(Request request) {
        MultipartFormData<TemporaryFile> body=request.body().asMultipartFormData();
        return ok(views.html.index.render());
    }

}
```

`HomeControllerTest`:

```
package controllers;

import java.util.*;
import org.junit.Test;
import play.Application;
import play.inject.guice.GuiceApplicationBuilder;
import play.mvc.Http;
import play.mvc.Result;
import play.test.WithApplication;

import static org.junit.Assert.assertEquals;
import static play.mvc.Http.Status.OK;
import static play.test.Helpers.POST;
import static play.test.Helpers.route;

public class HomeControllerTest extends WithApplication {

    @Override
    protected Application provideApplication() {
        return new GuiceApplicationBuilder().build();
    }

    @Test
    public void testIndex() {
        final Map<String, String[]> postParams = new HashMap<>();
        postParams.put("value", new String[]{"value"});
        Http.RequestBuilder request = new Http.RequestBuilder()
                .method(POST)
                .bodyMultipart(postParams, Collections.emptyList())
                .uri("/test");

        Result result = route(app, request);
        assertEquals(OK, result.status());
    }

}
```

### PR DESCRIPTION
**Pull request by adrianlyjak**
## Fixes

Fixes #11496 

## Purpose

Handles the case of multipart form data in the java `Helpers` api so that java based routes and tests that accept multipart form data files can be properly tested.

This is my first contribution here, so interested in feedback on implementation:

- I extracted a `FilePart.asScala()` method to keep the codebase DRY. However this method is now in the public API. Is this acceptable? It seemed somewhat appropriate as there are a bunch of similar methods in the same file for similar classes to convert to scala.
- The different types of generic "files" are still not terribly well handled for multipart form data. Only `MultipartFormData[TemporaryFile]` is handled. The types are cooerced somewhat awkwardly, but seems like there's likely diminishing returns with how many cases should be handled here, and I'm somewhat unclear on whether other types of form data files are even supported? Currently if you send, e.g. a `FilePart[String]` through, there will be another blow up in parsing internals from type casting. I could just ignore cases where the `FilePart` is not matching, and perhaps throw a more descriptive exception at least?
- I added a fairly monstrous test to the Play-Integration-Tests, because I had some general concerns about whether things were actually being serialized correctly. This test creates a temp file, so it may also be somewhat slow. I was basing this behavior off of some of the form tests that do the same. Is this test too much?

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

### CODE REVIEW

**Comment by martinariehm** [comment]
I hoped it could simply be possible to extend `RequestBody.asBytes()` to also handle bodies of type `MultipartFormData`. However, if this is not easily doable, that the changes look like a good solution with my limited knowledge.

**Comment by adrianlyjak** [comment]
@martinariehm it seems like returning bytes from MultiPartFormData with `RequestBody.asBytes()` was an intended optimization judging by the comments--since multipart data is generally reserved for files, and those are stored on disk. I was concerned about exposing that asBytes API to non-test use, but working with small test data bytes in testing seems reasonable

**Comment by mkurz** [comment]
First of all thanks for taking the time and providing this pull request!

At first it seemed the changes you made were ok, I almost wanted to merge, however then I quickly set up a Play Java app with the "Reproducible Test Case" posted in #11496, running against a local Play build with this patch applied and ... it failed.
I was wondering why that happens because you added tests. Turns out the tests you added did not actually test the changes you made:
* one just tested if the NullPointerException gets avoided, but didn't go deep enough to also test the logic of your change,
* the second test did not at all test your change, it even passes without your patch applied. That is because you added it as routed DSL test, which does not go through the `jRoute` method you patched. The `jRoute` method only gets traversed when a router needs to be retrieved from the app. When using the DSL however you already provide a router, so `jRoute` never will be called.

Since because we need to call `jRoute`, which in the end gets the router from the app, the easiest and sanest way to provide the application a router (without enabling the `RoutesCompiler` plugin on the test project), is to test a full application, which we can by using scripted tests. So that's what I did, see [this commit](https://github.com/playframework/playframework/pull/11505/commits/097303355776bffa62c32a2c59f1479c42fc0a08).

Now with this scripted test I was able to reproduce the errors I just experienced
This was the exception I was getting
```
Test controllers.HomeControllerTest.testJavaTemporaryFile failed: java.lang.ClassCastException: class play.libs.Files$DelegateTemporaryFile cannot be cast to class play.api.libs.Files$TemporaryFile (play.libs.Files$DelegateTemporaryFile and play.api.libs.Files$TemporaryFile are in unnamed module of loader 'app'), took 0.095 sec
    at play.api.http.DefaultWriteables.$anonfun$writeableOf_MultipartFormData$1(Writeable.scala:128)
    at play.api.http.DefaultWriteables.$anonfun$writeableOf_MultipartFormData$7(Writeable.scala:169)
    at scala.collection.immutable.List.flatMap(List.scala:293)
    at scala.collection.immutable.List.flatMap(List.scala:79)
    at play.api.http.DefaultWriteables.$anonfun$writeableOf_MultipartFormData$6(Writeable.scala:168)
```
So the problem here was that you used `Writeable.writeableOf_MultipartFormData` whichs works with Scala's `play.api.mvc.MultipartFormData`. You did convert the object from Java's `play.mvc.Http.MultipartFormData` though, but that was not enough, because the `ref` of the object still contained Java's `DelegateTemporaryFile` (subclass of Java's `TemporaryFile`), but the writable expected the Scala one. That's why we see that exception.

Now, I was able to work around that by creating a writeable that handles Java's `TemporaryFile` object in th `ref` pointer ([see commit](https://github.com/playframework/playframework/pull/11505/commits/b212f31aa0fa0f68adf5e8280620a1a0f05a1504)), which made the exception go away. However I got a different problem now:
```
[info] [error] Test controllers.HomeControllerTest.testScalaTemporaryFile failed: java.lang.AssertionError: expected:<200> but was:<400>, took 1.074 sec
[info] [error]     at controllers.HomeControllerTest.testTemporaryFile(HomeControllerTest.java:66)
[info] [error]     at controllers.HomeControllerTest.testScalaTemporaryFile(HomeControllerTest.java:52)
[info] [error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] [error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] [error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] [error]     at java.lang.reflect.Method.invoke(Method.java:566)
[info] [error]     ...
```
So I got http 400 "bad request", but expected 200. After a bit debugging I found out that the payload of the 400 error displayed  `"Unexpected end of input"`, which is caused by this line:
https://github.com/playframework/playframework/blob/52fc73b89bc7df08a73e129142e0e41037486871/core/play/src/main/scala/play/core/parsers/Multipart.scala#L377
So something had to be wrong with parsing the multipart/form-data request.
And it was: The writables did not correctly escape the `name` field, fixed [in the commit](https://github.com/playframework/playframework/pull/11505/commits/b3aca4951fb88f5f211cd29ad77d6c99f96281de). And even worse: The `boundary` that is used for splitting the request body into multiple data/file parts was not consistent: The boundary supplied in the `Content-Type` header did not match any boundary in the request body. That's because the writable just generated its own boundary, not caring about the one of the content-type it got passed. So I fixed that as well ([see commit](https://github.com/playframework/playframework/pull/11505/commits/dd1f037a09e60e2b41497e437c23497d9c7e617d)) and now my tests did pass!

However I was not really satisfied with how this was implemented, because, like you already mentioned, this solution only works with `TemporaryFiles`, as soon as you use a `FilePart` with something else (like plain `String`) this whole thing would fail.
So I was experimenting and starting with commit `f517b9a` I came up with a different solution, which I think is ready to get merged.
The main problem is that the writables have no idea what the `ref` object actually contains, and because of the lack of that information it is not able to convert the `ref` into bytes (or work with it in general).
The only one that knows what's in the `ref` is the `FilePart` it contains. So the information about how to transform that `ref` into bytes has to come from that `FilePart`.
So the solution is that when creating a `FilePart` object the creator _can_ tell it how to transform the ref to bytes by supplying a `refToBytes` function. When the bytes are needed we can just call `transformRefToBytes()` later on. That way a framework user can let Play know how an exotic object can be transformed into bytes (which is already needed when using a Plain `String` since they can be encoded differently which Play doesn't has a clue about)
I added a couple of default transformers for classes Play knows about and which probably will fit 97% of use cases so most users don't need to do anything.
In the scripted test you can see how to supply the `refToBytes` method to transform a `String` `FilePart` into bytes.


> I extracted a `FilePart.asScala()` method to keep the codebase DRY. However this method is now in the public API. Is this acceptable?

Yes, thanks great!

> The different types of generic "files" are still not terribly well handled for multipart form data...

With my solution a framework user can use any "file" type. Like said, I implemented conversions for the most obvious ones.

> I added a fairly monstrous test to the Play-Integration-Tests, because I had some general concerns about whether things were actually being serialized correctly. This test creates a temp file, so it may also be somewhat slow. I was basing this behavior off of some of the form tests that do the same. Is this test too much?

The test was not monstrous. Scripted tests take much more resources and usually take much longer. Tests will never be too much, don't worry :wink:

File: core/play-integration-test/src/it/java/play/routing/AbstractRoutingDslTest.java [hunk 1]
```diff
@@ -282,6 +287,63 @@ public void shouldPreserveRequestBodyAsRawBuffer() {
...
+                            "document", "jabberwocky.txt", "text/plain", tempFile))));
+    assertThat(
+        result,
+        equalTo(
+            "author: Lewis Carrol\n"
+                + "filename: jabberwocky.txt\n"
+                + "contentType: text/plain\n"
+                + "contents: Twas brillig and the slithy Toves...\n"));
+  }
+
```
Comment (mkurz) [inline core/play-integration-test/src/it/java/play/routing/AbstractRoutingDslTest.java:346]: This is the test I was talking about which does not test your/my patche(s) at all. It will pass before applying this pull request already.
Let's keep it anyway so we now the mulitpart/form-data stuff works with the DSL :wink:

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/test/java/controllers/HomeControllerTest.java [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+        String content = result.body().consumeData(mat).thenApply(bs -> bs.utf8String()).toCompletableFuture().get(5, TimeUnit.SECONDS);
+        assertEquals(OK, result.status());
+        assertEquals("Files: 0, Data: 1 [value1]", content);
+    }
+
+    @Test
+    public void testStringFilePart() throws ExecutionException, InterruptedException, TimeoutException {
+        String content = "Twas brillig and the slithy Toves...";
+        testTemporaryFile(List.of(new Http.MultipartFormData.FilePart<>("document", "jabberwocky.txt", "text/plain", content,
+                data -> Optional.of(ByteString.fromString(data)))));
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/test/java/controllers/HomeControllerTest.java:52]: Look here, using the lambda `data -> ...` as optional parameter you can now let Play know how to transform any unknown file part object to bytes, like need for `String`.
The other tests in this file don't need that because `TemporaryFile`, etc. are handled by play out of the box :wink:

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/test/java/controllers/HomeControllerTest.java [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+    }
+
+    @Test
+    public void testStringFilePartToRefToBytesDefined() throws ExecutionException, InterruptedException, TimeoutException {
+        exceptionGrabber.expect(RuntimeException.class);
+        exceptionGrabber.expectMessage("To be able to convert this FilePart's ref to bytes you need to define refToBytes of FilePart[java.lang.String]");
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/test/java/controllers/HomeControllerTest.java:58]: If a user does not supply the `refToBytes` function, but wants to convert the object into bytes (e.g. when writing tests :wink:), a nice error will be displayed.

File: testkit/play-test/src/test/java/play/test/HelpersTest.java [hunk 4]
```diff
@@ -144,6 +146,17 @@ public void shouldSuccessfullyExecutePostRequestWithEmptyBody() {
...
 
+  @Test
+  public void shouldSuccessfullyExecutePostRequestWithMultipartFormData() {
+    Application app = Helpers.fakeApplication();
+    Map<String, String[]> postParams = new java.util.HashMap();
+    postParams.put("key", new String[] {"value"});
+    Http.RequestBuilder request =
+        new Http.RequestBuilder().method(POST).bodyMultipart(postParams, Collections.emptyList());
+    Result result = Helpers.route(app, request);
+    assertThat(result.status(), equalTo(404));
```
Comment (mkurz) [inline testkit/play-test/src/test/java/play/test/HelpersTest.java:157]: This test you added is only testing the there is no null pointer exeption anymore, nothing else.

**Comment by mkurz** [comment]
> I hoped it could simply be possible to extend `RequestBody.asBytes()` to also handle bodies of type `MultipartFormData`. However, if this is not easily doable, that the changes look like a good solution with my limited knowledge.

Just a note on this comment: If calling `asBytes()` on `RequestBody`, what would you expect the bytes to contain? Since the body can have many different file and data parts, it would not really make sense to retrieve all data fields and files in one single, concated blob. Having a method on each `FilePart` to turn it into bytes seems to be the only reasonable way (like the `transformRefToBytes` I implemented.

**Review by mkurz — APPROVED** [review]
@martinariehm @adrianlyjak Let me know if you have any feedback or concerns regarding my solution. I think if you look at `HomeControllerTest.java` you will see how my implemention works.

If you are good with this pr, I will merge it soon.
Maybe we can also backport parts of the pull request which do not break binary compatibility (basically my first solution until commit `dd1f037`) to the 2.8.x branch (which would only support the `TemporaryFile` classes though).

File: testkit/play-test/src/test/java/play/test/HelpersTest.java (hunk 4 above)
Comment (mkurz) [reply testkit/play-test/src/test/java/play/test/HelpersTest.java:157]: :+1: Are you ok with the pull request? If so we can go forward and merge it.

**Comment by adrianlyjak** [comment]
@mkurz this looks awesome! Thanks for the thorough review and for fixing it up, this all looks awesome to me! 

I put a few very minor comments on the multipart `Writable` conversion code and tests. I'd be happy to contribute further changes if you think they're worthwhile


The scripted tests are really what I was looking for to verify this change, good to know about them. I saw them running in the github CI, but couldn't quite figure out what they were or how they worked. Still having some trouble. Looks like they depend on a `publishLocal` and then using the `project Sbt-Plugin` and then running `scripted` with maybe an argument? When attempting to do so, I'm getting errors from `publishLocal` like this
```
[error] Unable to locate class corresponding to inner class entry for TemporaryFile in owner play.api.libs.Files
[error] Unable to locate class corresponding to inner class entry for TemporaryFileCreator in owner play.api.libs.Files
```

and then errors from `scripted`

```
[info] [error] java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "scala.sys.SystemProperties.apply(Object)" is null
```

Is there some documentation or files you can point me to that might help me figure out how to run the scripted tests locally?

**Comment by mkurz** [comment]
> I put a few very minor comments on the multipart `Writable` conversion code and tests. I'd be happy to contribute further changes if you think they're worthwhile

Which comment? I can not see any.

When I run into
```
[error] Unable to locate class corresponding to inner class entry for TemporaryFile...
```
I run `clean` within sbt, also I think usually I quit sbt and start it again (after still running `clean`) . To be honest I don't really know why this error occurs, I haven't had time to look into that. Either it's a bug in sbt or how Play and sbt play together.
Whatever, it's not your fault and not related to your changes, it happens every now and then.

To run scripted tests:
What I usually do is, I set a fixed version for the whole build, so in `build.sbt` I put (after the imports):
```
(ThisBuild / version) := "2.9.0-SNAPSHOT"
```
this makes sure the artifacts that get created in `~/.ivy2/local/com.typesafe.play/` all have the version `2.9.0-SNAPSHOT` and also when running the scripted tests they always use `2.9.0-SNAPSHOT`. 
If you do not set a version explicitly, then sbt-dynver sets one, based on the last tag, commit-hash and, if you have uncommittet changes, a timestamp. That sometimes can make problems, if sbt-dynver changes the version generated between a publishLocal and when you run scripted tests (the scripted test then try to pick up a version e.g. with another timestamp that you did not actually publish).

Anyway, to run the scripted tests, you should:

```sh
$ sbt
sbt:Play-Framework> publishLocal
...
sbt:Play-Framework> project Sbt-Plugin
[info] set current project to Sbt-Plugin (in build file:...)

# Now set the versions to use
sbt:Sbt-Plugin> set scriptedSbt := "1.7.2"; set scriptedLaunchOpts += "-Dscala.version=2.13.10"; set scriptedLaunchOpts += "-Dscala.crossversions=2.13.10";
# You can now check if ithe versions got set correctly:
sbt:Sbt-Plugin> show scriptedSbt; show scriptedLaunchOpts;
# To now run a specific scripted test (e.g. the one in folder `java-test-helpers`):
sbt:Sbt-Plugin> scripted play-sbt-plugin/java-test-helpers
# To run all scripted tests just run:
sbt:Sbt-Plugin> scripted.
```

There are docs, but I see they are not up-to-date:
https://www.playframework.com/documentation/2.8.x/BuildingFromSource

**Comment by mkurz** [comment]
@adrianlyjak I opened #11549 to update the docs.

**Comment by adrianlyjak** [comment]
> Which comment? I can not see any.
@mkurz oops, 🤦 submitted pending comments now

File: core/play/src/main/scala/play/api/http/Writeable.scala [hunk 5]
```diff
@@ -116,36 +114,35 @@ trait DefaultWriteables extends LowPriorityWriteables {
...
+    } yield boundary
+    val boundary = maybeBoundary.getOrElse(Multipart.randomBoundary())
 
     def formatDataParts(data: Map[String, Seq[String]]) = {
       val dataParts = data
         .flatMap {
           case (name, values) =>
             values.map { value =>
-              s"--$boundary\r\n${HeaderNames.CONTENT_DISPOSITION}: form-data; name=$name\r\n\r\n$value\r\n"
+              s"""--$boundary\r\n${HeaderNames.CONTENT_DISPOSITION}: form-data; name="$name"\r\n\r\n$value\r\n"""
```
[the remark this answers is not in the document]
Comment (mkurz) [reply core/play/src/main/scala/play/api/http/Writeable.scala:145]: I have seen quoted and unquoted in the wild, Play can also handle (parse) both when it receives a request. But yeah when Play can build the body it should quote :wink:

File: core/play/src/main/scala/play/api/http/Writeable.scala [hunk 6]
```diff
@@ -116,36 +114,35 @@ trait DefaultWriteables extends LowPriorityWriteables {
...
+      aWriteable: Writeable[FilePart[A]]
+  ): Writeable[MultipartFormData[A]] = writeableOf_MultipartFormData(codec, aWriteable.contentType)
 
   /**
    * `Writeable` for `MultipartFormData`.
    */
   def writeableOf_MultipartFormData[A](
       codec: Codec,
-      aWriteable: Writeable[FilePart[A]]
+      contentType: Option[String]
```
[the remark this answers is not in the document]
Comment (mkurz) [reply core/play/src/main/scala/play/api/http/Writeable.scala:137]: Yeah, I was not really satisfied having this `contentType` parameter here.
I pushed a commit in which I deprecate this method and override it with one that explicitly expects the boundary only - plus the codec is now implicit, like the other methods have that already.

File: core/play/src/test/scala/play/api/http/WriteableSpec.scala [hunk 7]
```diff
@@ -37,17 +36,14 @@ class WriteableSpec extends Specification {
...
-        val codec             = Codec.utf_8
+        val multipartFormData =
+          createMultipartFormData[String]("file part value", data => Some(ByteString.fromString(data)))
+        val codec = Codec.utf_8
 
-        val writeable = Writeable.writeableOf_MultipartFormData(
-          codec,
-          Writeable[FilePart[String]]((f: FilePart[String]) => codec.encode(f.ref), contentType)
-        )
+        val writeable               = Writeable.writeableOf_MultipartFormData[String](codec, None)
```
[the remark this answers is not in the document]
Comment (mkurz) [reply core/play/src/test/scala/play/api/http/WriteableSpec.scala]: You mean alway let the writable generate a random boundary? That does not really work, because the boundary needs to be set in the content-type header of the request as well. Look at `jRoute` method of the `Helpers.scala` file in this pull request. The mediatype already contains the boundary of the content-type header of the request, which as to be the same boundary used in the writable.
I mean of course, instead of passing down the boundary, we could parse the returned writeable.contentType variable of the writable, but I think that also is not really nice.
Of course, we could also always expect a boundary to be passed, and remove the generation inside the writable, but IMHO it's just a nit and avoids generating a writable in this spec I comment on here.

File: testkit/play-test/src/main/scala/play/api/test/Helpers.scala [hunk 8]
```diff
@@ -190,12 +190,26 @@ trait Writeables {
...
     Writeable.writeableOf_MultipartFormData(codec, contentType).map(_.mfd)
+
+  /**
+   * If you pass a boundary, it will be used to separate the data/file parts of the multipart/form-data body.
+   * If you don't pass a boundary a random one will be generated.
+   */
+  def writeableOf_AnyContentAsMultipartFormWithBoundary(
+      boundary: Option[String]
+  )(implicit codec: Codec): Writeable[AnyContentAsMultipartFormData] =
+    Writeable.writeableOf_MultipartFormData(boundary).map(_.mfd)
```
Comment (mkurz) [inline testkit/play-test/src/main/scala/play/api/test/Helpers.scala:212]: @adrianlyjak Here I introduced a (non-implicit) method `writeableOf_AnyContentAsMultipartFormWithBoundary` as workaround since I don't want to just change the `contentType` param name to `boundary` since people might already pass a content-type and changing the name also changing whats expected. If I would just change the name, we might end up with boundaries like `--text/plain`... Not so good.
Also, if I got that right, that methed does not really help to be implicit since you would have to pass the boundary param explicit anyway.
Would do you think?

File: testkit/play-test/src/main/scala/play/api/test/Helpers.scala [hunk 9]
```diff
@@ -280,7 +294,9 @@ trait RouteInvokers extends EssentialActionCaller {
     Option(body.asMultipartFormData[Any]()) match {
       case Some(mpfd: JMultipartFormData[Any]) =>
         implicit val write: Writeable[MultipartFormData[Any]] =
-          Writeable.writeableOf_MultipartFormData(implicitly[Codec], r.mediaType.map(_.toString))
+          Writeable.writeableOf_MultipartFormData(
+            r.mediaType.flatMap(_.parameters.find(_._1.equalsIgnoreCase("boundary")).flatMap(_._2))
+          )
```
Comment (mkurz) [inline testkit/play-test/src/main/scala/play/api/test/Helpers.scala:299]: Of course, instead of passing the content-type now, we have to pass the boundary now :wink:

**Comment by mkurz** [comment]
@adrianlyjak Please check the last commit I pushed and my comments. If everything is good I think we can merge :+1:

File: testkit/play-test/src/main/scala/play/api/test/Helpers.scala (hunk 8 above)
Comment (adrianlyjak) [reply testkit/play-test/src/main/scala/play/api/test/Helpers.scala:212]: that makes sense, I don't see any other straightforward way around it

File: core/play/src/test/scala/play/api/http/WriteableSpec.scala (hunk 7 above)
[the remark this answers is not in the document]
Comment (adrianlyjak) [reply core/play/src/test/scala/play/api/http/WriteableSpec.scala]: aha, that makes sense, especially in that scenario. The Writeable there is used only for serializing the body and not for modifying the headers, so the outer calling code needs to have that control over the boundary to be correct

**Comment by adrianlyjak** [comment]
> @adrianlyjak Please check the last commit I pushed and my comments. If everything is good I think we can merge 👍

@mkurz LGTM, this all looks awesome! Thanks for your help and all the work you do for play framework.
