### PR TITLE
Fixes issue-7892 with consolidated test

### LINKED ISSUE #7892: Common tests for Akka HTTP and standard Headers implementations
We currently have the `play.core.server.akkahttp.AkkaHeadersWrapper` in the akka-http-server implementation and `play.api.mvc.Headers`. We should add tests for both and if possible share some of the specification. This could be done by creating a new integration test or having the akka-http-server tests depend on the core play tests.

### PR DESCRIPTION
**Pull request by lousanna**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #7892

## Purpose

Makes the tests under HttpSpec common to both AkkaRequestHeader and NettyRequestHeader specifications.

### CODE REVIEW

File: framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala [hunk 1]
```diff
@@ -65,5 +65,16 @@ trait RequestHeadersSpec extends PlaySpecification with ServerIntegrationSpecifi
       )
       response.body.left.toOption must beSome("https://bar.com")
     }
+
+    "pass http header common tests" in withServer((Action, _) => Action { rh =>
+      val akkaHeaders = rh.headers
+      (new HttpHeaderSpec).commonTests(akkaHeaders)
```
Comment (gmethvin) [inline framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala]: For clarity it would be probably be better to make this a `HttpHeadersCommonSpec` and have both specs extend that, like we've done with `CORSCommonSpec`.
