### PR TITLE
Fix race condition creating play temp folder

### LINKED ISSUE #7584: Race condition when creating temporary folder
The `DefaultTemporaryFileCreator.playTempFolder` method reads and writes the `_playTempFolder` field without any synchronisation. This leads to a race condition which could mean (a) we create temporary files in the wrong place or (b) we fail to clean up ("reap") temporary files from the wrong place.

There needs to be some synchronisation on this method, possibly using an atomic value.

### PR DESCRIPTION
**Pull request by gmethvin**
Fixes #7584. Uses an `AtomicReference` and retries if the value was changed while trying to update it.

### CODE REVIEW

File: framework/src/play/src/main/scala/play/api/libs/Files.scala [hunk 1]
```diff
@@ -148,30 +149,37 @@ object Files {
...
+        case Some(folder) if JFiles.exists(folder) =>
+          folder
+        case _ =>
+          JFiles.createTempDirectory(TempDirectoryPrefix)
+      }
+      if (_playTempFolder.compareAndSet(lastValue, Some(newFolder))) {
+        temporaryFileReaper.updateTempFolder(newFolder)
+        newFolder
+      } else {
+        playTempFolder
```
Comment (richdougherty) [inline framework/src/play/src/main/scala/play/api/libs/Files.scala]: Perhaps we could delete the `newFolder` at this point since it has been created but it is not going to be used.

Comment (gmethvin) [inline framework/src/play/src/main/scala/play/api/libs/Files.scala]: Good idea. Added a `deleteIfExists` before making the recursive call.

File: framework/src/play/src/main/scala/play/api/libs/Files.scala [hunk 2]
```diff
@@ -18,11 +19,11 @@ import org.slf4j.LoggerFactory
 import play.api.Configuration
 import play.api.inject.ApplicationLifecycle
 
+import scala.annotation.tailrec
 import scala.concurrent.Future
-import scala.concurrent.duration.{ Duration, FiniteDuration }
+import scala.concurrent.duration.{ Duration, FiniteDuration, _ }
```
Comment (benmccann) [inline framework/src/play/src/main/scala/play/api/libs/Files.scala]: why import Duration and FiniteDuration if you have a wildcard import?
