### PR TITLE
Don't reload/(re-)compile or even start an app when shutting down in DEV mode

### LINKED ISSUE #9043: Log4j MatchError in console when terminating with Ctrl + C an application launched with sbt run
### Play Version (2.5.x / etc)

I encounter this issue with Play 2.7.0 and not with Play 2.6.20.

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Fedora 29

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

### Library Dependencies

Sbt and Log4j2

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Launch the play application with `sbt run`
2. Wait for the message `(Server started, use Enter to stop and go back to the console...)`
3. Stop the application with Ctrl + C

### Actual Behavior

1. Launch the play application with `sbt run`
2. Wait for the message `(Server started, use Enter to stop and go back to the console...)`
3. Stop the application with Ctrl + C
4. I get the following log in the console

```
[info] p.c.s.AkkaHttpServer - Stopping server...
2019-02-19 14:00:57,766 pool-8-thread-4 ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[error] scala.MatchError: org.apache.logging.log4j.simple.SimpleLoggerContext@72b026cb (of class org.apache.logging.log4j.simple.SimpleLoggerContext)
[error] 	at sbt.util.LogExchange.logger(LogExchange.scala:28)
[error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:137)
[error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:104)
[error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:52)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:178)
[error] 	at sbt.std.TaskStreams.log(Streams.scala:85)
[error] 	at sbt.std.TaskStreams.log$(Streams.scala:85)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:136)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:136)
[error] 	at sbt.Classpaths$.$anonfun$depMap$1(Defaults.scala:2711)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (projectDescriptors) scala.MatchError: org.apache.logging.log4j.simple.SimpleLoggerContext@72b026cb (of class org.apache.logging.log4j.simple.SimpleLoggerContext)
[warn] a.a.CoordinatedShutdown - Task [shutdown-application-dev-mode] failed in phase [service-stop]: Unexpected exception[MatchError: org.apache.logging.log4j.simple.SimpleLoggerContext@72b026cb (of class org.apache.logging.log4j.simple.SimpleLoggerContext)]
```
### Reproducible Test Case

Example of project : https://github.com/KelkooGroup/theGardener/tree/feature/update-play

It looks like a conflict of libraries of log4j2 as the class `sbt.util.LogExchange.logger(LogExchange.scala:28)` try to match a **`org.apache.logging.log4j.core.LoggerContext`** from the lib **`log4j-core`** but the actual variable has the type `org.apache.logging.log4j.simple.SimpleLoggerContext` that extends **`org.apache.logging.log4j.spi.LoggerContext`** from **`log4j-api`**.

Thanks

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #9043
Actually I experience myself quite often that Play (re-)compiles when I shutdown dev mode (e.g via enter or CTRL+D)

I tracked down the core problem:
https://github.com/playframework/playframework/blob/ce4dadbd8e46bf15b2f61b6e54d447b3e988d8b1/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala#L251-L257

The line 255 is calling `appProvider.get`, and this `get` call will reload the app which [will cause a compilation (if e.g. the app has not even started yet or a file changed)](https://github.com/playframework/playframework/blob/2.8.7/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala#L142). **But we don't want to reload the app and (re-)compile, we want to shut it down!**

Even worse, what happens next is that at some point later even the server tries to `get` an app to shutdown the logger:
https://github.com/playframework/playframework/blob/ce4dadbd8e46bf15b2f61b6e54d447b3e988d8b1/transport/server/play-server/src/main/scala/play/core/server/Server.scala#L48-L52
So the server now gets the app, which, if it was just newly created by the `shutdown-application-dev-mode` hook above, for some reason has not yet fully initialized its logging system and fails to shut it down correctly (actually I am not 100% sure how when the logging system will be initialized, it seems its lazy loaded by guice when the first request hits). And this is then causing the error message shown the [initial comment](https://github.com/playframework/playframework/issues/9043#issue-411916640) of the issue referenced.

### CODE REVIEW

File: core/play/src/main/scala/play/api/controllers/Assets.scala [hunk 1]
```diff
@@ -70,13 +70,15 @@ class AssetsMetadataProvider @Inject() (
...
 ) extends Provider[DefaultAssetsMetadata] {
+  private val logger = Logger(this.getClass)
   lazy val get = {
     import StaticAssetsMetadata.instance
     val assetsMetadata = new DefaultAssetsMetadata(env, config, fileMimeTypes)
     StaticAssetsMetadata.synchronized {
       instance = Some(assetsMetadata)
     }
     lifecycle.addStopHook(() => {
+      logger.debug("Cleaning AssetsMetadata instance")
```
Comment (mkurz) [inline core/play/src/main/scala/play/api/controllers/Assets.scala:81]: Just added some debug messages so I was sure that the ApplicationLifecycle stop hooks were called.

File: transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala [hunk 2]
```diff
@@ -298,6 +298,7 @@ class NettyServer(
     // Do this last because the hooks were created before the server,
     // so the server might need them to run until the last moment.
     cs.addTask(CoordinatedShutdown.PhaseBeforeActorSystemTerminate, "user-provided-server-stop-hook") { () =>
+      logger.info("Running provided shutdown stop hooks")
```
Comment (mkurz) [inline transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala:301]: Just syncing with akka-http backend: https://github.com/playframework/playframework/blob/2.8.7/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L491

File: transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala [hunk 3]
```diff
@@ -199,10 +206,6 @@ final class DevServerStart(
               // First, stop the old application if it exists
               lastState.foreach(Play.stop)
 
-              // Basically no matter if the last state was a Success, we need to
-              // call all remaining hooks
-              lastLifecycle.foreach(cycle => Await.result(cycle.stop(), 10.minutes))
-
```
Comment (mkurz) [inline transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala:205]: I am 100% sure this line can be removed. The ApplicatoinLifecycle stop hooks are now called via the coordinated shutdown hooks ([the call is set up here](https://github.com/playframework/playframework/blob/2.8.7/core/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L304-L308)) (no matter if re-loading or shutting down an app in dev mode or shutting down an app in prod mode).
Actually this line here is and was a no-op, because at the time it was called the coordinated shutdown system already ran `applicationLifecycle.stop()` - which after running a stop hook [cleared it from the queue](https://github.com/playframework/playframework/blob/2.8.7/core/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala#L124).
So this line _always_ ended up executing zero stop hooks (that's why I added the debug message [above](https://github.com/playframework/playframework/pull/10661/files#diff-336f376aa6eaef66625c7d1d200135bcd6d0012b0ed41f4ed54310a65b2d544cR118)):
```
Executing ApplicationLifecycle.stop() with 0 stop hook(s) registered
```

File: transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala [hunk 4]
```diff
@@ -302,8 +305,9 @@ final class DevServerStart(
         // the Application and the Server use separate ActorSystems (e.g. DevMode).
         serverCs.addTask(CoordinatedShutdown.PhaseServiceStop, "shutdown-application-dev-mode") { () =>
           implicit val ctx = actorSystem.dispatcher
-          val stoppedApp   = appProvider.get.map(Play.stop)
-          Future.fromTry(stoppedApp).map(_ => Done)
+          val stoppedApp   = appProvider.lastState.map(Play.stop)
+          appProvider.isShutdown = true
+          Future(Done)
```
Comment (mkurz) [inline transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala:310]: So the key fix is here:
`lastState` is what we need to call, it means "give me the current running app if there is one". Then we shut down this current running app. Done.
Calling `get` however means "get me an app, and if there is no app, create a new one (which means compilation), or if there is one that needs re-compilation because of file changes, then yes, do it, and re-compile. But if compilation fails or already did fail, I tell the shutdown hook that there is a problem".

Also we need to track that the app was shut down already via `isShutdown` so a caller of `get` afterwards will get the already shut down app instead of again reloading/re-compiling/creating an app, like when https://github.com/playframework/playframework/blob/2.8.6/transport/server/play-server/src/main/scala/play/core/server/Server.scala#L48-L52 get called.

File: transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala [hunk 5]
```diff
@@ -178,12 +179,18 @@ final class DevServerStart(
...
+              // This avoids that reload will be called which might triggers a compilation
+              lastState
+            } else {
+              synchronized {
+                buildLink.reload match {
+                  case cl: ClassLoader => reload(cl) // New application classes
+                  case null            => lastState  // No change in the application classes
+                  case NonFatal(t)     => Failure(t) // An error we can display
+                  case t: Throwable    => throw t    // An error that we can't handle
+                }
```
Comment (mkurz) [inline transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala:193]: See [explanation below](https://github.com/playframework/playframework/pull/10661/files#r565194528) why we need check `if (isShutdown) ...`

**Review by jtjeferreira — APPROVED** [review]
Fanstastic work :tada: . Will you backport this to 2.7.x?

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x 2.7.x

**Review by ignasi35 — COMMENTED** [review]
This looks really good. Thanks for all the detailed explanation it made the review a lot simpler. 

My only question is that I couldn't find anywhere where `isShutDown` was set to `false` once the `appProvider` created a new instance. Or am I reading the code wrong and each new reload creates a new `appProvider` instance so there's no need to reset the `isShutdown` field?

**Comment by mkurz** [comment]
> My only question is that I couldn't find anywhere where `isShutDown` was set to `false` once the `appProvider` created a new instance. Or am I reading the code wrong and each new reload creates a new `appProvider` instance so there's no need to reset the `isShutdown` field?

We are talking about the dev mode server. What happens is that you `sbt run` your app, then you see 
```
--- (Running the application, auto-reloading is enabled) ---
```
and immediately afterwards the `appProvider` instance gets created, see the code:
https://github.com/playframework/playframework/blob/2.8.7/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala#L113-L117

So now when you stop the dev server with CTRL+D, and `run` again, you again see this line and again **a new** `appProvider` instance gets created. So actually, no, there is no need to reset the `isShutdown` field with _this_ workflow.
However, look at my last commit now. I reset it now when the app was _successfully_ created, just to make sure in case the `reload` method gets called from somewhere else (which is not the case right now) it is correctly reseted.

**Comment by ignasi35** [comment]
> We are talking about the dev mode server. What happens is that you `sbt run` your app, then you see...

Sure! But I thought the problem (the double compilation) already manifested when _just_ saving a file. that would trigger the need for a new compilation using the same `appProvider` instance, right? Did I misunderstood the scope of the issue?

File: transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala [hunk 6]
```diff
@@ -165,6 +165,7 @@ final class DevServerStart(
         val appProvider = new ApplicationProvider {
           var lastState: Try[Application]                        = Failure(new PlayException("Not initialized", "?"))
           var lastLifecycle: Option[DefaultApplicationLifecycle] = None
+          var isShutdown                                         = false
```
Comment (marcospereira) [inline transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala:168]: Nitpicking: at some other places, as in `Reloader`, we use an `AtomicBoolean` for such flags. It can be good to do the same here.

Comment (mkurz) [reply transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala]: Done!

File: transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala (hunk 3 above)
Comment (mkurz) [reply transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala:205]: > Can you validate that with a scenario where the app failed to startup entirely, but some components were started?

If you want to know if the stop hooks of the started components will still be run even if the app only started "partially" before failing to start up completely (and such a started component registered a stop hook in its constructor): yes they will, there is absolutely no change. I just tested this on my machine and can confirm this is working. 
I was sure that this will still work after reading the source code: the `lastState.foreach(Play.stop)` 2 lines above [will eventually run the coordinanted shutdown hooks of the current actorSystem](https://github.com/playframework/playframework/blob/2.8.7/core/play/src/main/scala/play/api/Application.scala#L217).
And when [setting up the coordinated shutdown hook](https://github.com/playframework/playframework/blob/2.8.7/core/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L305-L308) for the current actorSystem, it immediately adds a task to call `applicationLifecycle.stop()` when shutting down (which, again will happen in the `Play.stop` call).
So this is wired together and this line I removed is and was a no-op - the `applicationLifecycle.stop()` in Play 2.7.0 - 2.8.x is and was always triggered by `Play.stop` before already above, before even reaching this line.

I am sure this is a leftover ([introduced in Play 2.6.0](https://github.com/playframework/playframework/pull/6437/files#diff-53df0fd634da895ce66022f24b6387cb4e79d672e125fda6188afd8199dbecddR144)) which didn't get removed when we switched to the coordinated shutdown hooks in Play 2.7.

**Comment by mkurz** [comment]
@ignasi35 

> > We are talking about the dev mode server. What happens is that you `sbt run` your app, then you see...
> 
> Sure! But I thought the problem (the double compilation) already manifested when _just_ saving a file. that would trigger the need for a new compilation using the same `appProvider` instance, right? Did I misunderstood the scope of the issue?

To be honest, I don't really understand what you mean. This issue/pull request it not about double compilation, it's about an undesired and unnecessary compilation when the SERVER stops in dev mode (by hitting CTRL+D or enter). Like when doing `sbt run` but then doing nothing (not sending a request and therefore also not initializing the APP) but immediately pressing CTRL+D to quit. Until now a compilation will happen which clearly is not what a user wants. Another case would be when doing `sbt run`, sending a request which initializes the app, then editing a file but hitting CTRL+D (instead of sending a request). In this case also a compilation will happen (because a file was modified). But that does not make sense, because the user just intended to quit, it's nuts to re-compile the whole app now if the user wants to quit it anyway. It just costs time (this happens to me every now and then, I have to wait for the compilation to quit my app, insane... costs so much time). As soon a user hits CTRL+D he/she wants to quit, not compile it anymore (OK to be fair there may be one edge use case I can think of that a user actually wants to compile before quitting and that would be when the user is developing stop hooks and he/she wants to test them... but in such a case the solution is that the user has to make a request with the browser to re-compile and afterwards can quit to trigger the hooks and test the changes he/she made)

I hope you get what I mean, I am tired so I write long texts...

And about the `appProvider` instance: Not sure how I should explain that, but yes, for each `sbt run` in the sbt command line a new `appProvider` gets created. Now when a reload happens, because e.g. of a file change, the server will NOT be shutdown, but the current APP will be stopped (see `reload()`) and a new app will be created. But important: the `shutdown-application-dev-mode` stop hook of the SERVER actor system will not yet be called. This will only be called when shutting down the whole server via CTRL+D, but that also means a new `appProvider` will be created for a new `sbt run` anyway.  So for reloads the same instances will be used, but for shutdowns and then `sbt run`s new instances will be created. And `isShutdown` only tracks if the SERVER gets shut down.

A bit complicated I know...

**Comment by mkurz** [comment]
@marcospereira @ignasi35 Please have a look again, thanks.

**Comment by ignasi35** [comment]
> To be honest, I don't really understand what you mean. This issue/pull request it not about double compilation, it's about an undesired and unnecessary compilation when the SERVER stops in dev mode (by hitting CTRL+D or enter).

Thanks for explaining. I had completely misunderstood the issue.

**Comment by ignasi35** [comment]
I was reviewing this PR with a Lagom mindset. In Lagom, recompilation is immediate as soon as a file changes and that triggers a server restart. It is not the case in Play. In play, the application restarts as soon as there's a file change but compilation is deferred until the first request arrives. I was missing that case.

**Review by ignasi35 — APPROVED** [review]

**Comment by mkurz** [comment]
> In play, the application restarts as soon as there's a file change but compilation is deferred until the first request arrives. I was missing that case.

That is not correct:
When you use `run` nothing happens until a request arrives, only then the reloader checks if a file changed and if so, recompiles and _reloads_ (not "restarts") the app.
When you use `~run` and a file changes, the file will be (re-)compiled immediately and then nothing happens until a request arrives, and only then the app finally gets _reloaded_.

Also be aware: **`~run` is broken starting with sbt 1.3+** because sbt changed things regarding file watching, see https://github.com/playframework/playframework/issues/9983.
It would be interesting if lagom is affected as well.
