### PR TITLE
[master]: Stop Netty server reloading configuration on each request

### LINKED ISSUE #7812: [2.6.3] NumberFormatExceptions on every incoming query
Upgrading to sbt-play 2.6.3

I'm seeing exceptions with every request when using the netty backend (not confirmed with akka-httop), I isolated the problem to these two config parameters: https://www.playframework.com/documentation/2.6.x/ScalaBodyParsers#Max-content-length

the config parser is trying to load the defaults (128KB and 10MB) as `Long`, then `Double`, then finally as the custom format. This causes two guaranteed exceptions, every query.

The real fix is to fix the parser, the hack is to change the defaults to

```
play.http.parser.maxMemoryBuffer = 131072
play.http.parser.maxDiskBuffer = 10526720
```

### PR DESCRIPTION
**Pull request by richdougherty**
Fixes #7812.

The caching of the `ReloadCache` uses reference equality so we need to be more careful when passing around the Try[Application] returned by `ApplicationProvider.get`. We need to make sure we keep the same reference.

Also did some refactoring of code while I was making these changes.

### CODE REVIEW

**Comment by richdougherty** [comment]
2.6.x version of this PR: #8334.

**Comment by richdougherty** [comment]
I couldn't work out a way to unit test configuration loading without adding intrusive instrumentation into the server code so I plan to verify this by hand before merging. 🤷‍♂️

File: framework/src/play-server/src/main/scala/play/core/server/Server.scala [hunk 1]
```diff
@@ -32,23 +33,6 @@ trait Server extends ReloadableServer {
...
-   *
-   * - If there's a "web command" installed that intercepts the request.
-   * - If we fail to get the `Application` from the `applicationProvider`,
-   *   i.e. if there's an error loading the application.
-   * - If an exception is thrown.
-   *
-   * NOTE: This will use the ApplicationProvider of the server to get the application instance.
-   *       Use {@code Server.getHandlerFor(request, tryApp)} to pass a specific application instance
-   */
-  @deprecated("Use Server.getHandlerFor(request, tryApp) instead", "2.7.0")
```
Comment (richdougherty) [inline framework/src/play-server/src/main/scala/play/core/server/Server.scala]: As of #8334 this method will be deprecated in 2.6.13. The  method is highly unlikely to be used outside Play so I think it's OK to remove it for 2.7.0.

File: framework/src/play-server/src/main/scala/play/core/server/Server.scala [hunk 2]
```diff
@@ -94,10 +78,10 @@ object Server {
    *   i.e. if there's an error loading the application.
    * - If an exception is thrown.
    */
-  def getHandlerFor(
+  private[server] def getHandlerFor(
     request: RequestHeader,
     tryApp: Try[Application]
-  ): Either[Future[Result], (RequestHeader, Handler, Application)] = {
+  ): (RequestHeader, Handler) = {
```
Comment (richdougherty) [inline framework/src/play-server/src/main/scala/play/core/server/Server.scala]: It's easier to return a `Handler` than an `Either[Future[Result], Handler]`, since the returned `Future[Result]` is always  just turned into a `Handler` anyway...

Also the returned  `Application` is not helpful if we're trying to preserve the reference equality of the `Try[Application]`.

File: framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala [hunk 3]
```diff
@@ -84,40 +82,31 @@ private[play] class PlayRequestHandler(val server: NettyServer, val serverHeader
 
     val tryRequest: Try[RequestHeader] = modelConversion(tryApp).convertRequest(channel, request)
 
-    def clientError(statusCode: Int, message: String) = {
+    def clientError(statusCode: Int, message: String): (RequestHeader, Handler) = {
```
Comment (richdougherty) [inline framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala]: Quite a lot of code in this PR now uses a `(RequestHeader, Handler)` pair instead of other  types. This is probably something we could represent as a special type at some point. Maybe there's a state monad in here for the `RequestHeader`...

File: framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala [hunk 4]
```diff
@@ -264,12 +247,10 @@ private[play] class PlayRequestHandler(val server: NettyServer, val serverHeader
    * Handle an essential action.
    */
   private def handleAction(action: EssentialAction, requestHeader: RequestHeader,
-    request: HttpRequest, app: Option[Application]): Future[HttpResponse] = {
-    implicit val mat: Materializer = app.fold(server.materializer)(_.materializer)
+    request: HttpRequest, tryApp: Try[Application]): Future[HttpResponse] = {
```
Comment (richdougherty) [inline framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala]: This line is the key fix. We're insuring we pass the original `Try[Application]` through.

File: framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala [hunk 5]
```diff
@@ -84,40 +82,31 @@ private[play] class PlayRequestHandler(val server: NettyServer, val serverHeader
 
     val tryRequest: Try[RequestHeader] = modelConversion(tryApp).convertRequest(channel, request)
 
-    def clientError(statusCode: Int, message: String) = {
+    def clientError(statusCode: Int, message: String): (RequestHeader, Handler) = {
       val unparsedTarget = modelConversion(tryApp).createUnparsedRequestTarget(request)
       val requestHeader = modelConversion(tryApp).createRequestHeader(channel, request, unparsedTarget)
-      val result = errorHandler(server.applicationProvider.current).onClientError(requestHeader, statusCode,
```
Comment (richdougherty) [inline framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala]: This line is the only behaviour change I made in the refactoring—using `tryApp` instead of `applicationProvider.current`—however I think the new code is the correct behaviour.

**Comment by pettyjamesm** [comment]
Flame graphs of running the akka http server show that it has the same or similar problem: configuration being loaded every request.

File: framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala [hunk 6]
```diff
@@ -225,25 +225,6 @@ class AkkaHttpServer(
     }
   }
 
-  private def getHandler(
```
Comment (marcospereira) [inline framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala]: 👍

File: framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala [hunk 7]
```diff
@@ -283,24 +264,24 @@ private[play] class PlayRequestHandler(val server: NettyServer, val serverHeader
...
     } yield convertedResult
   }
 
   /**
    * Get the error handler for the application.
    */
-  private def errorHandler(app: Option[Application]): HttpErrorHandler =
-    app.fold[HttpErrorHandler](DefaultHttpErrorHandler)(_.errorHandler)
+  private def errorHandler(tryApp: Try[Application]): HttpErrorHandler =
+    tryApp.fold[HttpErrorHandler](_ => DefaultHttpErrorHandler, _.errorHandler)
```
Comment (marcospereira) [inline framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala]: The master branch build will have the same problem with Scala 2.11 (no fold for `Try`).

Since we will drop Scala 2.11, we can add a comment here to use `fold` when dropping Scala 2.11.

File: framework/src/play-server/src/main/scala/play/core/server/Server.scala (hunk 1 above)
Comment (marcospereira) [reply framework/src/play-server/src/main/scala/play/core/server/Server.scala]: 👍 

Anyway, maybe is worth to add a note in `Migration27.md`.

**Comment by richdougherty** [comment]
> I couldn't work out a way to unit test configuration loading without adding intrusive instrumentation into the server code so I plan to verify this by hand before merging. 

Due to reports of issues with Akka HTTP as well as Netty I've decided to be more conservative and there is now instrumentation in the server so that we can write automated tests to check reloads. The instrumentation is enabled with a configuration setting and details are passed as a request attribute. This is one of those times it would be nice to have JMX hooks so we can view internal server stats. Using a request attribute is the next best thing though.

Reload counts now appear to be correct on both backends.

**Comment by richdougherty** [comment]
Got this probably transient failure on one test, restarting.

```
[error]   x Not reap a non-expired file
[error]    List(/tmp/8627293184609446381/notcollected.txt) is not empty (TemporaryFileReaperSpec.scala:79)
```

**Comment by richdougherty** [comment]
I've run the the HelloWorld microbenchmark before and after this change and the change does seem to improve performance.

File: documentation/manual/releases/release27/migration27/Migration27.md [hunk 8]
```diff
@@ -92,3 +92,7 @@ Like announced in the [[Play 2.6 Migration Guide|Migration26#Java-Form-Changes]]
 ### `Guava` version updated to 24.0-jre
 
 Play 2.6.x provided 23.0 version of Guava library. Now it is updated to last actual version, 24.1-jre. Lots of changes were made in library, you can see the full changelog [here](https://github.com/google/guava/releases).
+
+### `Server.getHandlerFor` has been removed
```
Comment (gmethvin) [inline documentation/manual/releases/release27/migration27/Migration27.md]: I would write `Server#getHandlerFor` which is the common notation for instance methods.

File: documentation/manual/releases/release27/migration27/Migration27.md [hunk 9]
```diff
@@ -92,3 +92,7 @@ Like announced in the [[Play 2.6 Migration Guide|Migration26#Java-Form-Changes]]
...
+
+This method on the `Server` trait was used internally by the Play server code when routing requests. It has been removed and replaced with a method of the same name on the `Server` object.
```
Comment (gmethvin) [inline documentation/manual/releases/release27/migration27/Migration27.md]: You should either mention that the new method is `private[server]` or not mention it at all since it's not public API.

Comment (gmethvin) [reply documentation/manual/releases/release27/migration27/Migration27.md]: Yeah, fine with me, as long as we note that it's not public API.

File: documentation/manual/releases/release27/migration27/Migration27.md (hunk 8 above)
Comment (richdougherty) [reply documentation/manual/releases/release27/migration27/Migration27.md]: OK!

File: documentation/manual/releases/release27/migration27/Migration27.md (hunk 9 above)
Comment (richdougherty) [reply documentation/manual/releases/release27/migration27/Migration27.md]: I'll make an "internal API changes" section in the migration documentation and we'll try to mention any notable changes here. No guarantees though because we do make quite a few internal changes and it'll be hard to track everything.

**Comment by richdougherty** [comment]
Migration guide updated, merging.
