### PR TITLE
QueryStringBindable.unbind(): Do-do-do URLEncode for all queryString keys!

### LINKED ISSUE #10369: QueryStringBindable.bindableString.unbind() produces URL-encoded keys, other binders - don't
### Play Version
play-`2.8.2`

### API
Scala

### Operating System
`Linux pc 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux`

### JDK
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

### Library Dependencies
None

### Expected Behavior
`implicitly[QueryStringBindable[String]].unbind()` should NOT URL-encode key-part.
```
$ sbt console
import play.api.mvc.QueryStringBindable

scala> QueryStringBindable.bindableChar.unbind( "items[1]", '1' )
val res1: String = items[1]=1

scala> QueryStringBindable.bindableInt.unbind( "items[1]", 1 )
val res2: String = items[1]=1

scala> QueryStringBindable.bindableString.unbind( "items[1]", "1" )
val res3: String = items%5B1%5D=1

scala> QueryStringBindable.bindableDouble.unbind( "items[1]", 1 )
val res4: String = items[1]=1.0
```

### Actual Behavior
As you can see, the `res3` contains unexpected URL-encoded characters for `[` and `]` in key part: `items%5B1%5D`.
Other binders works as expected: `items[1]`.

Problem is in [play/api/mvc/Binders.scala#L312](https://github.com/playframework/playframework/blob/ddf3a7ee4285212ec665826ec268ef32b5a76000/core/play/src/main/scala/play/api/mvc/Binders.scala#L312).

### PR DESCRIPTION
**Pull request by helllamer**
Fixes #10369 - Let's DO `URLEncode.encode()` for all queryString keys in QSB.unbind().
Unify unbind() behaviour over all query-string binders.

Currently, different binders handle qs-keys differently (look at `res3`):
```
$ sbt console
import play.api.mvc.QueryStringBindable

scala> QueryStringBindable.bindableChar.unbind( "items[1]", '1' )
val res1: String = items[1]=1

scala> QueryStringBindable.bindableInt.unbind( "items[1]", 1 )
val res2: String = items[1]=1

scala> QueryStringBindable.bindableString.unbind( "items[1]", "1" )
val res3: String = items%5B1%5D=1

scala> QueryStringBindable.bindableDouble.unbind( "items[1]", 1 )
val res4: String = items[1]=1.0
```
Special characters like `[`, `]` and others MUST be Form-URL-encoded according to [RFC](https://tools.ietf.org/html/rfc3986#section-2.2).
Added documentation about applying `URLEncode` for handy-implemented unbinders.
Added tests for several common types of `QueryStringBindable`s.

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #10369

### CODE REVIEW

File: core/play/src/test/scala/play/api/mvc/BindersSpec.scala [hunk 1]
```diff
@@ -64,11 +64,6 @@ class BindersSpec extends Specification {
       val boundValue = bindableString.unbind("key", null)
       boundValue must beEqualTo("key=")
     }
-    "unbind with keys needing encode" in {
-      import QueryStringBindable._
-      val boundValue = bindableString.unbind("ke=y", "bar")
-      boundValue must beEqualTo("ke%3Dy=bar")
-    }
```
Comment (mkurz) [inline core/play/src/test/scala/play/api/mvc/BindersSpec.scala:71]: This test was just added a year ago in #9470 (which fixes #9403, also related: #9389 and #9401)
Looks like encoding query string keys was/is a desired behaviour.  
Having a quick look at [#9389 (section "Why perhaps shouldn't this be shipped as is")](https://github.com/playframework/playframework/pull/9389#:~:text=Why%20perhaps%20shouldn't%20this%20be%20shipped%20as%20is) it seems that un/reserved characters need special treatment: https://tools.ietf.org/html/rfc3986#section-2.2

Comment (helllamer) [reply core/play/src/test/scala/play/api/mvc/BindersSpec.scala:71]: Very "interesting" situation:
One test.
It tests **only one** `String` binder.
String binder - is the only one binder that `URLEncode`s qs keys.
All other binders (Int, Char, Double, etc, user/custom) all will 100% fail such test, because they never `URLEncode` keys.

I think, some "logical" error has been occured in previous pull-request/reviews.
So, that your mention/correct solution?

Comment (mkurz) [reply core/play/src/test/scala/play/api/mvc/BindersSpec.scala:71]: > All other binders (Int, Char, Double, etc, user/custom) all will 100% fail such test, because they never URLEncode keys.

You are totally right. So yes, there is/are bug(s) which need(s) to be fixed and there should be tests for all binders...
So I think the best is of course to fix all the binders so they behave the same. Also we should look into how to handle certain characters, like in your case `[` and `]`. As mentioned the rfc gives some clues. I don't have time to fix this myself (btw: I am not getting payed working on Play), so if you want to deep dive into this issues and provide a patch to fix all the problems everyone would be very happy if you do so.
Maybe @ignasi35 has a better insight how to encode the query string keys? I just don't have time right now to spend more time.

Comment (helllamer) [reply core/play/src/test/scala/play/api/mvc/BindersSpec.scala:71]: @mkurz Ok.

Couple of words about RFC and keys-encoding of special chars:

If we want to encode qs keys, we may break compatibility with user-implemented `QueryStringBindable`s inside end-user projects.
QSBs inside user projects has been written for years according to [documentation](https://www.playframework.com/documentation/2.8.x/ScalaRequestBinders#QueryStringBindable), that does not says about URLEncode.

**Comment by helllamer** [comment]
PR has been rewritten from scratch.
Now, all qs-binders using URLEncode.encode() against all of it data.
Tests extended.
Documentation extended.

File: core/play/src/main/scala/play/api/mvc/Binders.scala [hunk 2]
```diff
@@ -309,8 +319,7 @@ object QueryStringBindable {
 
     // Use an option here in case users call index(null) in the routes -- see #818
     def unbind(key: String, value: String) =
-      URLEncoder.encode(Option(key).getOrElse(""), "utf-8") + "=" + URLEncoder
-        .encode(Option(value).getOrElse(""), "utf-8")
+      _urlEncode(key) + "=" + Option(value).fold("")(_urlEncode)
```
Comment (ihostage) [inline core/play/src/main/scala/play/api/mvc/Binders.scala:322]: Why `Option` dropped for `key`? 🤔 He is no longer needed?

Comment (helllamer) [reply core/play/src/main/scala/play/api/mvc/Binders.scala:322]: Possibly, it never needed.
`Option(key).getOrElse()` added year ago in #9403 [(diff)](https://github.com/playframework/playframework/commit/458c6ed45bccc0753e8c3dd16d8f20ef2bcfbd70#diff-a7501fbcc4163466697d50c277648c4bR350) during fixing `URLEncode` for **values**.

- In `Binders.scala` there are no `Option(key)` for any other binders (Char, Long, Int, UUID, etc).
- There are zero tests for such behavior, where parsed queryString contains null keys with String-only values.
- Generated `Router.scala` can't pass `null`s as parameter names.
- `null` as keys in scala `Map[String,_]` **must** always `throw NPE`. It indicates serious problem in somewhere outer logic.

Comment (helllamer) [reply core/play/src/main/scala/play/api/mvc/Binders.scala:322]: @ihostage Этот Option(key) появился, т.к. код поддержки URLEncode просто скопипастили и value-кода в той же строке. Для `value` действительно нужен `Option()`, о чём в комменте там выше написано.

Comment (ihostage) [reply core/play/src/main/scala/play/api/mvc/Binders.scala:322]: Ok 👌

**Comment by helllamer** [comment]
@mkurz @ihostage I don't understand, is reviews completed ok? Is it time to remove `status:block-merge` flag?

**Comment by ihostage** [comment]
@helllamer Sorry, I'm not a maintainer and can't edit PR 🤷‍♂️

**Comment by mkurz** [comment]
Sorry, I am too busy this days... Maybe @ignasi35 and/or @renatocaval can review?

**Comment by mkurz** [comment]
@helllamer I had an intense look again at this pull request and it looks good to me. Actually I think it's a necessary fix and want to include it in the next Play 2.8.8 release. However I would like to push some small fixes to your patch (documentation wording and one more test).
Could you please give me access to your branch by selecting "Allow edits by maintainers" at the right side of the pull request?
Thanks!

image

**Comment by helllamer** [comment]
@mkurz Glad to hear you.
I've added you with WRITE access to `suggestio:master` branch on github.
Because i cannot find such checkbox, possibly due to using of `master` branch name.

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Comment by mkurz** [comment]
@helllamer Thanks, I pushed two commits. Let's see what Travis says.

**Review by mkurz — APPROVED** [review]
