### PR TITLE
import CollectionConverters or JavaConverters based on scala version

### LINKED ISSUE #9845: Play-twirl support imports deprecated API (scala 2.13)
The Java minimal imports:

https://github.com/playframework/playframework/blob/576c0def93c7abe8df7802fb3549b2e02475005b/dev-mode/build-link/src/main/java/play/TemplateImports.java#L32

imports `scala.collection.JavaConverters` which is deprecated in scala 2.13. This triggers the warning/error (dependinc on your `scalac` options):

```
[error] /Users/ignasi/git/projects/lightbend/playframework/play-samples/play-java-forms-example/app/views/listWidgets.scala.html:28:15: object JavaConverters in package col
lection is deprecated (since 2.13.0): Use `scala.jdk.CollectionConverters` instead
[error]         @form.globalErrors.asScala.map { error: play.data.validation.ValidationError =>
[error]               ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Nov 26, 2019 11:58:26 AM
```

Maybe fixable in this [`PlaySettings`](https://github.com/playframework/playframework/blob/b59ea7c532e9218b6d86825a1e5865274c96b5cf/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L35) initialization (branch over `scalaVersion`?)

### PR DESCRIPTION
**Pull request by fusuiyi123**
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #9845 

## Purpose

What does this PR do?
 if scala version >= `2.13.0` import `scala.jdk.CollectionConverters._`
else import `scala.collection.JavaConverters._`
## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

File: dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala [hunk 1]
```diff
@@ -29,18 +29,23 @@ import com.typesafe.sbt.web.SbtWeb.autoImport._
 import com.typesafe.sbt.web.SbtWeb.autoImport.WebKeys._
 
 object PlaySettings {
+
+  lazy val converterImport =
+    if (PlayVersion.scalaVersion >= "2.13.0") "scala.jdk.CollectionConverters._"
```
Comment (raboof) [inline dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala]: `PlayVersion.scalaVersion` is a `String`, so comparing that to `2.13.0` with `>=` probably doesn't do what we want.

Comment (fusuiyi123) [reply dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala]: do you mean scala string comparison? I checked the doc https://www.scala-lang.org/api/2.12.1/scala/collection/immutable/StringOps.html#>=(that:A):Boolean here, or is it the logic issue? Thanks!

Comment (raboof) [reply dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala:34]: Yes: `"2.12.2" >= "2.12.1"` is true, but also `"2.12.2" >= "2.12.10"`, so using string comparison to compare versions is dangerous (even if it might happen to work in some situations).

Comment (fusuiyi123) [reply dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala:34]: cool! gotcha.

**Comment by ignasi35** [comment]
Great work. Thanks @fusuiyi123

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x
