### PR TITLE
Fixes resource leakage in DefaultTemporaryFileReaper

### LINKED ISSUE #7667: DefaultTemporaryFileReaper is leaking open file descriptors
When I activate the temporary file reaper, the application starts to accumulate open file descriptors that are not closed anymore.

I'm using Play Framework 2.6.1 with Scala on Ubuntu 17.04 with Oracle Java:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

`uname -a` shows:
```
Linux jostick-XPS-15-9550 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Library dependencies do not matter.

### Expected Behavior

The number of open file descriptors stays stable over time.

### Actual Behavior

When I activate the temporary file reaper, e.g. with this configuration
```
play {
 temporaryFile {
    reaper {
      enabled = true
      initialDelay = "1 seconds"
      interval = "10 seconds"
      olderThan = "30 minutes"
    }
  }
}
```

the application starts to accumulate open file descriptors that are not closed anymore or at least not for a long time. The short interval is only for demonstration purposes. It also happens with longer intervals, but takes a bit longer to become obvious. It seems 2 new file descriptors are open in each interval.

`lsof -p 9608 | grep DIR` show a long list like:
```
java    9608 jostick  338r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  391r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  394r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  395r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  396r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  397r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  398r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
....
```

### Solution

I think the only thing required to fix the problem is to call close on the JFiles.list(f) stream in DefaultTemporaryFileReaper.reap()

If requested I can do a small PR. But it's probably not easy to write a proper unit test for that.

### PR DESCRIPTION
**Pull request by jostick**
Fixes #7667

As noted already, this is not easy to unit test without adding further abstractions. Ideas and feedback how to properly test it is welcome.

### CODE REVIEW

File: framework/src/play/src/main/scala/play/api/libs/Files.scala [hunk 1]
```diff
@@ -275,18 +275,26 @@ object Files {
...
               }
-            }).toScala[List]
+            })
 
-          reaped.foreach { p =>
-            delete(p)
+          try {
+            val reaped = directoryStream.toScala[List]
+
+            reaped.foreach { p =>
```
Comment (marcospereira) [inline framework/src/play/src/main/scala/play/api/libs/Files.scala]: Nitpick: this can be:

```scala
reaped.foreach(delete)
```

Comment (jostick) [inline framework/src/play/src/main/scala/play/api/libs/Files.scala]: Ah yes, I didn't write the line, but I like the improvement. Let's wait for more feedback. Maybe I can squash this in.

Comment (marcospereira) [inline framework/src/play/src/main/scala/play/api/libs/Files.scala]: No need to squash it manually. You can just add a new commit and they will all be squashed when integrating the pull request. :-)

**Comment by jostick** [comment]
@marcospereira Well... there is no obvious way. The stream is created by calling a static method in reap() and you can't access it from outside the method. I do see the following possibilities:
* use some magic to mock the static method JFiles.list
* expose the stream in some way
* extract the creation of the stream, e.g. inject a DirectoryStreamCreator that can be replaced in the test, or add a method createDirectoryStream(p: Path) to the DefaultTemporaryFileReaper that can be overriden in the test.

None of them make the code any better. If we want to add a test for this, I would suggest using last method and add a protected def createDirectorySteam(p: Path). It seems to be the easiest and most pragmatic way.

File: framework/src/play/src/main/scala/play/api/libs/Files.scala [hunk 2]
```diff
@@ -275,18 +275,26 @@ object Files {
         playTempFolder.map { f =>
           import scala.compat.java8.StreamConverters._
 
-          val reaped = JFiles.list(f)
+          val directoryStream = JFiles.list(f)
```
Comment (richdougherty) [inline framework/src/play/src/main/scala/play/api/libs/Files.scala]: I know that the `Stream` is lazy, but I'd suggest moving the `.filter` clause into the `try` block too, so there's a very clear divide between the resource we want to close (outside the `try` block) and the logic that runs on that resource (inside the `try` block). If you do that then the `try`/`finally` pattern you're using is clearer to see.

Also maybe put a `Stream[Path]` type annotation on `directoryStream`?

Comment (jostick) [inline framework/src/play/src/main/scala/play/api/libs/Files.scala]: I feel there should be a tryWithResource replacement for Scala like
```scala
  def tryWithResource[A <: AutoCloseable, B](resource: A)(f: A => B): B = 
      try {
        f(resource)
      } finally {
        resource.close()
      }
```

Which would allow to write
```scala 
 tryWithResource(JFiles.list(f)) { directoryStream =>
   val reaped = directoryStream.filter(new Predicate[Path]() {
    override def test(p: Path): Boolean = {
      val lastModifiedTime = JFiles.getLastModifiedTime(p).toInstant
      lastModifiedTime.isBefore(secondsAgo)
    }
  }).toScala[List]

  reaped.foreach(delete)

  reaped
}
```

This would be by far the cleanest solution. But I have no idea where to put this. 

@richdougherty Is there any utility function in Play I could use for that?

**Comment by marcospereira** [comment]
Backport to 2.6.x here: c9492090d3920a43a8ffc73122413d3a6cde5a1e

Thank you, @jostick.

**Comment by wsargent** [comment]
@jostick for future reference, it looks like it's possibe to test the list method by injecting the filesystem:

https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html

and then in the test, you could pass in ephemeralfs https://github.com/sbridges/ephemeralfs and then test the resource was closed.

**Comment by richdougherty** [comment]
@wsargent, that's great thanks! And I guess we could test thread leaks elsewhere in Play if we inject `ThreadFactory`s everywhere…

**Comment by jostick** [comment]
@wsargent I'm a bit worried about a dependency with one committer and no commits in the last 2 years. But the approach looks good and assertNoOpenResources is exactyl what's needed here. Thanks for the hint.

**Comment by wsargent** [comment]
@jostick there are other test filesystems out there, I picked ephemeralfs as an example.  I've not used one in anger, though.
