### PR TITLE
Make sure injector uses application ClassLoader

### LINKED ISSUE #7535: Using `JPA` helper class stand alone. without injecting `JPAApi`
### Expected Behavior

Using `JPA` helper class stand alone. without injecting `JPAApi`

### Actual Behavior
**It seems that creating entity manager using DI has some problems in play 2.6**
I have a very very simple database access :
```
@Transactional
public class HomeController extends Controller {

    public Result index() {
        JPA.em().find(Person.class, 1L);
        return ok(views.html.index.render());
    }

}
```

this simple code generates following stack trace and does not works:
```

! @74fhap05p - Internal server error, for (GET) [/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, javax.persistence.PersistenceException: Unable to build entity manager factory
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:40)
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.class(DefaultJPAApi.java:35)
  while locating play.db.jpa.DefaultJPAApi$JPAApiProvider
  while locating play.db.jpa.JPAApi
    for the 1st parameter of play.db.jpa.TransactionalAction.<init>(TransactionalAction.java:20)
  while locating play.db.jpa.TransactionalAction

1 error]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:230)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:229)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, javax.persistence.PersistenceException: Unable to build entity manager factory
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:40)
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.class(DefaultJPAApi.java:35)
  while locating play.db.jpa.DefaultJPAApi$JPAApiProvider
  while locating play.db.jpa.JPAApi
    for the 1st parameter of play.db.jpa.TransactionalAction.<init>(TransactionalAction.java:20)
  while locating play.db.jpa.TransactionalAction

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:405)
        at play.core.j.DefaultJavaHandlerComponents.getAction(JavaAction.scala:173)
        at play.core.j.JavaAction.$anonfun$apply$1(JavaAction.scala:96)
        at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
        at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
        at scala.collection.mutable.ArraySeq.foldLeft(ArraySeq.scala:46)
        at play.core.j.JavaAction.apply(JavaAction.scala:94)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
Caused by: javax.persistence.PersistenceException: Unable to build entity manager factory
        at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:66)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:39)
        at play.db.jpa.DefaultJPAApi.lambda$start$1(DefaultJPAApi.java:61)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at play.db.jpa.DefaultJPAApi.start(DefaultJPAApi.java:60)
        at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:47)
        at play.db.jpa.DefaultJPAApi$JPAApiProvider$$FastClassByGuice$$dcd4cdbd.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [models.Person]
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:229)
        at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:103)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:147)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:141)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:848)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:876)
        at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:39)
        at play.db.jpa.DefaultJPAApi.lambda$start$1(DefaultJPAApi.java:61)
Caused by: java.lang.ClassNotFoundException: Could not load requested class : models.Person
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader.findClass(ClassLoaderServiceImpl.java:217)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:226)
        at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:103)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:147)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:141)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:848)


```

while, surprisingly adding unused `JPAApi` inject resolves this problem:
```
@Transactional
public class HomeController extends Controller {
    @Inject
    public HomeController(JPAApi jpaApi) {
    }
    public Result index() {
        JPA.em().find(Person.class, 1L);
        return ok(views.html.index.render());
    }
}
```

I meet this issue when I am try to update my play version from 2.5 to 2.6

### PR DESCRIPTION
**Pull request by richdougherty**
Fixes #7535.

We need to set the thread context ClassLoader before we inject a class, because that class may itself use reflection when it initializes.

This fixes an issue where in dev mode initialization of the @Transactional annotation in dev mode fails to find the application's model classes. This is because in dev mode there are multiple ClassLoaders so we need to be careful about always using the correct ClassLoader when we load classes reflectively or call an API, such as JPA, which uses reflection internally.

### CODE REVIEW

File: framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala [hunk 1]
```diff
@@ -409,3 +413,23 @@ class GuiceInjector @Inject() (injector: com.google.inject.Injector) extends Pla
...
 }
+
+/**
+ * An object that holds a `ClassLoader` for Guice to use. We use this
+ * simple value object so it can be looked up by its type when we're
+ * assembling the Guice injector.
+ *
+ * @param classLoader The wrapped `ClassLoader`.
+ */
+class GuiceClassLoader(val classLoader: ClassLoader)
```
Comment (marcospereira) [inline framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: case class?

Comment (marcospereira) [inline framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: Also, should this be `private[play]`?

File: framework/src/play/src/test/scala/play/api/BuiltinComponentsSpec.scala [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+import java.io.File
+import java.net.URLClassLoader
+
+import org.specs2.mutable.Specification
+import play.api.inject.DefaultApplicationLifecycle
+import play.api.mvc.EssentialFilter
+import play.api.routing.Router
+import play.core.{ SourceMapper, WebCommands }
+
+class BuiltinComponentsSpec extends Specification {
```
Comment (marcospereira) [inline framework/src/play/src/test/scala/play/api/BuiltinComponentsSpec.scala]: `BuiltInComponentsSpec` (`In` with a capital `I`).

File: framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala [hunk 3]
```diff
@@ -409,3 +413,23 @@ class GuiceInjector @Inject() (injector: com.google.inject.Injector) extends Pla
...
+
+/**
+ * A provider for a Guice injector that wraps the injector to ensure
+ * it uses the correct `ClassLoader`.
+ *
+ * @param injector The injector to wrap.
+ * @param guiceClassLoader The `ClassLoader` the injector should use.
+ */
+class GuiceInjectorWithClassLoaderProvider @Inject() (injector: GuiceInjector, guiceClassLoader: GuiceClassLoader) extends Provider[Injector] {
```
Comment (gmethvin) [inline framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: Why not just have

```scala
class PlayInjectorProvider @Inject()(injector: GuiceInjector, environment: Environment) extends Provider[PlayInjector] {
  def get = new ContextClassloaderInjector(injector, environment.classLoader)
}
```

File: framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala (hunk 1 above)
Comment (richdougherty) [inline framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: I think it should have the same visibility as `GuiceInjector` since you'd often want to use them together.

Comment (richdougherty) [inline framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: (And `GuiceInjector` is public.)

File: framework/src/play/src/test/scala/play/api/BuiltinComponentsSpec.scala (hunk 2 above)
Comment (richdougherty) [inline framework/src/play/src/test/scala/play/api/BuiltinComponentsSpec.scala]: Nice catch :)

File: framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala (hunk 3 above)
Comment (richdougherty) [inline framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: It's because the `Environment` isn't bound in a minimal `GuiceInjectorBuilder`. Nor is the `Configuration`, even though both `Environment` and `Configuration` are known by the `GuiceInjectorBuilder`.

This is possibly because those objects might need to be bound in a custom way by a user of the `GuiceInjectorBuilder`. E.g. our `BuiltInModule` bind the `Configuration` in a clever way.

If we added bindings for `Environment` and `Configuration` into `GuiceInjectorBuilder` then would we be able to override them in `BuiltInModule`?

It's a bit tricky to work out the right design, since these two objects are a bit of a special case.

On a side note, I'm happy with having a `GuiceClassLoader` class, just in case it needs a binding that's different from the rest of the `Guice` application.

**Comment by richdougherty** [comment]
Fixed typo, added response to @gmethvin's comment. I'm happy with this one now. May need to rebase to pick up #7574's MIMA fix.

**Comment by richdougherty** [comment]
Broken by MIMA issue that is fixed in PR #7574. This PR will need to be rebased once that PR has been merged.

File: framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala (hunk 3 above)
Comment (gmethvin) [inline framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: Ok makes sense. Just wanted to see if we could avoid adding extra classes.

**Comment by fgi-github** [comment]
Any idea when this problem will be fixed ? Or if fixed, related problem #7751 is still present (unable to get play.current().injector() from parallelStream() (raising SecurityException at setClassLoader).

**Comment by richdougherty** [comment]
@fgi-github, the original issue was fixed, but it seems like it caused a regression as you reported in #7751. It looks like it might be a tricky one to resolve - either set the `ClassLoader` and get a `SecurityException` or don't set it and get a `ClassNotFoundException`. Which one you get depends on your usage. In any case, lets discuss back on #7751.
