### PR TITLE
GuiceBuilder does not utilize com.google.inject.Stage.PRODUCTION

### LINKED ISSUE #4608: [2.4] GuiceBuilder does not utilize com.google.inject.Stage.PRODUCTION
```
def injector(): PlayInjector = {
    try {
      val guiceInjector = Guice.createInjector(applicationModule())
      guiceInjector.getInstance(classOf[PlayInjector])
    } catch {
      case e: CreationException => e.getCause match {
        case p: PlayException => throw p
        case _ => throw e
      }
    }
  }
```

Above method from `GuiceBuilder` creates `guiceInjector` with default stage which is `Stage.DEVELOPMENT` for all environments. Wouldn't it be wiser to use `Stage.PRODUCTION` in `PROD` environment?

### PR DESCRIPTION
**Pull request by jCalamari**

### CODE REVIEW

File: framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala [hunk 1]
```diff
@@ -134,6 +134,14 @@ abstract class GuiceBuilder[Self] protected (
   }
 
   /**
+   * Maps Play environment to Guice stage.
+   */
+  lazy val stage = environment.mode match {
+    case Mode.Prod => Stage.PRODUCTION
+    case _ => Stage.DEVELOPMENT
+  }
```
Comment (richdougherty) [inline framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: What about making this a local variable inside the `injector` method? I don't think it needs to be exposed as API.

If we do want to make it part of the API, perhaps it could be a `protected def` instead of `lazy val`. We should minimise its visibility and I don't think we need to cache the result.

**Comment by marcospereira** [comment]
Build failed with:

```
[info] ProdServerStartSpec.start should
[error]   ! read settings, create custom ServerProvider, create a pid file, start the the server and register shutdown hooks
[error]    Exit with Oops, cannot start the server., -1 (ProdServerStartSpec.scala:60)
[error] play.core.server.ProdServerStartSpec$FakeServerProcess.exit(ProdServerStartSpec.scala:60)
[error] play.core.server.ProdServerStart$.start(ProdServerStart.scala:69)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$15$$anonfun$apply$16.apply(ProdServerStartSpec.scala:94)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$15$$anonfun$apply$16.apply(ProdServerStartSpec.scala:86)
[error] play.core.server.ProdServerStartSpec$.withTempDir(ProdServerStartSpec.scala:20)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$15.apply(ProdServerStartSpec.scala:86)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$15.apply(ProdServerStartSpec.scala:86)
[error] play.api.libs.CryptoConfigParser.get$lzycompute(Crypto.scala:236)
[error] play.api.libs.CryptoConfigParser.get(Crypto.scala:203)
[error] play.api.libs.CryptoConfigParser.get(Crypto.scala:197)
[error] com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
[error] com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
[error] com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
[error] com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
[error] com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[error] com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[error] com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
[error] com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
[error] com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
[error] com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[error] com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
[error] com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[error] com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
[error] com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[error] com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
[error] com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
[error] com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[error] com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
[error] com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
[error] com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
[error] com.google.inject.Guice.createInjector(Guice.java:96)
[error] com.google.inject.Guice.createInjector(Guice.java:84)
[error] play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
[error] play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
[error] play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
[error] play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$15$$anonfun$apply$16.apply(ProdServerStartSpec.scala:94)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$15$$anonfun$apply$16.apply(ProdServerStartSpec.scala:86)
[error] play.core.server.ProdServerStartSpec$.withTempDir(ProdServerStartSpec.scala:20)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$15.apply(ProdServerStartSpec.scala:86)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$15.apply(ProdServerStartSpec.scala:86)
[info] 
[error]   ! read configuration for ports
[error]    Exit with Oops, cannot start the server., -1 (ProdServerStartSpec.scala:60)
[error] play.core.server.ProdServerStartSpec$FakeServerProcess.exit(ProdServerStartSpec.scala:60)
[error] play.core.server.ProdServerStart$.start(ProdServerStart.scala:69)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$26$$anonfun$apply$27.apply(ProdServerStartSpec.scala:122)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$26$$anonfun$apply$27.apply(ProdServerStartSpec.scala:109)
[error] play.core.server.ProdServerStartSpec$.withTempDir(ProdServerStartSpec.scala:20)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$26.apply(ProdServerStartSpec.scala:109)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$26.apply(ProdServerStartSpec.scala:109)
[error] play.api.libs.CryptoConfigParser.get$lzycompute(Crypto.scala:236)
[error] play.api.libs.CryptoConfigParser.get(Crypto.scala:203)
[error] play.api.libs.CryptoConfigParser.get(Crypto.scala:197)
[error] com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
[error] com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
[error] com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
[error] com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
[error] com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[error] com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[error] com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
[error] com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
[error] com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
[error] com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[error] com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
[error] com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[error] com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
[error] com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[error] com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
[error] com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
[error] com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[error] com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
[error] com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
[error] com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
[error] com.google.inject.Guice.createInjector(Guice.java:96)
[error] com.google.inject.Guice.createInjector(Guice.java:84)
[error] play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
[error] play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
[error] play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
[error] play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$26$$anonfun$apply$27.apply(ProdServerStartSpec.scala:122)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$26$$anonfun$apply$27.apply(ProdServerStartSpec.scala:109)
[error] play.core.server.ProdServerStartSpec$.withTempDir(ProdServerStartSpec.scala:20)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$26.apply(ProdServerStartSpec.scala:109)
[error] play.core.server.ProdServerStartSpec$$anonfun$4$$anonfun$apply$26.apply(ProdServerStartSpec.scala:109)
[info] 
```

**Comment by benmccann** [comment]
I usually always used Stage.PRODUCTION which means you find errors when you create the injector, which is more helpful. Stage.DEVELOPMENT is more of a lazy loading thing where you don't find an error until you inject that particular thing.

File: framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala (hunk 1 above)
Comment (matiwinnetou) [inline framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: Stage from Guice also has a tool option, what if one would map TOOL to TEST, I know it is not ideal but somehow could be 1 to 1 mapping?

Comment (gmethvin) [inline framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: I don't think `TOOL` does what we want though: https://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/Stage.html#TOOL

**Comment by jCalamari** [comment]
@benmccann Having Stage.DEVELOPMENT still makes sense. Not sure how much faster is DEV than PROD.

>We want fast startup times at the expense of runtime performance and some up front error checking.

https://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/Stage.html#DEVELOPMENT

File: framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala (hunk 1 above)
Comment (jCalamari) [inline framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala]: >What about making this a local variable inside the injector method? I don't think it needs to be exposed as API.

Yeah makes sense.

**Comment by jCalamari** [comment]
@cchantep Any advice how to squash these commits, please?

**Comment by cchantep** [comment]
You can do `git rebase -i HEAD~8` from CLI on your branch, then follow instructions in the history editor to squash (`s` operation).

**Comment by jCalamari** [comment]
@cchantep  Thanks, squash noob here. Would you confirm I am doing it right, please? Deleted:
8978ef1, b02a15e, 95d4ef6.

Before: 
```
pick c58bf6c Make it easier to see hyperlinks in documentation code
pick fb62c20 update mysql driver version in documentation
pick 64ee720 fix incorrect scaladoc
pick bf27613 use executableScriptName instead of normalizedName
pick 5e56ea6 Updated key to generate a new secret
pick 40a0b21 should not use default Locale when call toLowerCase, toUpperCase
pick b02a15e local variable
pick dc0240e fix BodyParser scaladoc
pick 1bcebe9 Add support for unquoted Content-Disposition parameters
pick 7cc442e Update test dependencies
pick 0762412 Upgrade async-http-client to version 1.9.29
pick 95d4ef6 guice stage - local variable
pick df5d4c1 Update Heroku deployment documentation for 2.4
pick 3ef4a09 local variable
pick b628ecf Change JsLookupResult#getOrElse to call by name
pick d24cbe3 fix dev-mode memory leaks (#4649)
pick 405db38 Enable sql log statements
pick 7cd042e Added SubTypesScanner to Reflections factory in Classpath
pick 84f6f5a Make `invokeWithContext` static in Helpers.java
pick 8978ef1 GuiceBuilder does not utilize com.google.inject.Stage.PRODUCTION
```

After:

```
pick 3ef4a09 local variable
s c58bf6c Make it easier to see hyperlinks in documentation code
s fb62c20 update mysql driver version in documentation
s 64ee720 fix incorrect scaladoc
s bf27613 use executableScriptName instead of normalizedName
s 5e56ea6 Updated key to generate a new secret
s 40a0b21 should not use default Locale when call toLowerCase, toUpperCase
s dc0240e fix BodyParser scaladoc
s 1bcebe9 Add support for unquoted Content-Disposition parameters
s 7cc442e Update test dependencies
s 0762412 Upgrade async-http-client to version 1.9.29
s df5d4c1 Update Heroku deployment documentation for 2.4
s b628ecf Change JsLookupResult#getOrElse to call by name
s d24cbe3 fix dev-mode memory leaks (#4649)
s 405db38 Enable sql log statements
s 7cd042e Added SubTypesScanner to Reflections factory in Classpath
s 84f6f5a Make `invokeWithContext` static in Helpers.java
```

**Comment by jroper** [comment]
Hey @jCalamari, instructions for squashing are [here](https://playframework.com/documentation/2.4.x/WorkingWithGit).

**Comment by jCalamari** [comment]
@jroper Thanks, I've found it just after placing the comment. Is it fine to squash merges? All these are merges:

```
s c58bf6c Make it easier to see hyperlinks in documentation code
s fb62c20 update mysql driver version in documentation
s 64ee720 fix incorrect scaladoc
s bf27613 use executableScriptName instead of normalizedName
s 5e56ea6 Updated key to generate a new secret
s 40a0b21 should not use default Locale when call toLowerCase, toUpperCase
s dc0240e fix BodyParser scaladoc
s 1bcebe9 Add support for unquoted Content-Disposition parameters
s 7cc442e Update test dependencies
s 0762412 Upgrade async-http-client to version 1.9.29
s df5d4c1 Update Heroku deployment documentation for 2.4
s b628ecf Change JsLookupResult#getOrElse to call by name
s d24cbe3 fix dev-mode memory leaks (#4649)
s 405db38 Enable sql log statements
s 7cd042e Added SubTypesScanner to Reflections factory in Classpath
s 84f6f5a Make `invokeWithContext` static in Helpers.java
```

**Comment by cchantep** [comment]
You should not have `s` for the first of your commit, which will become the only one in this PR.

**Comment by benmccann** [comment]
@jCalamari i'm not sure i agree. why would you want to disable error checking in development? i don't want to deploy my service to production only to get error checking that didn't run in dev and find out that my service is failing. the time it saves you is unnoticeable and inconsequential

**Comment by jCalamari** [comment]
@marcospereira Not sure why, but some core config properties cannot be resolved with Stage.PRODUCTION, root cause:

>Configuration error: Configuration error[reference.conf @ file:/home/piotrek/workspace/playframework/framework/src/play-server/target/scala-2.10/classes/reference.conf: 63: Could not resolve substitution to a value: ${play.server.dir}]

>[error] p.a.l.CryptoConfigParser - The application secret has not been set, and we are in prod mode. Your application is not secure.
[error] p.a.l.CryptoConfigParser - The application secret has not been set, and we are in prod mode. Your application is not secure.
[error] p.a.l.CryptoConfigParser - To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
[error] p.a.l.CryptoConfigParser - To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret

I simply added `play.crypto.secret: ...` to `src/play-server/src/test/resources/application.conf`, however not sure why the property was resolved in Stage.DEVELOPMENT.

**Comment by benmccann** [comment]
This is exactly why I think we should always use `Stage.PRODUCTION` even in development. Guice used stupid names in calling it `Stage.PRODUCTION` and `Stage.DEVELOPMENT`. Pretend instead that they called it `ErrorChecking.ON` and `ErrorChecking.OFF`. It makes sense to always have error checking turned on.

**Comment by gmethvin** [comment]
I think it should be explicitly configurable in the injector builder and/or through configuration. It should be easy to make it so my injector always uses the `PRODUCTION` stage.

I know the `DEVELOPMENT` stage makes singleton creation lazy by default, which could possibly serve some performance benefit when the application is reloading frequently. So I still can see the reason to keep that as the default in dev mode (though maybe someone should measure the difference in a real app...).

**Comment by benmccann** [comment]
+1 to having it easily configurable and benchmarking what if any performance difference there is

**Comment by matiwinnetou** [comment]
For me performance difference is already noticeable. As those singletons are lazy in DEV mode, if there is some eager preloading of DB resources then basically some injected resources won't be loaded on startup. I would vote for Mode.DEV -> Stage.STAGE and Mode.PROD -> Stage.PRODUCTION

**Comment by jCalamari** [comment]
+1
Mode.DEV -> Stage.DEVELOPMENT
Mode.PROD -> Stage.PRODUCTION

+1
having it configurable

**Comment by richdougherty** [comment]
So Mode.PROD is always Stage.PRODUCTION, but Mode.DEV is configurable? Sounds good to me.

**Comment by marcospereira** [comment]
LGTM.

**Comment by jroper** [comment]
So now it's configurable, but to configure it in dev mode you need to define a custom application loader, you can't configure it from the configuration file.  Maybe that's ok - what do others think?

**Comment by marcospereira** [comment]
@jroper given the fact that most of users won't need to reconfigure it and, if they need, maybe we need to change the default configuration value, I think this PR is already ok.

**Comment by matiwinnetou** [comment]
@jroper: for me it is ok that it can be also reconfigured from application loader.

**Comment by puneetar** [comment]
Hey Guys, 
Is this available in play 2.4.3 ? How can I configure this ?
