### PR TITLE
Fix Java Formatters (#6419)

### LINKED ISSUE #6419: [2.5.4] java.lang.IllegalArgumentException thrown when using Formatters#parse(Field, String, Class)
### Play Version (2.5.x / etc)

2.5.4

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 8.1

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

### Library Dependencies

N/A

### Expected Behavior

Steps 1-4 can be completed by following the steps outlined here: https://www.playframework.com/documentation/2.5.x/JavaForms#Register-a-custom-DataBinder

1. Implement a custom formatter (`play.data.format.Formatter.SimpleFormatter` or `play.data.format.Formatter.AnnotationFormatter`, doesn't matter). For this example I went with  `public class IntegerFormatter extends play.data.format.Formatter.SimpleFormatter<Integer>`.
2. Create a provider that registers the new formatter.
3. Create a Guice module that binds `play.data.format.Formatters` to the new provider.
4. Disable the default `play.data.format.FormatterModule` and enable the new module in `application.conf`.
5. Create a DTO class with a field that will use the new formatter. For this example I created a class called `IntegerDto` with a single `java.lang.Integer` field named `integer`.
6. Create a controller and inject an instance of `play.data.format.Formatters`.
7. In a controller method attempt to parse a valid value with the new formatter using the `play.data.format.Formatters#parse(java.lang.reflect.Field, java.lang.String, java.lang.Class)` method. For this example it would look like this: `String value = "1"; Integer i = formatters.parse(IntegerDto.class.getDeclaredField("integer"), value, Integer.class);`
8. The integer value should be parsed successfully and should have the value of 1.

### Actual Behavior

The following exception is thrown in step 7: `play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalArgumentException: source to convert from must be an instance of java.lang.Integer; instead it was a java.lang.String]]`

The exception is thrown because `play.data.format.Formatters` passes the type descriptor of the target type instead of the source type as the 2nd parameter to `GenericConversionService#convert(java.lang.Object, org.springframework.core.convert.TypeDescriptor, org.springframework.core.convert.TypeDescriptor)`:

    @SuppressWarnings("unchecked")
    public <T> T parse(Field field, String text, Class<T> clazz) {
        return (T)conversion.convert(text, new TypeDescriptor(field), TypeDescriptor.valueOf(clazz));
    }

### Reproducible Test Case

A simple Play application that illustrates this issue can be found here:

https://github.com/sevasm/play-formatters

### PR DESCRIPTION
**Pull request by Dziman**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

## Fixes

Fixes #6419

### CODE REVIEW

**Comment by cchantep** [comment]
Hi, it would be nice to add at least one test (using the reproducer indicated in #6429), so this can be reviewed/validated. Best regards

**Comment by gmethvin** [comment]
@Dziman I agree with @cchantep. The test case in #6419 should be sufficient. Also, it would be nice if the commit message described what this is doing in a few words. Someone reading over the commit history (and the changelog) should basically understand what the commit is doing without referring to Github.

**Comment by Dziman** [comment]
@cchantep do you mean FarmattersTest should contains more test cases?
P.S. PR checklist was updated to reflect commit fc25c1d contains tests

**Comment by schmitch** [comment]
@cchantep acording to the timeline this now has tests are you satisfied with them?

**Comment by cchantep** [comment]
As indicated I would prefer the test not to require a full app

**Comment by Dziman** [comment]
@cchantep changed

File: framework/src/play-java/src/main/java/play/data/format/Formatters.java [hunk 1]
```diff
@@ -59,9 +55,9 @@ public Formatters(MessagesApi messagesApi) {
      * @param <T> the type to parse out of the text
      * @return the parsed value
      */
-    @SuppressWarnings("unchecked")
+    @SuppressWarnings({"unchecked", "unused"})
     public <T> T parse(Field field, String text, Class<T> clazz) {
```
Comment (mkurz) [inline framework/src/play-java/src/main/java/play/data/format/Formatters.java]: Why didn't we just remove the clazz parameter instead of suppressing the unused warning?
I think it's fine to do this in the master branch...

Comment (mkurz) [inline framework/src/play-java/src/main/java/play/data/format/Formatters.java]: There is no point of passing an argument and not using it anway.
