### PR TITLE
Fix issues when building on Windows

### LINKED ISSUE #8449: java.nio.charset.UnmappableCharacterException on windows 10
Playframework 2.6.x doesn't compile on Windows 10 out of the box.  I get "java.nio.charset.UnmappableCharacterException: Input length = 1" [errors when I try and compile](https://stackoverflow.com/a/50594577/1502448) right after checking out 2.6.x.  The compile errors seem to be due to smart quotes in some comments in RequestHeader.scala, Render.scala, Jasonp.scala.  Removing all of them manually seems to have worked to compile.  Then I had to delete the test directory to get around the same problem of special characters in some of the tests to be able to publishLocal.  If someone with access to windows could fix this it would be helpful.  I assume that putting a scalacOptions ++= Seq("-encoding", "UTF-8") in the right place is necessary but I couldn't get it to work.

### PR DESCRIPTION
**Pull request by marcospereira**
## Fixes

Fixes #8449.

## Purpose

Make it possible to build Play on Windows without changing any project configurations. This was tested on a Windows 10 VM.

### CODE REVIEW

File: documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java [hunk 1]
```diff
@@ -110,8 +107,7 @@ public MultipartFormDataWithFileBodyParser(Materializer materializer, play.api.h
         private File generateTempFile() {
             try {
                 final EnumSet<PosixFilePermission> attrs = EnumSet.of(OWNER_READ, OWNER_WRITE);
```
Comment (benmccann) [inline documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java]: this is unused now

Comment (marcospereira) [reply documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java]: Done. :-)

**Comment by marcospereira** [comment]
2.6.x: 65812edc8e6c770f03c3c3856929ff158a25396a
