### PR TITLE
Better use of AsyncCacheApi in CachedAction

### LINKED ISSUE #7615: Cannot use injector.instanceOf() with @Cached
### Are you looking for help?

No

### Play Version (2.5.x / etc)

2.6.1

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### Library Dependencies

No

### Expected Behavior

Please refer the following code.
```
@Inject
play.inject.Injector injector;

@play.cache.Cached(key = "somewhat")
public Result index() {
  AnyClass o = injector.instanceOf(AnyClass.class);
  return ok();
}
```

I hope the instance of `AnyClass` will be retrived as expected.

### Actual Behavior

In fact, the injector throw an exception in DEV mode in sbt interactive mode.

```
! @74j450acf - Internal server error, for (GET) [/] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.SecurityException: setContextClassLoader]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:204)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:164)
        at play.core.j.JavaHttpErrorHandlerAdapter.$anonfun$onServerError$1(JavaHttpErrorHandlerAdapter.scala:22)
Caused by: java.util.concurrent.CompletionException: java.lang.SecurityException: setContextClassLoader
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
Caused by: java.lang.SecurityException: setContextClassLoader
        at java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:244)
        at play.api.inject.ContextClassLoaderInjector.withContext(Injector.scala:125)
        at play.api.inject.ContextClassLoaderInjector.instanceOf(Injector.scala:118)
        at play.inject.DelegateInjector.instanceOf(DelegateInjector.java:22)
        at controllers.Home.index(Home.java:49)
```

In PROD mode, the code works as expected.

### Reproducible Test Case

Just use the attached code as before.

### PR DESCRIPTION
**Pull request by marcospereira**
## Fixes

Fixes #7615.

## Purpose

Instead of using get-and-set the cache, using getOrElseUpdate.

This way the execution won't happen in a ForkJoinPool thread pool, but instead it will fallback all the way down until Scala AsyncCacheApi implementation which uses the application ExecutionContext. Because of that, ContextClassLoaderInjector won't fail to change the ClassLoader for the executing thread.

### CODE REVIEW

File: framework/src/play-cache/src/main/java/play/cache/CachedAction.java [hunk 1]
```diff
@@ -27,14 +26,7 @@ public CachedAction(AsyncCacheApi cacheApi) {
...
         final Integer duration = configuration.duration();
-        return cacheApi.<Result>get(key).thenComposeAsync(cacheResult -> {
-            if (cacheResult != null) {
-                return CompletableFuture.completedFuture(cacheResult);
-            }
-            return delegate.call(ctx).thenComposeAsync(result ->
-                    cacheApi.set(key, result, duration).thenApply(ignore -> result)
-            );
-        });
+        return cacheApi.getOrElseUpdate(key, () -> delegate.call(ctx), duration);
```
Comment (richdougherty) [inline framework/src/play-cache/src/main/java/play/cache/CachedAction.java]: OK this looks like it would solve the threading problem. :) So now the cache is storing `CompletionState<Result>`s instead of `Result`s. I think that is fine.

Just a question though—is the behaviour the same as before if the`CompletionStage` returned by `delegate.call(ctx)` completes with an exception?

File: framework/src/play-integration-test/src/test/scala/play/it/http/JavaCachedActionSpec.scala [hunk 2]
```diff
@@ -0,0 +1,211 @@
...
+import play.api.test.{ PlaySpecification, TestServer, WsTestClient }
+import play.cache.{ Cached, DefaultAsyncCacheApi }
+import play.inject.ApplicationLifecycle
+import play.mvc.Result
+
+import scala.concurrent.{ ExecutionContext, Future }
+import scala.concurrent.duration._
+import scala.reflect.ClassTag
+
+class JavaCachedActionSpec extends PlaySpecification with WsTestClient {
```
Comment (richdougherty) [inline framework/src/play-integration-test/src/test/scala/play/it/http/JavaCachedActionSpec.scala]: Nice test!

File: framework/src/play-integration-test/src/test/scala/play/it/http/JavaCachedActionSpec.scala [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+
+    "when controller is annotated" in {
+
+      "cache result" in makeRequest(new CachedController()) { port =>
+        val responses = BasicHttpClient.makeRequests(port)(
+          BasicRequest("GET", "/", "HTTP/1.1", Map(), ""),
+          BasicRequest("GET", "/", "HTTP/1.1", Map(), "")
+        )
+
+        val first = responses.head
```
Comment (richdougherty) [inline framework/src/play-integration-test/src/test/scala/play/it/http/JavaCachedActionSpec.scala]: Did this test reproduce the issue before you made the fix?

File: framework/src/play-cache/src/main/java/play/cache/CachedAction.java (hunk 1 above)
Comment (marcospereira) [inline framework/src/play-cache/src/main/java/play/cache/CachedAction.java]: Here is the current implementation:

https://github.com/playframework/playframework/blob/2.6.1/framework/src/play-ehcache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala#L193-L198

So it should cache only the success value of a `Future` (which was created from the `CompletionStage`).

Comment (richdougherty) [inline framework/src/play-cache/src/main/java/play/cache/CachedAction.java]: OK I understand now. :) I thought it was the old cache API, but it's the new async one.

**Comment by gmethvin** [comment]
Backport 2.6.x: 	dcb608e
