### PR TITLE
Fix #8023 - Don't ignore exceptions thrown during JPA rollback

### LINKED ISSUE #8023: Don't ignore exceptions thrown during JPA rollback
I noticed this bit of code [in the JPA implementation](https://github.com/playframework/playframework/blob/cdc2210758d906055774cd9573921d9cdfaaa106/framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java#L150-L154) where we're catching a `Throwable` and ignoring it. See the `catch (Throwable e) {}` below:

```scala
} catch (Throwable t) {
  if (tx != null) {
    try { tx.rollback(); } catch (Throwable e) {}
  }
  throw t;
} ...
```

1. We should try and avoid catching `Throwable` - maybe catch `NonFatal` instead?
2. Since we've got two exceptions at this point but we can only throw one, we should update `catch (Throwable e) {}` to log the value of `e` before we `throw t`.

### PR DESCRIPTION
**Pull request by defrancea**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
  * N/A
* [x] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
  * N/A
* [ ] Have you added tests for any changed functionality?
  * I didn't not change any functionality, I'll be happy to improve the exception management tests if you think it's worth it.

# Helpful things

## Fixes

Fixes #8023

## Purpose

Check that the transaction is active before to roll it back and add logging if any exception is encountered during the rollback.

## Background Context

I started to look at #8023 and followed the advises. I looked at the JPA documentation in order to choose a better exception type to catch

## References

[JPA EntityTransaction documentation](https://docs.oracle.com/javaee/6/api/javax/persistence/EntityTransaction.html#rollback())

### CODE REVIEW

File: framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java [hunk 1]
```diff
@@ -21,6 +22,8 @@
  */
 public class DefaultJPAApi implements JPAApi {
 
+    private static final Logger.ALogger logger = Logger.of(DefaultJPAApi.class);
```
Comment (PromanSEW) [inline framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java]: `play.Logger` is deprecated. Use SLF4J instead.

File: framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java [hunk 2]
```diff
@@ -148,8 +151,12 @@ public EntityManager em() {
...
         } catch (Throwable t) {
-            if (tx != null) {
-                try { tx.rollback(); } catch (Throwable e) {}
+            if (tx != null && tx.isActive()) {
+                try {
+                    tx.rollback();
+                } catch (PersistenceException e) {
+                    logger.error("Could not rollback transaction", e);
+                }
             }
```
Comment (richdougherty) [inline framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java]: Perhaps put the `try`/`catch` around the `if (...) {...}` just in case there's an exception in `tx.isActive()`?

**Comment by richdougherty** [comment]
@defrancea, thanks a lot for taking a look at that issue!

File: framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java [hunk 3]
```diff
@@ -148,8 +151,12 @@ public EntityManager em() {
             return result;
 
         } catch (Throwable t) {
-            if (tx != null) {
-                try { tx.rollback(); } catch (Throwable e) {}
+            if (tx != null && tx.isActive()) {
+                try {
+                    tx.rollback();
+                } catch (PersistenceException e) {
```
Comment (richdougherty) [inline framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java]: I'd be happier if this was an `Exception` instead of a `PersistenceException` so that we can catch and report other kinds of non-fatal exceptions. E.g. if there's a `NullPointerException` or an `IllegalStateException` we'd want to report that.

File: framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java (hunk 1 above)
Comment (defrancea) [reply framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java]: I'm going to address this, I took example from https://github.com/playframework/playframework/blob/master/framework/src/play-java/src/main/java/play/routing/RoutingDsl but I missed the deprecation, thanks.

File: framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java (hunk 2 above)
Comment (defrancea) [reply framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java]: Good point, sounds good.

File: framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java (hunk 3 above)
Comment (defrancea) [reply framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java]: I was thinking about that but after looking at the EntityTransaction documentation I got more specific to cover the throws only. However, I get your point and yeah I agree, it doesn't cost anything to be more general here and it's absolutely relevant to report these exceptions if they ever happen. I'll address it.

**Comment by defrancea** [comment]
I addressed everything, build of test-scala-212 is failing with:
```
ERROR application - 
! @768ldlo5f - Internal server error, for (POST) [/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IOException: out of disk space]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
Caused by: java.io.IOException: out of disk space
	at com.google.common.jimfs.HeapDisk.allocate(HeapDisk.java:121)
[error]   ! work if there's no crlf at the start
[error]    akka.stream.AbruptStageTerminationException: GraphStage [akka.stream.impl.HeadOptionStage$$anon$3@3b8481e3] terminated abruptly, caused by for example materializer or actor system termination. (file:1)
```
It doesn't sound like it comes from this change so I looked for a way to run the build again it but I couldn't find any.

**Comment by marcospereira** [comment]
@defrancea the failing test is not related to the changes you made. `MultipartFormDataParserSpec` is being flaky:

https://gitter.im/playframework/contributors?at=5a2abd38a2be46682878c36d

I've triggered the build again to see if it pass, but it would be better if you rebase against the master branch where there is a fix for the test.

**Comment by marcospereira** [comment]
Thank you very much, @defrancea!

**Comment by marcospereira** [comment]
Backport to 2.6.x: 56e395d8d09d5c63ea3297394ec2160d83362236
