### PR TITLE
fixes websockets on netty

### LINKED ISSUE #6504: Netty WebSocket specs do not return close frames
### Play Version (2.5.x / etc)

master

### API (Scala / Java / Neither / Both)

Scala

### Actual Behavior

We've seen build failures where the WebSocketSpec fails because the close frame does not seem to be returned from the server.  This happens reliably for 

``` scala
  "respond to pings" in {
    withServer(app => WebSocket.accept[String, String] { req =>
      Flow.fromSinkAndSource(Sink.ignore, Source.maybe[String])
    }) { app =>
      import app.materializer
      val frames = runWebSocket { flow =>
        sendFrames(
          PingMessage(ByteString("hello")),
          CloseMessage(1000)
        ).via(flow).runWith(consumeFrames)
      }
      frames must contain(exactly(
        pongFrame(be_==("hello")),
        closeFrame()
      ))
    }
  }

  "not respond to pongs" in {
    withServer(app => WebSocket.accept[String, String] { req =>
      Flow.fromSinkAndSource(Sink.ignore, Source.maybe[String])
    }) { app =>
      import app.materializer
      val frames = runWebSocket { flow =>
        sendFrames(
          PongMessage(ByteString("hello")),
          CloseMessage(1000)
        ).via(flow).runWith(consumeFrames)
      }
      frames must contain(exactly(
        closeFrame()
      ))
    }
  }
```

yields

```
[error]     x respond to pings
[error]      List(SimpleMessage(PongMessage(ByteString(104, 101, 108, 108, 111)),true)) does not contain exactly 2 correct values (WebSocketSpec.scala:273)
[error]     x not respond to pongs
[error]      List() does not contain exactly 1 correct value (WebSocketSpec.scala:291)
```

This doesn't happen on Akka HTTP, only on Netty.  Because this is failing the build every time, we're moving the specs out to https://github.com/playframework/playframework/pull/6501 and marking as pendingUntilNettyHttpFixed to stabilize things a bit.

Looking at the build history on https://travis-ci.org/playframework/playframework/builds --

* Master was working until [job 3089](https://travis-ci.org/playframework/playframework/builds/153766184).  
* We don't see the particular ping error in [build 3112](https://travis-ci.org/playframework/playframework/builds/154544548).
* Earliest indication is [3117.2 failed](https://travis-ci.org/playframework/playframework/jobs/154594497#L2468), when we upgraded to Akka 2.4.9. 
* After that, we see it in [build 3123](https://travis-ci.org/playframework/playframework/jobs/154671232#L2349)

and we keep seeing it from there.  Next step might be moving to Akka 2.4.8 and repeating.

https://travis-ci.org/playframework/playframework/jobs/154594497#L2468

### PR DESCRIPTION
**Pull request by schmitch**
Fixes #6504

Edit: Fix is just 3 Lines https://github.com/playframework/playframework/pull/6534/files#diff-745ef9331ba1901efedd1607f6675eeaR183
Basically we can also omit complet/cancel for netty (not for akka) if necessary.

### CODE REVIEW

File: framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala [hunk 1]
```diff
@@ -180,9 +180,11 @@ object WebSocketFlowHandler {
 
                       // This is a client initiated close, so send back
                       if (isAvailable(remoteOut)) {
-                        // We can send, send immediately then terminate the connection
+                        // We can send the close frame
                         push(remoteOut, close)
-                        completeStage()
+                        // And complete both remote out and remote in
+                        complete(remoteOut)
```
Comment (schmitch) [inline framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala]: if that won't help we can basically just add a netty: Boolean and remove these two completly than netty will close the upstream by himself. Which is basically a little bit smoother since netty knows when he flushes the Message.

File: framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala [hunk 2]
```diff
@@ -166,13 +165,25 @@ object WebSocketClient {
...
-        def onPush(elem: WebSocketFrame, ctx: Context[WebSocketFrame]) = elem match {
-          case close: CloseWebSocketFrame =>
-            clientInitiatedClose.set(true)
-            ctx.push(close)
-          case other =>
-            ctx.push(other)
+      val captureClientClose = Flow[WebSocketFrame].via(new GraphStage[FlowShape[WebSocketFrame, WebSocketFrame]] {
+        val in = Inlet[WebSocketFrame]("WebSocketFrame.in")
+        val out = Outlet[WebSocketFrame]("WebSocketFrame.out")
+        override def shape: FlowShape[WebSocketFrame, WebSocketFrame] = FlowShape.of(in, out)
```
Comment (cchantep) [inline framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala]: I don't think defining it as a `def` is appropriate, as based on previously declared `val` (could lead to multiple eval).

> For me `override` should not be used there, as abstract in the `GraphStage`.

File: framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala [hunk 3]
```diff
@@ -166,13 +165,24 @@ object WebSocketClient {
...
+        override def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new GraphStageLogic(shape) with InHandler with OutHandler {
+          override def onPush(): Unit = {
```
Comment (cchantep) [inline framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala]: Same comment about `override` for `createLogic` and `onPush`

File: framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala [hunk 4]
```diff
@@ -166,13 +165,24 @@ object WebSocketClient {
...
+              case close: CloseWebSocketFrame =>
+                clientInitiatedClose.set(true)
+                push(out, close)
+              case other => push(out, other)
+            }
+          }
+
+          override def onPull(): Unit = pull(in)
+
+          setHandler(in, this)
```
Comment (cchantep) [inline framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala]: `setHandlers(in, out, this)`

**Comment by gmethvin** [comment]
@schmitch lgtm. Can you backport to 2.5.x?

**Comment by schmitch** [comment]
yes

**Comment by schmitch** [comment]
Backport https://github.com/playframework/playframework/commit/00e016ff728163f4ab4f0e78f105f86a5dba0746 (commited directly)

**Comment by philipwhiuk** [comment]
Not a helpful pull request title.
