### PR TITLE
Fixes issue 5275 with java helper method for parsing json

### LINKED ISSUE #5275: Provide helper method to parse json requests
Right now to get the value of a JSON request you need to do:

```
Json.fromJson(request().body().asJson(), Pet.class)
```

It seems like it'd be simpler to have a method that was something a bit more like:

```
request().body().asJson(Pet.class)
```

### PR DESCRIPTION
**Pull request by lousanna**
## Fixes

Fixes #5275

## Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you added tests for any changed functionality?

## Note

Message me if you were already working on this issue, and I'll gladly close this for you to take care of.

### CODE REVIEW

File: framework/src/play/src/main/java/play/mvc/Http.java [hunk 1]
```diff
@@ -1875,6 +1875,27 @@ public JsonNode asJson() {
...
+         */
+        public <A> A parseJson(Class<A> clazz) {
+            JsonNode asJson = asJson();
+            if (asJson == null) {
+                return null;
+
+            } else {
+                try {
+                    return Json.fromJson(asJson, clazz);
+                } catch(Exception e) {
```
Comment (gmethvin) [inline framework/src/play/src/main/java/play/mvc/Http.java]: What specific kinds of exceptions are you trying to catch here? I think it would be fine to let the exception bubble up.

File: framework/src/play/src/main/java/play/mvc/Http.java [hunk 2]
```diff
@@ -1875,6 +1875,27 @@ public JsonNode asJson() {
         }
 
         /**
+         * Parses the request to the expected class.
```
Comment (gmethvin) [inline framework/src/play/src/main/java/play/mvc/Http.java]: parses the request *body*

**Comment by lousanna** [comment]
Thank you @gmethvin for the feedback!

File: documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java [hunk 3]
```diff
@@ -113,6 +113,25 @@ public Result sayHello() {
...
+    static class JsonRequestAsAnyClazzAction extends MockJavaAction {
+
+        JsonRequestAsAnyClazzAction(JavaHandlerComponents javaHandlerComponents) {
+            super(javaHandlerComponents);
+        }
+
+        //#json-request-as-anyclazz
+        public Result sayHello() {
+            Person person = request().body().parseJson(Person.class);
+            if(person == null) {
```
Comment (benmccann) [inline documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java]: we always put a space before `(`

File: framework/src/play/src/main/java/play/mvc/Http.java [hunk 4]
```diff
@@ -1875,6 +1875,15 @@ public JsonNode asJson() {
         }
 
         /**
+         * Parses the request body to the expected class.
+         *
+         * @param <A> the type of the return value.
+         * @param clazz Expected Java value type.
+         * @return the return value.
+         */
+        public <A> A parseJson(Class<A> clazz) { return Json.fromJson(asJson(), clazz); }
```
Comment (gmethvin) [inline framework/src/play/src/main/java/play/mvc/Http.java]: Does this work properly if `asJson()` returns null? It would be good to have a test to verify.

I was wondering if `parseJson` should return `Optional<A>` instead. Perhaps that would be weird since `asJson()` can return null, but in the past we've discussed the idea of moving to `Optional` for many parts of the Java API.

File: documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java (hunk 3 above)
Comment (lousanna) [reply documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java]: Oh, got it. Thank you!!

File: framework/src/play/src/main/java/play/mvc/Http.java (hunk 4 above)
Comment (lousanna) [reply framework/src/play/src/main/java/play/mvc/Http.java]: Previously, it just ran into fromJson's exception. Now, I've changed the return type to Optional<A>, and if `asJson()` returns null, Optional.empty() is now returned.
Also added a test to check for the Optional.empty() case. Thanks again!

File: framework/src/play/src/main/java/play/mvc/Http.java [hunk 5]
```diff
@@ -1875,6 +1875,17 @@ public JsonNode asJson() {
         }
 
         /**
+         * Parses the request body to the expected class.
+         *
+         * @param <A> the type of the return value.
+         * @param clazz Expected Java value type.
+         * @return the return value.
```
Comment (richdougherty) [inline framework/src/play/src/main/java/play/mvc/Http.java]: Maybe flesh these docs out a bit more? E.g. mention that this method attempts to parse the body as JSON then convert to a class, say what happens if the body isn't JSON or if JSON parsing fails, say when the `Optional` value is empty, etc.

File: framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala [hunk 6]
```diff
@@ -69,6 +77,15 @@ class JavaJsonSpec extends Specification {
...
     }
+    "deserialize to a POJO from request body" in new JsonScope(Json.newDefaultMapper()) {
+      val javaPOJO = requestHeader.body.parseJson(classOf[JavaPOJO]).get()
+      javaPOJO.getBar must_== "baz"
+      javaPOJO.getFoo must_== "bar"
+      javaPOJO.getInstant must_== Instant.ofEpochSecond(1425435861l)
+      javaPOJO.getOptNumber must_== Optional.of(55555)
+
+      testNoJsonHeader.body.parseJson(classOf[JavaPOJO]) must_== Optional.empty()
+    }
```
Comment (richdougherty) [inline framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala]: Just wondering if there are tests for the method in the following cases:
1. not a JSON body
2. body is JSON but can't be converted to the `JavaPOJO` class

If not, perhaps you could add them to test those code paths. Thanks!

File: documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java [hunk 7]
```diff
@@ -113,6 +114,25 @@ public Result sayHello() {
...
+
+        JsonRequestAsAnyClazzAction(JavaHandlerComponents javaHandlerComponents) {
+            super(javaHandlerComponents);
+        }
+
+        //#json-request-as-anyclazz
+        public Result sayHello() {
+            Optional<Person> person = request().body().parseJson(Person.class);
+            if (!person.isPresent()) {
+                return badRequest("Expecting Json data");
```
Comment (richdougherty) [inline documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java]: Just checking this error message - could this condition happen when there's JSON data but it can't be converted properly to a `Person` class?

File: documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java [hunk 8]
```diff
@@ -113,6 +114,25 @@ public Result sayHello() {
...
+    static class JsonRequestAsAnyClazzAction extends MockJavaAction {
+
+        JsonRequestAsAnyClazzAction(JavaHandlerComponents javaHandlerComponents) {
+            super(javaHandlerComponents);
+        }
+
+        //#json-request-as-anyclazz
+        public Result sayHello() {
+            Optional<Person> person = request().body().parseJson(Person.class);
+            if (!person.isPresent()) {
```
Comment (marcospereira) [inline documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java]: You can rewrite this as:

```java
return person
                .map(p -> ok("Hello, " + p.name))
                .orElse(badRequest("Expecting JSON data"));
```

**Comment by marcospereira** [comment]
Hi @lousanna,

Are you still interested in this PR? I've made a small comment and also think @richdougherty points should be addressed. Do you want/need some help here?

Thanks!

File: documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java (hunk 7 above)
Comment (lousanna) [reply documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java]: So sorry for the late response @richdougherty! Yes, Optional.empty() is returned whenever the body isn't JSON and also if the JSON body cannot be converted properly. Do you think an error message of "Error parsing JSON" or just "Bad request body" would be more appropriate?

File: framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala (hunk 6 above)
Comment (lousanna) [reply framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala]: I think the "testNoJsonHeader" is testing #1, and I've just added a test for #2. Also, I renamed testNoJsonHeader to testNotJsonBody because I realized the name didn't make much sense. 

Questions:
1. Is it fine practice to create multiple variables along the lines of `val validRequest: Request[Http.RequestBody] = Request[Http.RequestBody](FakeRequest(), new RequestBody(testJson))` to address each of the test cases? Or do you suggest a better/less cluttered way?
2. Should I also include a test for if a RequestBody contains a raw JSON string and not a JsonNode? (i.e. new RequestBody("{
  "foo" : "bar",
  "bar" : "baz"
}")) 
If so, should this be parseable?

File: documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java (hunk 8 above)
Comment (lousanna) [reply documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java]: Thank you @marcospereira for the feedback and also for the follow-up!

File: framework/src/play/src/main/java/play/mvc/Http.java (hunk 5 above)
Comment (richdougherty) [reply framework/src/play/src/main/java/play/mvc/Http.java]: I still think these docs could be expanded a bit. (The other methods in this class are a bit light on detail, e.g. none of the `as*` method mention that they can return `null`.)

```scala
/**
 * Converts a JSON request to a given class. Conversion is performed
 * with [[Json.fromJson(JsonNode,Class)]].
 *
 * @param <A> The type to convert the JSON value to.
 * @param clazz The class to convert the JSON value to.
 * @return The converted value if the request has a JSON body or an empty value if the request has an empty body or a body of a different type.
 */

File: framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala [hunk 9]
```diff
@@ -25,7 +28,8 @@ class JavaJsonSpec extends Specification {
         |  "a" : 2.5,
         |  "copyright" : "\u00a9",
         |  "baz" : [ 1, 2, 3 ]
-        |}""".stripMargin
+        |}"""
+    val testJsonString = testJsonStringRaw.stripMargin
```
Comment (richdougherty) [inline framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala]: It's more idiomatic to leave this code as it was before, with a single `val` and a the call `.stripMargin` called directly on the string literal.

File: framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala [hunk 10]
```diff
@@ -39,6 +43,10 @@ class JavaJsonSpec extends Specification {
       .put("copyright", "\u00a9") // copyright symbol
       .set("baz", mapper.createArrayNode().add(1).add(2).add(3))
 
+    val requestHeader: Request[Http.RequestBody] = Request[Http.RequestBody](FakeRequest(), new RequestBody(testJson))
+
+    val testNoJsonHeader: Request[Http.RequestBody] = Request[Http.RequestBody](FakeRequest(), new RequestBody("foo"))
```
Comment (richdougherty) [inline framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala]: I agree with a comment you made elsewhere - these `val`s can be moved into the local scope where they're used. Moving `val`s and `def`s into a local scope reduces their "visibility" and makes it easier to understand the local code.

File: framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala (hunk 6 above)
Comment (richdougherty) [reply framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala]: 1. See comment above.
2. I don't think it's necessary to make a test for a JSON string that has been interpreted as a `String` body.

File: documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java (hunk 7 above)
Comment (richdougherty) [reply documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java]: It's a shame that Jackson makes the fields null if they're missing. However, since that's the existing behaviour I think your code is fine.

**Comment by pedrorijo91** [comment]
what's missing on this PR to be merged? It would be nice to see this merged. It's only because of the title @richdougherty ? If so, can't some maintainer simply edit it instead of losing this work? ¯\_(ツ)_/¯

**Comment by richdougherty** [comment]
@pedrorijo91 thanks for the reminder, this is merged now.
