### PR TITLE
Transactional evolutions: "Try again" button

### LINKED ISSUE #4885: Inconsistent database error is not aware of transactional evolutions
Transactional evolutions don't (well, shouldn't) leave broken state, so the current error language doesn't make a lot of sense.

Current:
ErrorMessage

If nothing else it'd be nice to either change or remove the button to something that is more relevant (like retry).

### PR DESCRIPTION
**Pull request by mkurz**
"Try again" instead of "Mark it resolved" button for transactional evolutions.

Fixes #4885

### CODE REVIEW

**Comment by mkurz** [comment]
Build is green and ready to review/merge.
I have another PR which I am holding back until this one gets merged.

**Comment by mkurz** [comment]
@jroper Could you please merge? I have another PR for #4720 based on this one. Thank you!

File: framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala [hunk 1]
```diff
@@ -526,21 +527,31 @@ object SimpleEvolutionsReader {
...
+  private val sentenceEnd = (if (autocommit) " before marking it as resolved." else ".")
+
+  private val buttonLabel = (if (autocommit) """Mark it resolved""" else """Try again""")
 
   def htmlDescription: String = {
 
-    <span>An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved -</span>
-    <input name="evolution-button" type="button" value="Mark it resolved" onclick={ javascript }/>
+    <span>An evolution has not been applied properly. Please check the problem and resolve it manually{ sentenceEnd } -</span>
+    <input name="evolution-button" type="button" value={ buttonLabel } onclick={ javascript }/>
```
Comment (gmethvin) [inline framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala]: I think it would be better to just make this a link. The onclick just changes the location.

Comment (mkurz) [inline framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala]: Yeah, but it uses javascript's `encodeURIComponent(...)` to provide a redirect url, see line 538 above

Comment (gmethvin) [inline framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala]: Okay, sure. Now I see how it's being rendered (from PlayException, which doesn't have access to the request) it makes more sense we're using JS.

File: framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala [hunk 2]
```diff
@@ -526,21 +527,31 @@ object SimpleEvolutionsReader {
...
   def subTitle = "We got the following error: " + error + ", while trying to run this SQL script:"
   def content = script
 
+  private val resolvePath = if (autocommit) {
+    "/resolve/%s/%s?redirect=' + encodeURIComponent(location)".format(db, rev)
+  } else {
+    "'"
+  }
+
   private val javascript = """
```
Comment (gmethvin) [inline framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala]: This is a bit clearer I think (wrt handling of quotes):
```scala
private val resolvePathJavascript =
  if (autocommit) s"'/evolutions/resolve/$db/$rev/?redirect=' + encodeURIComponent(window.location)"
  else s"'/evolutions/'"
private val redirectJavascript = s"window.location = $resolvePathJavascript"
```

**Comment by mkurz** [comment]
@gmethvin Updated the PR with your suggestions.

**Comment by mkurz** [comment]
Ping @gmethvin :smile:
