### PR TITLE
Fixes HTTP and HTTPS port binding in DEV mode

### LINKED ISSUE #9055: Binding both HTTP and HTTPS ports when running in dev
### Play Version (2.5.x / etc)
2.6.15

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
macOS 10.14.3

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_181

### Library Depedencies
`play-sbt`

### Expected Behavior

I bind the ports for development in sbt with: 
```
PlayKeys.devSettings ++= Seq("play.server.http.port" -> "9090", "play.server.https.port" -> "9443")
```

Using `run` should start listeners for both HTTP and HTTPS.

### Actual Behavior
When I execute `run`

image

When I execute `run -Dhttps.port=9443`

image

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #9055

### CODE REVIEW

File: transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala [hunk 1]
```diff
@@ -47,7 +47,22 @@ object DevServerStart {
    * compiled with different versions of Scala.
    */
   def mainDevHttpMode(buildLink: BuildLink, httpPort: Int, httpAddress: String): ReloadableServer = {
-    mainDev(buildLink, Some(httpPort), Option(System.getProperty("https.port")).map(Integer.parseInt), httpAddress)
```
Comment (mkurz) [inline transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala]: `System.getProperty("https.port")` definitely needs to be removed here, because the only place we decide what ports are set is within `Reloader.scala`. Here we don't decide anything anymore.

**Comment by renatocaval** [comment]
Backported to 2.7.x (c34e72ebb8ffa6645507c33a955ff7ad479b5e8b)
