### PR TITLE
Make sure context.withRequest maintains original session and flash

### LINKED ISSUE #7328: Session clear is not working (using AuthenticatedAction)
**Play Version** 
2.6.0-M5

**API (Scala / Java / Neither / Both)**
Java

**Expected Behavior**
After migrating to 2.6 my session.clear() calls stopped working

### PR DESCRIPTION
**Pull request by gmethvin**
The `play.mvc.Http.Context#withRequest` method should maintain the original `Session`, `Flash`, and `Response` references, so all changes can be read by `JavaAction`. Otherwise, modifications made inside the action will not be propagated up the chain.

This looks like it has actually been a bug for a while, but we only recently noticed it because we started using this method in `AuthenticatedAction`.

Fixes #7328.

### CODE REVIEW

File: framework/src/play/src/main/java/play/mvc/Http.java [hunk 1]
```diff
@@ -122,7 +122,9 @@ public Context(Request request, JavaContextComponents components) {
          * @param args any arbitrary data to associate with this request context.
          * @param components the context components.
          */
-        public Context(Long id, play.api.mvc.RequestHeader header, Request request, Map<String,String> sessionData, Map<String,String> flashData, Map<String,Object> args, JavaContextComponents components) {
+        public Context(Long id, play.api.mvc.RequestHeader header, Request request,
+            Map<String,String> sessionData, Map<String,String> flashData, Map<String,Object> args,
```
Comment (benmccann) [inline framework/src/play/src/main/java/play/mvc/Http.java]: usually a continuation of the line before is double indented. so this should be indented another four spaces so that it doesn't line up with "this.id" anymore. (I prefer two spaces for indention over four, but this file is already using four)

File: framework/src/play/src/main/java/play/mvc/Http.java [hunk 2]
```diff
@@ -122,7 +122,9 @@ public Context(Request request, JavaContextComponents components) {
          * @param args any arbitrary data to associate with this request context.
          * @param components the context components.
          */
-        public Context(Long id, play.api.mvc.RequestHeader header, Request request, Map<String,String> sessionData, Map<String,String> flashData, Map<String,Object> args, JavaContextComponents components) {
+        public Context(Long id, play.api.mvc.RequestHeader header, Request request,
```
Comment (marcospereira) [inline framework/src/play/src/main/java/play/mvc/Http.java]: This constructor can use the other one:

```java
public Context(...) {
    this(id, header, request, new Response(), new Session(sessionData), ...);
}
```

File: framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala [hunk 3]
```diff
@@ -71,6 +72,19 @@ class JavaActionCompositionSpec extends PlaySpecification with WsTestClient {
     }) { response =>
       response.body must_== "foo"
     }
+    "ensure context.withRequest in an Action maintains Session and Response" in makeRequest(new MockController {
```
Comment (marcospereira) [inline framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala]: We should also test flash scope here. Maybe split these in more smaller/specific tests.

File: framework/src/play/src/main/java/play/mvc/Http.java (hunk 1 above)
Comment (gmethvin) [inline framework/src/play/src/main/java/play/mvc/Http.java]: ok. I prefer two spaces as well but for some reason Play has always used four. Maybe at some point we should just change all the files to two spaces.

File: framework/src/play/src/main/java/play/mvc/Http.java (hunk 2 above)
Comment (gmethvin) [inline framework/src/play/src/main/java/play/mvc/Http.java]: done

**Comment by gmethvin** [comment]
updated

File: framework/src/play/src/main/java/play/mvc/Http.java (hunk 1 above)
Comment (marcospereira) [inline framework/src/play/src/main/java/play/mvc/Http.java]: Ideally, we would use something like scalariform for Java source code.
