### PR TITLE
HTTP 400 instead of 500 on Unicode headers

### LINKED ISSUE #10944: Unicode header values should not cause server errors
### Play Version

2.8.8

### API

Scala

### Expected Behavior

When receiving headers with Unicode values, Play server should do either of the following:

1. Return HTTP 400, based on the request header being invalid as per [RFC2616](https://datatracker.ietf.org/doc/html/rfc2616#section-4.2)
2. Be lenient and accept Unicode headers just as it accepts Ascii headers (we received this header through several routing layers, so evidently there are some tech stacks out there that tolerate Unicode headers)

### Actual Behavior

When receiving headers with Unicode values, the following happens:

1. An error is logged with the following message:
```
Exception occurred while converting Result with headers [<myHeader>: <독골사거리역더퍼스트뷰>, ...]. Calling HttpErrorHandler to get alternative Result.
```
And the following stack trace:
```
java.lang.IllegalArgumentException: Character 46021 cannot match AsciiSet because it is out of range
        at play.core.utils.AsciiBitSet.get(AsciiSet.scala:94)
	at play.core.server.common.ServerResultUtils.loop$1(ServerResultUtils.scala:130)
        ...
```
This one is explicitly logged at [ServerResultUtils:166](https://github.com/playframework/playframework/blob/2.8.x/transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala#L166) - this log should be info level, not error level.

I assume there could in theory be server-caused conversion errors that deserve the error level, so it may be needed to differentiate on the type of `Throwable` received as parameter.

2. Another error is logged with the following message:
```
! @7kjn33i1p - Internal server error, for (GET) [/myRoute] ->
```
And the following stack trace:
```
play.api.UnexpectedException: Unexpected exception[ServerResultException: Error converting Play Result for server backend]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
	at play.core.server.common.ServerResultUtils.play$core$server$common$ServerResultUtils$$handleConversionError$1(ServerResultUtils.scala:173)
        ...
```
This one is caused by [ServerResultUtils:171](https://github.com/playframework/playframework/blob/2.8.x/transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala#L171) "throwing" an exception that bubbles all the way up. In this case it is not a server error, but a client error, so `onClientError` should be called instead of `onServerError`.

The same remark on error types applies as in point 1 above.

3. The client receives an HTTP 500 reponse, when in reality it is the client that is at fault, so it should be HTTP 400. This has the same cause as point 2 above and would be fixed at the same time.

### PR DESCRIPTION
**Pull request by bursauxa**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* ~~Have you checked that both Scala and Java APIs are updated?~~
* ~~Have you updated the documentation for both Scala and Java sections?~~
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #10944

## Purpose

Return HTTP 400 instead of 500 when headers contain non-Ascii characters, and avoid writing error logs in such cases.

## Background Context

Another option would be to allow Unicode characters to go through, even though the RFCs do not allow it.
Even then, there would be more malicious cases (e.g. control characters) that should be rejected without causing server errors, so this fix would be required anyways.

### CODE REVIEW

**Comment by bursauxa** [comment]
Build is green now :tada:

File: transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala [hunk 1]
```diff
@@ -156,30 +156,43 @@ private[play] final class ServerResultUtils(
...
         }
 
         // Call the HttpErrorHandler to generate an alternative error
-        errorHandler
-          .onServerError(
+        val futureErrorResult = if (isInvalidHeaderCharacter) {
+          errorHandler.onClientError(
+            requestHeader,
+            400,
+            s"Invalid header: ${conversionError.getMessage()}"
```
Comment (gmethvin) [inline transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala:179]: It might be useful if we included the original string and the position in the string where we found the invalid character.

**Review by gmethvin — COMMENTED** [review]
We should try to avoid throwing and catching exceptions if we can, the caller has to be aware that it throws, so it's easy to forget to handle that case in new code. These are all internal `private[play]` APIs, so we can change the APIs to make them return some representation of the error, maybe `Either[InvalidCharacter, Unit]` instead of `Unit` for example.

**Comment by bursauxa** [comment]
> We should try to avoid throwing and catching exceptions if we can. Since the caller has to be aware that the method throws, it's easy to forget to handle that case and introduce bugs in new code. These are all internal `private[play]` APIs, so we can change the APIs to make them return some representation of the error, maybe `Either[InvalidCharacter, Unit]` instead of `Unit` for example.

I absolutely agree on the use of Either vs exceptions, but all the code I touched for this request had pre-existing exception-style structure. I feel like changing it all would be a significant refactoring (beyond the scope of this request), and using Either for a small fresh part would have a greater cost in terms of inconsistency within the class than benefits in terms of Scala quality.

As for the other comment, I will address it when I get back to an IDE 😉

**Review by gmethvin — APPROVED** [review]
