### PR TITLE
Use uri parsing mode "relaxed" in akka-http 10.2.x

### LINKED ISSUE #11113: Fix failing tests after upgrade to akka-http 10.2.x
In #11081 akka-http got upgraded, which resulted in two [failing tests](https://app.travis-ci.com/github/playframework/playframework/jobs/554669370#L2883):
```
[info] UriHandlingSpec
[info] Server should
[info]   preserve order of repeated query string parameters
[info]     + with Netty HTTP/1.1 (plaintext) (2 seconds, 151 ms)
[info]     + with Netty HTTP/1.1 (encrypted) (2 seconds, 196 ms)
[info]     + with Akka HTTP HTTP/1.1 (plaintext) (160 ms)
[info]     + with Akka HTTP HTTP/1.1 (encrypted) (163 ms)
[info]     + with Akka HTTP HTTP/2 (encrypted) (249 ms)
[info]   handle '/pat/resources/BodhiApplication?where={%22name%22:%22hsdashboard%22}' as a valid URI
[info]     + with Netty HTTP/1.1 (plaintext) (2 seconds, 172 ms)
[info]     + with Netty HTTP/1.1 (encrypted) (2 seconds, 183 ms)
[error]     x with Akka HTTP HTTP/1.1 (plaintext) (146 ms)
[error]      'Illegal request-target: Invalid input '{', expected query-char, pct-encoded or 'EOI' (line 1, column 39)' != '/pat/resources/BodhiApplication?where={"name":"hsdashboard"}' (UriHandlingSpec.scala:60)
[error] Actual:   Illegal request-target: Invalid input '{', expected query-char, pct-encoded or 'EOI' (line 1, column 39)
[error] Expected: /pat/resources/BodhiApplication?where={"name":"hsdashboard"}
[error]     x with Akka HTTP HTTP/1.1 (encrypted) (287 ms)
[error]      'Illegal request-target: Invalid input '{', expected query-char, pct-encoded or 'EOI' (line 1, column 39)' != '/pat/resources/BodhiApplication?where={"name":"hsdashboard"}' (UriHandlingSpec.scala:60)
[error] Actual:   Illegal request-target: Invalid input '{', expected query-char, pct-encoded or 'EOI' (line 1, column 39)
[error] Expected: /pat/resources/BodhiApplication?where={"name":"hsdashboard"}
```
To move on I just disabled the tests for now (https://github.com/playframework/playframework/pull/11081/files#diff-f4ddb770288fea113964ef88cc5d51deb88afbaf4a0439a2e92d3baa4606198c), however before cutting Play we definitely need to find out why tests fail and fix them.

I am pretty sure the failing tests are caused by https://github.com/akka/akka-http/pull/3003, that's why I tried adding
```
akka {
  ...
  http {
    server.parsing.uri-parsing-mode = relaxed
  }
  ...
}
```
to the `reference.conf` of the akka-http backend, however that didn't work.

(Also not sure anymore, but maybe #7427 is relevant as well (?))

### PR DESCRIPTION
**Pull request by mkurz**
Partly fixes #11113 by enabling one of the two tests that had do be disabled when ugrading akka-http to 10.2.x.

~akka-http 10.2.0 introduced a parsing mode, which by default is set to strict~ (I was wrong here, the parsing mode existed before already). See
* comments in akka's reference.conf: https://github.com/akka/akka-http/blob/v10.2.10/akka-http-core/src/main/resources/reference.conf#L690-L698
* https://github.com/akka/akka-http/issues/3504

### CODE REVIEW

**Comment by mkurz** [comment]
Changing to relaxed now revealed a flaw in the akka-http server backend.... To fix that it needs some more changes in the akka-http backend... More details soon.

File: transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala [hunk 1]
```diff
@@ -46,33 +47,45 @@ private[server] class AkkaModelConversion(
...
       secureProtocol: Boolean,
       request: HttpRequest
-  ): (RequestHeader, Either[ByteString, Source[ByteString, Any]]) = {
-    (
-      convertRequestHeader(requestId, remoteAddress, secureProtocol, request),
-      convertRequestBody(request)
-    )
+  ): Try[RequestHeader] = Try {
+    val headers                         = convertRequestHeadersAkka(request)
+    val (parsedPath, parsedQueryString) = PathAndQueryParser.parse(headers.uri)
```
Comment (mkurz) [inline transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala:58]: This line is key of this pull request. Now the path is parsed eagerly which can lead to an exception, which in turn will be handled and passed on as 400 bad request now.

File: transport/server/play-server/src/main/scala/play/core/server/Server.scala [hunk 2]
```diff
@@ -142,6 +143,45 @@ object Server {
     EssentialAction(_ => Accumulator.done(errorResult))
   }
 
+  /**
+   * Create request target information from a request uri String where
+   * there was a parsing failure.
+   */
+  private[server] def createUnparsedRequestTarget(requestUri: String): RequestTarget = new RequestTarget {
```
Comment (mkurz) [inline transport/server/play-server/src/main/scala/play/core/server/Server.scala:150]: This method is need in all backends, so I moved it here.

File: transport/server/play-server/src/main/scala/play/core/server/common/PathAndQueryParser.scala [hunk 3]
```diff
@@ -33,10 +33,17 @@ private[server] object PathAndQueryParser {
     val queryString = withoutHost.substring(pathEndPos, queryEndPos)
 
     // wrapping into URI to handle absoluteURI and path validation
-    val parsedPath = Option(new URI(unsafePath).getRawPath).getOrElse {
```
Comment (mkurz) [inline transport/server/play-server/src/main/scala/play/core/server/common/PathAndQueryParser.scala:36]: This `Option(new URI(unsafePath).getRawPath).getOrElse (...)` never worked, the `getOrElse` was more or less unreachable code. If there is an exception when creating the `URI´ it will directly be thrown, `getOrElse` not be reached anymore.
So this code was obviously broken.

File: core/play-integration-test/src/it/scala/play/it/http/UriHandlingSpec.scala [hunk 4]
```diff
@@ -48,15 +48,13 @@ class UriHandlingSpec
         response.body.string must_== "a=1&b=1&b=2&b=3&b=4&b=5"
       }
     }
-    /*
```
Comment (mkurz) [inline core/play-integration-test/src/it/scala/play/it/http/UriHandlingSpec.scala:51]: :partying_face:

**Review by mkurz — COMMENTED** [review]
Refactored the akka-http backend a bit. It now is a bit more similar to the netty backend, which totally makes sense, since we want to catch parsing errors as soon as possible, which netty already is doing. For me a proof that this totally makes sense is that I was able to enable a previously disabled test for the akka-backend (which was enabled for netty already) - which I was not even intending to fix :wink: 

I tried to be as clear as possible by splitting most things in separate commits.

File: core/play-integration-test/src/it/scala/play/it/http/BadClientHandlingSpec.scala [hunk 5]
```diff
@@ -75,15 +75,15 @@ trait BadClientHandlingSpec extends PlaySpecification with ServerIntegrationSpec
...
+        Future.successful(Results.BadRequest("Bad path: " + request.path + " message: " + message))
       def onServerError(request: RequestHeader, exception: Throwable) = Future.successful(Results.Ok)
     }) { port =>
       val response = BasicHttpClient.makeRequests(port)(
         BasicRequest("GET", "/[", "HTTP/1.1", Map(), "")
       )(0)
 
       response.status must_== 400
-      response.body must beLeft("Bad path: /[")
-    }.skipUntilAkkaHttpFixed
```
Comment (mkurz) [inline core/play-integration-test/src/it/scala/play/it/http/BadClientHandlingSpec.scala:87]: I just double checked: The akka-http test is failing on current main branch, so this PR definitely fixed that :tada:

**Comment by mkurz** [comment]
For the sake of completeness, here is [the important part of the akka-http 10.2.0 release notes](https://doc.akka.io/docs/akka-http/current/migration-guide/migration-guide-10.2.x.html#strict-query-strings):

> **Strict query strings**
In 10.1.x, while parsing the query string of a URI, characters were accepted that are not allowed according to RFC 3986, even when `parsing.uri-parsing-mode` was set to the default value of `strict`. Parsing such URIs will now fail in `strict` mode. If you want to allow such characters in incoming URIs, set `parsing.uri-parsing-mode` to `relaxed`, in which case these characters will be percent-encoded automatically.
