### PR TITLE
Fix i18n locale lookup behavior

### LINKED ISSUE #8953: i18n matching inversely
### Play Version (2.5.x / etc)

2.6

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.12 (Sierra)

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

### Expected Behavior

1. application.conf is like below

```
play.i18n.langs = [ "ja", "ja-JP", "en", "en-US" ]
```

2. access with `Accept-Language: en-GB`

3. `en` is chosen for rendering

### Actual Behavior

3. default lang `ja` is chosen

According to the Stackoverflow, in this case, `en-GB` should be matched with `en`:
https://stackoverflow.com/questions/30754287/java-8-locale-lookup-behavior

I found this issue could be occurred because of the code below

https://github.com/playframework/playframework/blob/8793cfaa568f79e822cb11c1d6a156331ca9ba74/framework/src/play/src/main/scala/play/api/i18n/Langs.scala#L58

According to the Javadoc of `Locale#lookup` , first parameter should be `user's Language Priority List` and second be `instances used for matching`, but actually it is in inverse.

### PR DESCRIPTION
**Pull request by golemiso**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #8953

## Purpose

This fixes i18n locale lookup behavior  for satisfying RFC 4647.

## Background Context

I am developing Japanese language defaulted system which also supports English.
Although i18n setting is below, `Accept-Language: en-GB` does not much `en` and defaults to `ja`.

```
play.i18n.langs = [ "ja", "ja-JP", "en", "en-US" ]
```

I think that following the Language Lookup behavior described in RFC 4647 section 3.4. is preferable for the better i18n support.

## References

* #8953
* [RFC 4647](https://www.ietf.org/rfc/rfc4647.txt)
* https://discuss.lightbend.com/t/play-2-6-i18n-locale-lookup-behavior/3239

Thank you for your taking time 😄

### CODE REVIEW

File: core/play/src/main/scala/play/api/i18n/Langs.scala [hunk 1]
```diff
@@ -57,6 +57,7 @@ case class Lang(locale: Locale) {
    *
    * @param accept The accepted language
    */
+  @deprecated("For the Locale Lookup, use Langs#preferred instead", "2.7.0")
```
Comment (marcospereira) [inline core/play/src/main/scala/play/api/i18n/Langs.scala]: Why deprecate this?

Comment (marcospereira) [inline core/play/src/main/scala/play/api/i18n/Langs.scala]:
```suggestion
  @deprecated("For the Locale Lookup, use Langs#preferred instead", "2.8.0")
```

Comment (marcospereira) [reply core/play/src/main/scala/play/api/i18n/Langs.scala]: We won't backport it to 2.7, so if we decide that it is better to deprecate, it will be in 2.8.0.

Comment (golemiso) [reply core/play/src/main/scala/play/api/i18n/Langs.scala]: Because the Locale Lookup feature requires all user's preferred languages and all available languages, while the usage of `Locale.lookup` in this method does not follow this.
Existence of this method will cause confusion.
