### PR TITLE
Avoid error at shutdown if tmpdir is not writeable but was not used in the first place

### LINKED ISSUE #13013: Error at shutdown if tmpdir is not writeable even though it is not used
_Version: Play 3.0.6_

During shutdown, the application can throw and log an error because the temporary directory used by Play is not writeable even though this directory was never used in the first place.

This is likely to happen in containerized environments with read-only filesystem as a default setup.

---

**Stack trace:**
```
java.nio.file.FileSystemException: /tmp/playtemp8313349136202869755: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.TempFileHelper.create(Unknown Source)
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createTempDirectory(Unknown Source)
	at play.api.libs.Files$DefaultTemporaryFileCreator.playTempFolder$lzycompute(Files.scala:263)
	at play.api.libs.Files$DefaultTemporaryFileCreator.play$api$libs$Files$DefaultTemporaryFileCreator$$playTempFolder(Files.scala:260)
	at play.api.libs.Files$DefaultTemporaryFileCreator.$anonfun$new$1(Files.scala:320)
	at scala.util.Try$.apply(Try.scala:217)
	at play.api.inject.DefaultApplicationLifecycle.$anonfun$stop$2(ApplicationLifecycle.scala:128)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:65)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
	at play.api.inject.DefaultApplicationLifecycle.clearHooks$1(ApplicationLifecycle.scala:127)
	at play.api.inject.DefaultApplicationLifecycle.stop(ApplicationLifecycle.scala:139)
	at play.api.libs.concurrent.CoordinatedShutdownProvider.$anonfun$get$2(Pekko.scala:305)
	at org.apache.pekko.actor.CoordinatedShutdown$tasks$TaskDefinition$$anon$2.liftedTree1$1(CoordinatedShutdown.scala:438)
	at org.apache.pekko.actor.CoordinatedShutdown$tasks$TaskDefinition$$anon$2.run(CoordinatedShutdown.scala:437)
	at org.apache.pekko.actor.CoordinatedShutdown$tasks$StrictPhaseDefinition.$anonfun$run$3(CoordinatedShutdown.scala:496)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.collection.immutable.Set$Set1.map(Set.scala:165)
	at org.apache.pekko.actor.CoordinatedShutdown$tasks$StrictPhaseDefinition.run(CoordinatedShutdown.scala:496)
	at org.apache.pekko.actor.CoordinatedShutdown.loop$1(CoordinatedShutdown.scala:745)
	at org.apache.pekko.actor.CoordinatedShutdown.$anonfun$run$7(CoordinatedShutdown.scala:773)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
	at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
	at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

---

This happens because a stop hook is registered to clean the temporary directory but the directory is created only at first access. If the app doesn't need temporary files, the directory is never created and the stop hook thus tries to create it only to delete it afterwards.

**Related sources:**

https://github.com/playframework/playframework/blob/28447a52805ba5c082c8fd6e6a3dd9ba583b933d/core/play/src/main/scala/play/api/libs/Files.scala#L318-L320

https://github.com/playframework/playframework/blob/28447a52805ba5c082c8fd6e6a3dd9ba583b933d/core/play/src/main/scala/play/api/libs/Files.scala#L260-L266

---

While the error is definitely not an issue, it can raise false alerts for systems watching ERROR logs.

**I would suggest to have a way to know if the directory was never created and thus do not try to clean anything. WDYT?**

### PR DESCRIPTION
**Pull request by gaeljw**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #13013 

## Purpose

Do not try to delete the temporary folder during shutdown if it was never created in the 1st place. Because when trying to delete, it actually tries to create the folder if it was not already created. This is useless and can cause errors with read-only filesystems.

## Background Context

I used a simple mutable `var` as I believe this is enough in this context: the `var` is private, in a singleton, only set during a `lazy val` initialization.
However, if you believe we should use an `AtomicBoolean`, just say it :)

Note that I didn't add test, not sure if this is worth it and I'm not sure how to approach writing such a test.

## References

N/A

### CODE REVIEW

File: core/play/src/main/scala/play/api/libs/Files.scala [hunk 1]
```diff
@@ -256,11 +256,13 @@ object Files {
     // Keeping references ensures that the FinalizablePhantomReference itself is not garbage-collected.
     private val references = Sets.newConcurrentHashSet[Reference[TemporaryFile]]()
 
-    private val TempDirectoryPrefix = "playtemp"
+    private val TempDirectoryPrefix        = "playtemp"
+    private var TempFolderCreated: Boolean = false
```
Comment (ihostage) [inline core/play/src/main/scala/play/api/libs/Files.scala:260]: Hi, @gaeljw! Thanks a lot to your contribution 👍 
In common I agree with this approach, but personally, I would prefer to change type of private `playTempFolder` and use `Option/Either` for them instead of add a new boolean field. It'll be a more idiomatic way instead of manually sync a state of two `Path` and `Boolean` vars 😉

Comment (gaeljw) [reply core/play/src/main/scala/play/api/libs/Files.scala:260]: @ihostage I agree it's not the best pattern but I wanted to keep the laziness of `playTempFolder`.

Are you suggesting to have a mutable `Option[Path]` and replace the `lazy val` creation of the folder by something like `playTempFolder.getOrElse(create...)` in the `create` method?

Comment (ihostage) [reply core/play/src/main/scala/play/api/libs/Files.scala:260]: No, I thought like this
```scala
private lazy val playTempFolder: Either[Throwable, Path] =
      try {
        ...
        Right(tmpFolder)
      } catch {
        case t: Throwable => Left(t)
      }
```
But now, I realize that this approach still creates and deletes a temporary folder unnecessarily, just potentially hide an error message in the log via the stop hook implementation. I don't like this. 😄 
Need to think 🤔

Comment (mkurz) [reply core/play/src/main/scala/play/api/libs/Files.scala:260]: I implemented the alternative you talked about in #13110

What do you guys think / prefer?
I don't really care.

Comment (gaeljw) [reply core/play/src/main/scala/play/api/libs/Files.scala:260]: Slight preference for my initial proposal that I find more explicit but I'm fine with yours as well.

Let's get one of the two merged :)

Comment (mkurz) [reply core/play/src/main/scala/play/api/libs/Files.scala:260]: The alternative suggestion does not work anyway, because it can cause race conditions, see https://github.com/playframework/playframework/pull/13110#discussion_r1957281123

Therefore lets just merge this PR finally.

**Review by mkurz — APPROVED** [review]

**Comment by mkurz** [comment]
@Mergifyio backport 3.0.x 2.9.x

**Comment by mkurz** [comment]
We can include this in our next patch release.
