### PR TITLE
WebSocket endpoints returning 400 for HEAD requests

### LINKED ISSUE #4878: HEAD request on websocket throws ugly 500
Tripped over this by complete coincidence, but when you do a `HEAD` request to a websocket endpoint, you get a ugly internal server error (see stacktrace at the bottom).

I started poking around, but this is the only case I could come up with that would break, so I'm guessing this is the automagic `GET`s-also-serve-`HEAD`s code messing things up here, probably failing to return a `WebSocket.reject response`.
Other things I tried, but were handled perfectly fine:
- normal `GET` request to the websocket endpoint, without websocket headers (`400 bad request`, expecting this from the `HEAD` request too)
- other HTTP method requests (like `DELETE`, `OPTION`, `PUT`) to the websocket endpoint (`404 not found`)
- `HEAD` request to non websocket endpoints (`200 OK`)

It would be nice to get a clean response instead of a nasty stacktrace, even though it is unlikely that someone will run in to this.

```
[ERROR] from application in New I/O worker #19 - ! @6mpedf1kb - Internal server error, for (HEAD) [/news/stream] -> play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MatchError: Some(WebSocket(<function1>)) (of class scala.Some)]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:59) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57) [play-server_2.11-2.4.2.jar:2.4.2]
    at scala.util.Either$RightProjection.flatMap(Either.scala:522) [scala-library-2.11.7.jar:na]
    at play.core.server.Server$class.getHandlerFor(Server.scala:57) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:33) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at scala.util.Either.fold(Either.scala:99) [scala-library-2.11.7.jar:na]
    at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:127) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
    at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [netty-http-pipelining-1.1.4.jar:na]
    at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.3.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: scala.MatchError: Some(WebSocket(<function1>)) (of class scala.Some)
    at play.api.GlobalSettings$$anonfun$3.apply(GlobalSettings.scala:119) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.api.GlobalSettings$$anonfun$3.apply(GlobalSettings.scala:113) ~[play_2.11-2.4.2.jar:2.4.2]
    at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
    at play.api.GlobalSettings$class.onRequestReceived(GlobalSettings.scala:113) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.core.j.JavaGlobalSettingsAdapter.onRequestReceived(JavaGlobalSettingsAdapter.scala:14) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.api.http.GlobalSettingsHttpRequestHandler.handlerForRequest(HttpRequestHandler.scala:183) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:38) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:37) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.7.jar:na]
    at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:na]
    at scala.util.Success.map(Try.scala:237) ~[scala-library-2.11.7.jar:na]
    at play.core.server.Server$class.sendHandler$1(Server.scala:37) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:58) [play-server_2.11-2.4.2.jar:2.4.2]
    ... 38 common frames omitted
```

### PR DESCRIPTION
**Pull request by marcospereira**
## Fixes

Fixes #4878.

## Purpose

As suggested by @gmethvin (https://github.com/playframework/playframework/issues/4878#issuecomment-125174212), `HEAD` request against ws endpoints will now respond with a Bad Request (`400`).

## References

See #7057 and #7059.

### CODE REVIEW

File: framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala [hunk 1]
```diff
@@ -109,26 +109,37 @@ class DefaultHttpRequestHandler(router: Router, errorHandler: HttpErrorHandler,
...
-          // An Action for a 404 error
-          ActionBuilder.ignoringBody.async(BodyParsers.utils.empty)(req =>
-            errorHandler.onClientError(req, NOT_FOUND)
-          )
+      routeRequest(request).getOrElse {
+        request.method match {
+          // We automatically permit HEAD requests against any GETs without the need to
+          // add an explicit mapping in Routes. Since we couldn't route the HEAD request,
+          // try to get a Handler for the equivalent GET request instead. Note: the handler
+          // returned will still be passed a HEAD request when it is actually evaluated.
```
Comment (richdougherty) [inline framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala]: This comment needs to be updated to say that we don't permit HEAD requests for WebSocket Handlers.

Comment (marcospereira) [inline framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala]: Done!

**Comment by marcospereira** [comment]
@richdougherty this is ready to be reviewed again. :-)

**Comment by marcospereira** [comment]
Thanks @richdougherty.

Do you mind also taking a look at #7057 and #7059?
