### PR TITLE
Handle incorrect percent-encoded query chars

### LINKED ISSUE #11113: Fix failing tests after upgrade to akka-http 10.2.x
In #11081 akka-http got upgraded, which resulted in two [failing tests](https://app.travis-ci.com/github/playframework/playframework/jobs/554669370#L2883):
```
[info] UriHandlingSpec
[info] Server should
[info]   preserve order of repeated query string parameters
[info]     + with Netty HTTP/1.1 (plaintext) (2 seconds, 151 ms)
[info]     + with Netty HTTP/1.1 (encrypted) (2 seconds, 196 ms)
[info]     + with Akka HTTP HTTP/1.1 (plaintext) (160 ms)
[info]     + with Akka HTTP HTTP/1.1 (encrypted) (163 ms)
[info]     + with Akka HTTP HTTP/2 (encrypted) (249 ms)
[info]   handle '/pat/resources/BodhiApplication?where={%22name%22:%22hsdashboard%22}' as a valid URI
[info]     + with Netty HTTP/1.1 (plaintext) (2 seconds, 172 ms)
[info]     + with Netty HTTP/1.1 (encrypted) (2 seconds, 183 ms)
[error]     x with Akka HTTP HTTP/1.1 (plaintext) (146 ms)
[error]      'Illegal request-target: Invalid input '{', expected query-char, pct-encoded or 'EOI' (line 1, column 39)' != '/pat/resources/BodhiApplication?where={"name":"hsdashboard"}' (UriHandlingSpec.scala:60)
[error] Actual:   Illegal request-target: Invalid input '{', expected query-char, pct-encoded or 'EOI' (line 1, column 39)
[error] Expected: /pat/resources/BodhiApplication?where={"name":"hsdashboard"}
[error]     x with Akka HTTP HTTP/1.1 (encrypted) (287 ms)
[error]      'Illegal request-target: Invalid input '{', expected query-char, pct-encoded or 'EOI' (line 1, column 39)' != '/pat/resources/BodhiApplication?where={"name":"hsdashboard"}' (UriHandlingSpec.scala:60)
[error] Actual:   Illegal request-target: Invalid input '{', expected query-char, pct-encoded or 'EOI' (line 1, column 39)
[error] Expected: /pat/resources/BodhiApplication?where={"name":"hsdashboard"}
```
To move on I just disabled the tests for now (https://github.com/playframework/playframework/pull/11081/files#diff-f4ddb770288fea113964ef88cc5d51deb88afbaf4a0439a2e92d3baa4606198c), however before cutting Play we definitely need to find out why tests fail and fix them.

I am pretty sure the failing tests are caused by https://github.com/akka/akka-http/pull/3003, that's why I tried adding
```
akka {
  ...
  http {
    server.parsing.uri-parsing-mode = relaxed
  }
  ...
}
```
to the `reference.conf` of the akka-http backend, however that didn't work.

(Also not sure anymore, but maybe #7427 is relevant as well (?))

### PR DESCRIPTION
**Pull request by mkurz**
Fully fixes #11113
Since akka-http 10.2.0, an incorrect percent-encoded uri character will be immediately handled as 400 bad request by akka-http. It gives us (Play) no chance to handle that, so we never see this error in the Play akka-http backend. There is nothing we can do really. So I had to adjust the test, and as part of that I also made netty behave the same (not going through the error handler when it parses incorrect percent-encoded chars). This is because I want to have both http backends to be as much compatible as possible in case one gets replaced by the other.

### CODE REVIEW

File: core/play-integration-test/src/it/scala/play/it/http/UriHandlingSpec.scala [hunk 1]
```diff
@@ -86,14 +96,25 @@ class UriHandlingSpec
...
-    /*
-    "handle '/pat?param=%_D%' as a URI with an invalid query string" in makeRequest(
-      "/pat?param=%_D%"
+
+    "handle '/pat?param=%_D%' as a URI with an invalid percent-encoded character in query string" in makeRequest(
+      "/pat?param=%_D%",
+      // TODO: Disabled the (secure) akka-http2 test, an URI parsing bug causes requests to be stuck forever, never reaching Play:
+      // https://github.com/apache/incubator-pekko-http/issues/59
+      // https://github.com/akka/akka-http/issues/4226
+      skipAkkaHttps2 = true
```
Comment (mkurz) [inline core/play-integration-test/src/it/scala/play/it/http/UriHandlingSpec.scala:105]: So I bumped into an issue of with the HTTP/2 support in akka-http, also opened an issue in pekko to let them know:
* https://github.com/akka/akka-http/issues/4226
* https://github.com/apache/incubator-pekko-http/issues/59

File: transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala [hunk 2]
```diff
@@ -99,11 +99,12 @@ private[server] class NettyModelConversion(
       override def uriString: String   = request.uri
       override val path: String        = parsedPath
       override val queryString: String = parsedQueryString.stripPrefix("?")
-      override lazy val queryMap: Map[String, Seq[String]] = {
+      override val queryMap: Map[String, Seq[String]] = {
```
Comment (mkurz) [inline transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala:102]: `lazy` needs to be removed here so the parsing is done eagerly, which, when causing the exception, is then handled as http 400.

**Comment by mkurz** [comment]
Going to merge this, pretty sure it's alright. I could have introduced a custom (private[netty]) exception to pass on the IllegalArgumentException, but not sure if that's really worth it.
