### PR TITLE
Fixes #6688 adds a includeDocumentation variable

### LINKED ISSUE #6688: Hardcoded dependency on (doc in Compile) breaks build
### Are you looking for help?

No

### Play Version (2.5.x / etc)

`2.5.9`

### API (Scala / Java / Neither / Both)

build

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

All systems

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

### Expected Behavior

A successful build when docs aren't able to built. We are using [simulacrum](https://github.com/mpilquist/simulacrum), which generates invalid scaladoc ATM.

1. Add invalid scaladoc (e.g. invalid reference to another class)
2. Configure scalac with `"-Xfatal-warnings"`
3. `sbt universal:packageBin`

### Actual Behavior

I want to disable [the hardcoded sources](https://github.com/playframework/playframework/blob/2.5.x/framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L219-L227). For example with
an extra AutoPlugin

```
disablePlugins(PlayIncludeDocumentation)
```

### Reproducible Test Case

Will provide a failing test

### PR DESCRIPTION
**Pull request by schmitch**
# Helpful things

## Fixes

Fixes #6688

## Purpose

Fixes #6688 adds a includeDocumentation variable to remove the java/scala-doc from the distribution

## Background Context

Actually to really stop it from generating the documentation would mean to actually set `packageDoc` to new `File(".")`, see https://github.com/playframework/playframework/pull/6723/files#diff-69b29e5ccdf04d73ef169d932b4e2dbcR20.

Another way would be creating a `AutoPlugin` to remove the `mappings` but even that can't remove the `packageDoc` call.

/cc @muuki88

### CODE REVIEW

File: framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala [hunk 1]
```diff
@@ -119,5 +119,7 @@ object PlayImport {
 
     val playMonitoredFiles = TaskKey[Seq[File]]("playMonitoredFiles")
     val fileWatchService = SettingKey[FileWatchService]("fileWatchService", "The watch service Play uses to watch for file changes")
+
+    val includeDocumentation = SettingKey[Boolean]("includeDocumentation", "Determines if a documentation should be generated on stage/dist tasks.")
```
Comment (gmethvin) [inline framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala]: `generateDocumentation`?

Comment (schmitch) [inline framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala]: well actually it still generate's the documentation via `packageDoc` so the includeDocumentation just doesn't add it, I guess the description here is wrong. it should probably be "includes the Documentation inside the distribution binary." WDYT?

**Comment by gmethvin** [comment]
Yeah, you're right, just update the comment like you said.

File: framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/test [hunk 2]
```diff
@@ -0,0 +1,6 @@
+# Build the distribution and ensure that there is no documentation
+> stage
+$ absent target/universal/stage/share
+
+# Build the documentation which should fail
```
Comment (muuki88) [inline framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/test]: This comment can be removed

File: framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala (hunk 1 above)
Comment (muuki88) [inline framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala]: The full name should be `includeDocumentationInBinary`. IMHO this is a bit clumsy. Generation is not correct for the reasons @schmitch mentioned.

File: framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala [hunk 3]
```diff
@@ -225,15 +227,24 @@ object PlaySettings {
...
     }.value,
 
-    mappings in Universal ++= {
-      val docDirectory = (doc in Compile).value
-      val docDirectoryLen = docDirectory.getCanonicalPath.length
-      val pathFinder = docDirectory ** "*"
-      pathFinder.get map {
-        docFile: File =>
-          docFile -> ("share/doc/api/" + docFile.getCanonicalPath.substring(docDirectoryLen))
+    mappings in Universal ++= Def.taskDyn {
```
Comment (muuki88) [inline framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala]: Ah :) Haven't played with the dynamic tasks that much. I'm fine with that.
