### PR TITLE
Fix Content-Disposition filename handling

### LINKED ISSUE #7501: Incorrect Filename when downloading from Play 2.6 application  Ask Question
### Incorrect downloaded filename

I downloaded [Play 2.6 Scala Starter Example](https://example.lightbend.com/v1/download/play-scala-starter-example) from [playframework.com](https://www.playframework.com/download#seeds).

Added route to `conf/routes`
```
GET     /readme                    controllers.AsyncController.readme
```
Added _Action_ to `app/controllers/AsyncController.scala`
```
  def readme = Action {
    Ok.sendFile(
      content = new java.io.File("README.md"),
      inline = false)
  }
```
When I try to `http://localhost:9000/readme`, I'm expecting file **README.md** to be downloaded, instead I get **utf-8"README.md".
[Related question on stackoverflow](https://stackoverflow.com/questions/44733090/incorrect-filename-when-downloading-from-play-2-6-application)

### Play Version (2.5.x / etc)

**2.6.0**

### API (Scala / Java / Neither / Both)

**Scala**

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

**Windows 10**

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```
### Library Dependencies

**None**

### Expected Behavior

Downloaded filename should be **README.md**.

### Actual Behavior

Downloaded filename is **utf-8"README.md**.

### Reproducible Test Case

### PR DESCRIPTION
**Pull request by richdougherty**
Fixes #7501.

1. Improve handling of extended characters in filenames, following the definition in RFC 5987.

   The previous rendering had a couple of problems. First, it rendered UTF-8 characters into the regular `filename` parameter. Second, its %-escaping of extended characters in the `filename*` parameter used the URI path-segement encoding, which doesn't escape all necessary characters.

   In addition, the new handling only renders an extended `filename*` parameter when there are special characters that need escaping.

   See:
   - https://github.com/playframework/playframework/pull/6042

2. Use a RawHeader with Akka HTTP to avoid the backend parsing and re-rendering the header. There's currently a bug with this that needs to be fixed before we can use a typed header.

   See:
   - https://github.com/akka/akka-http/issues/1240
   - https://github.com/akka/akka-http/issues/1066

Cc @jrudolph, @zhangshifeng.

### CODE REVIEW

**Comment by zhangshifeng** [comment]
LGTM. This also needs to be corrected for [StatusHeader.java](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L277) and [ResultsTest.java](https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/java/play/mvc/ResultsTest.java).

File: framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala [hunk 1]
```diff
@@ -20,6 +20,7 @@ import play.api.http.ContentTypes
 import play.api.http.HeaderNames._
 import play.api.http.HttpEntity
 import play.api.http.Status._
+import play.core.utils.HttpHeaderParameterEncoding
 import play.utils.UriEncoding
```
Comment (zhangshifeng) [inline framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala]: Maybe can remove unused import `StandardCharsets` and `UriEncoding`

File: framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala [hunk 2]
```diff
@@ -0,0 +1,168 @@
...
+      // the 'token' or 'quoted printable' encoding, however it's
+      // simpler to use the subset of characters that is also valid
+      // for extended attributes.
+      if (codePoint >= 0 && codePoint <= 255 && PartialQuotedText.get(codePoint)) {
+        builder.append(codePoint.toChar)
+      } else {
+        // Set flag because we need to render an extended parameter.
+        hasExtendedChars = true
+        // Render a placeholder instead of the unsupported character.
+        builder.append(PlaceholderChar)
```
Comment (zhangshifeng) [inline framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala]: I'm not sure `PlaceholderChar` is good if the browser does not support this feature.

File: framework/src/play/src/main/scala/play/api/mvc/Results.scala [hunk 3]
```diff
@@ -406,8 +406,11 @@ trait Results {
           status,
           Map(
             CONTENT_DISPOSITION -> {
-              val dispositionType = if (inline) "inline" else "attachment"
-              s"""$dispositionType; filename="$name"; filename*=utf-8''${UriEncoding.encodePathSegment(name, StandardCharsets.UTF_8)}"""
```
Comment (zhangshifeng) [inline framework/src/play/src/main/scala/play/api/mvc/Results.scala]: Why not `HttpHeaderParameterEncoding.encode` in here

Comment (richdougherty) [inline framework/src/play/src/main/scala/play/api/mvc/Results.scala]: Just a slight efficiency improvement…

File: framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala (hunk 2 above)
Comment (richdougherty) [inline framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala]: Do mean that we should render the UTF-8 characters into the `filename` parameter in case browsers don't support the `filename*` parameter?

I decided not to render UTF-8 characters into the `filename` parameter because it didn't seem like it would work reliably.

The `filename` parameter is a [_quoted-string_](https://tools.ietf.org/html/rfc2616#section-2.2) which means it can contain any bytes except control characters and `"`. The encoding of these bytes is ISO-8859-1, not UTF-8. There's provision for escaping with `\` and for changing the character set with RFC 2047's `"=?" charset "?" encoding "?" encoded-text "?="` format, however I doubt that format is widely supported by browsers, so I don't think we can safely use UTF-8 encoding in the `filename` field.

[IE7/IE8 seem to accept a URL-encoded string in the `filename` parameter](https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http/6745788#6745788). However I think they are the only browsers that have this behaviour, so I don't think we can use this format.

Instead I've opted for the `filename` _quoted-string_ parameter to use a "safe" subset of 7-bit ASCII. Modern browsers should ignore the `filename` parameter anyway and pick up the real filename from the `filename*` parameter. Incompatible/old browsers should at least work, even if they have placeholders in the filename.

I realise this might not be that great if you _do_ have an older or incompatible browser and you have a lot of filenames in UTF-8 but not US-ASCII. Do you have a suggestion for alternative behaviour that would work properly across browsers?

Comment (richdougherty) [inline framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala]: > There's provision for escaping with \ and for changing the character set with RFC 2047's "=?" charset "?" encoding "?" encoded-text "?=" format, however I doubt that format is widely supported by browsers, so I don't think we can safely use UTF-8 encoding in the filename field.

Maybe this encoding is actually supported after all? But since that encoding doesn't seem to be supported in IE it probably isn't any better than `filename*` anyway.

https://stackoverflow.com/questions/22319277/how-to-set-chinese-filename-correctly-for-different-browsers-when-download-file/22324744#22324744

Comment (richdougherty) [inline framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala]: See also a JavaScript implementation of this. They put ISO-8859-1 chars into the `filename` parameter, but UTF-8 chars are replaced with a `?` placeholder.

https://github.com/jshttp/content-disposition/blob/master/test/test.js#L57-L62

**Comment by jrudolph** [comment]
In any way, we need to also need to fix the `Content-Disposition` behavior in akka-http. Wouldn't it make sense to have only one implementation that works as desired? Or do you need the rendering also for the netty backend?

**Comment by richdougherty** [comment]
@jrudolph, I'd say we need to support both Netty and Akka HTTP for Play 2.6.x. The best outcome for us would be if Akka HTTP supports RFC 5987 headers itself (https://github.com/akka/akka-http/issues/1066) and also exposes a `parse`/`render` SPI so that we can do it ourselves for Netty.

File: framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala (hunk 2 above)
Comment (zhangshifeng) [inline framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala]: I do not have a good idea.

**Comment by richdougherty** [comment]
@jrudolph We'd like to do a Play 2.6.1 release fairly soon (mid-next week?) so I'd like to work out how to handle this issue.

I propose we do an interim fix now using this PR, then change to an Akka HTTP-based SPI later once Akka HTTP implements https://github.com/akka/akka-http/issues/1066. It should be OK for Play users if we change implementation later, because the implementation is private to Play; it's not a public API. That means we can change the underlying implementation whenever/however we want.

On the other hand, if you feel you can have something ready fairly soon then it would probably just make sense to use an Akka HTTP implementation right from the start.

Thoughts?

File: framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala [hunk 4]
```diff
@@ -0,0 +1,172 @@
...
+package play.core.utils
+
+import java.lang.{ StringBuilder => JStringBuilder }
+import java.util.function.IntConsumer
+import java.util.{ BitSet => JBitSet }
+
+/**
+ * Support for rending HTTP header parameters according to RFC5987.
+ */
+private[play] object HttpHeaderParameterEncoding {
```
Comment (ktoso) [inline framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala]: hm this fix we'll want to port as soon as possible, or perhaps could you help us out with that - by doing a PR to Akka HTTP?

Comment (richdougherty) [inline framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala]: I'd be happy to do a PR but will be stretched to do it pre-2.6.1 because there are other issues we want to get fixed. I'm sure you're busy too, so I think it's probably pragmatic to get the fix into Akka HTTP a bit later.

The work in Akka HTTP will be a bit more involved because:
- need to consider parsing as well as rendering (this Play PR is only rendering)
- may want to discuss design decisions, like whether to allow more ISO-8859-1 in regular parameters, or just use a subset like we're doing here
- need to consider how users of Akka's API actually express char encoded Strings issues in header parameters, e.g. what happens when users set the `filename` parameter a UTF-8 value (which is invalid)—do we convert it to a valid quoted string then render an extended parameter? Or does there need to be an explicit API for expressing encoded parameters? (I don't know if there's an existing Akka HTTP API for setting charset-encoded strings into headers?)

Not sure where that leaves this issue, but maybe you, me, @jrudolph  and @gmethvin can have a chat early next week to figure out a good way to collaborate and manage the workflow between Play and Akka HTTP?
