### PR TITLE
Leave other set cookies alone when cleaning up flash

### LINKED ISSUE #4753: Cleanup of FLASH cookie prevents other cookies from being set (e.g., CSRF token)
*Description*
Cleanup of FLASH cookie prevents other cookies from being set (e.g., CSRF token)

*How to Reproduce*
1. Run sample app: https://github.com/seantbrady/play-flash-sample
2. Go to http://localhost:9000/ and observe HELLO cookie is set
3. Clear cookies
4. Go to http://localhost:9000/setflash which sets a flash cookie and redirects to http://localhost:9000/
5. Observe HELLO cookie is NOT set when it should be

### PR DESCRIPTION
**Pull request by jroper**
Fixes #4753

### CODE REVIEW

File: framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala [hunk 1]
```diff
@@ -267,7 +267,7 @@ object ServerResultUtils {
       } else {
         // We got incoming flash cookies, but there are no outgoing flash cookies,
         // so we need to clear the cookies for the next request
-        result.withHeaders(SET_COOKIE -> Cookies.encodeSetCookieHeader(Seq(Flash.discard.toCookie)))
```
Comment (richdougherty) [inline framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala]: Oops.

**Comment by richdougherty** [comment]
LGTM

**Comment by jroper** [comment]
Backported to 2.4.x: e3f2755
