### PR TITLE
Routes compiler: Remove generation date, keep the source relative

### LINKED ISSUE #10490: Does not work sbt 1.4 remote cache feature
### Play Version

2.8.2

### API

Maybe both(Java and Scala)

### Operating System

Mac and Linux (also maybe Windows)

### JDK

1.8

### Library Dependencies

unrelated

### Expected Behavior

it should work sbt 1.4 remote cache feature

### Actual Behavior

recompile even if there is cache

### Reproducible Test Case

- https://github.com/xuwei-k/sbt-remote-cache-playframework/commit/0cc2569f46e50bb0c8dab7c9648a667bc5389116
- https://github.com/xuwei-k/sbt-remote-cache-playframework/runs/1279043026

#### step and log

```
$ sbt pushRemoteCache
```

```
$ sbt clean pullRemoteCache compile
[info] welcome to sbt 1.4.1 (AdoptOpenJDK Java 1.8.0_265)
[info] loading settings for project sbt-remote-cache-playframework-build from plugins.sbt ...
[info] loading project definition from /home/runner/work/sbt-remote-cache-playframework/sbt-remote-cache-playframework/project
[info] loading settings for project sbt-remote-cache-playframework from build.sbt ...
[info] set current project to sbt-remote-cache-playframework (in build file:/home/runner/work/sbt-remote-cache-playframework/sbt-remote-cache-playframework/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed Oct 20, 2020 5:01:29 AM
[info] remote cache artifact extracted for Some(cached-compile)
[info] remote cache artifact extracted for Some(cached-test)
[success] Total time: 1 s, completed Oct 20, 2020 5:01:30 AM
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] compiling 5 Scala sources and 1 Java source to /home/runner/work/sbt-remote-cache-playframework/sbt-remote-cache-playframework/target/scala-2.13/classes ...
[info] done compiling
[success] Total time: 9 s, completed Oct 20, 2020 5:01:39 AM
```

#### `app/controllers/Application.scala`

```scala
package controllers

import play.api.mvc._
import javax.inject.Inject

class Application @Inject()(cc: ControllerComponents) extends AbstractController(cc) {

  def index = Action {
    Ok("hello")
  }

}
```

#### `build.sbt`

```scala
scalaVersion := "2.13.3"

libraryDependencies +=  guice

enablePlugins(PlayScala)

pushRemoteCacheTo := Some(
  MavenCache("local-cache", (ThisBuild / baseDirectory).value / "remote-cache")
)

remoteCacheId := "fixed-id"

remoteCacheIdCandidates := Seq(remoteCacheId.value)

pushRemoteCacheConfiguration := pushRemoteCacheConfiguration.value.withOverwrite(true)
```

#### `conf/routes`

```
GET     /                           controllers.Application.index
```

#### `project/build.properties`

```
sbt.version=1.4.1
```

#### `project/plugins.sbt`

```scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.2")
```

### Note

playframework routes generator embed current `DATE` in generated source comments.
I think it is the cause this issue 🤔 

- https://github.com/playframework/playframework/blob/a90ab0f0d027bfc81671c329f7e30eb20f7a4cd8/dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/routesPrefix.scala.twirl#L3-L6
- https://github.com/playframework/playframework/blob/a90ab0f0d027bfc81671c329f7e30eb20f7a4cd8/dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala#L55-L56

```
$  git grep @DATE
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl:// @@DATE:@sourceInfo.date
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/javaWrappers.scala.twirl:// @@DATE:@sourceInfo.date
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/javascriptReverseRouter.scala.twirl:// @@DATE:@sourceInfo.date
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/reverseRouter.scala.twirl:// @@DATE:@sourceInfo.date
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/routesPrefix.scala.twirl:// @@DATE:@sourceInfo.date
```

#### `cat target/scala-2.13/routes/main/router/RoutesPrefix.scala`

different **`@DATE`** comment 😢 

##### after first compile

```
// @GENERATOR:play-routes-compiler
// @SOURCE:/home/runner/work/sbt-remote-cache-playframework/sbt-remote-cache-playframework/conf/routes
// @DATE:Tue Oct 20 05:01:03 UTC 2020
```

##### after second compile
(I want to use remote cache but play re-generate different source 😢 )

```
// @GENERATOR:play-routes-compiler
// @SOURCE:/home/runner/work/sbt-remote-cache-playframework/sbt-remote-cache-playframework/conf/routes
// @DATE:Tue Oct 20 05:01:31 UTC 2020
```

Is this a sbt bug or playframework bug? /cc @eed3si9n 
playframework should not embed `@DATE` comment? 🤔

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #10490

Necessary to make a build reproducible and for sbt's 1.4 remote cache feature.

Date was never used.
Source is used only here:
https://github.com/playframework/playframework/blob/202ca0a18dc3e6555eb0ebc73afdc7c2b10480b2/dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala#L58-L59

Comments generated before this patch:
```
// @GENERATOR:play-routes-compiler
// @SOURCE:/home/mkurz/play-test-project/conf/routes
// @DATE:Tue Feb 16 18:47:10 CET 2021
```
With this patch:
```
// @GENERATOR:play-routes-compiler
// @SOURCE:conf/routes
```

Did manual testing, works great (means the error page get's shown highlighting an invalid line in the routes file if there is one)

### CODE REVIEW

File: dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala [hunk 1]
```diff
@@ -53,7 +53,10 @@ object InjectedRoutesGenerator extends RoutesGenerator {
     val folder = namespace.map(_.replace('.', '/') + "/").getOrElse("") + "/"
 
     val sourceInfo =
-      RoutesSourceInfo(task.file.getCanonicalPath.replace(File.separator, "/"), new java.util.Date().toString)
+      RoutesSourceInfo(
+        new File(".").toURI.relativize(task.file.toURI).getPath.replace(File.separator, "/"),
```
Comment (mkurz) [inline dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala:57]: Stolen from https://github.com/playframework/twirl/pull/378/files#diff-81dc011c212aa694b5dc7fc54c688e76d1e0304e8252723848b9b1dc2e693d99R229

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Review by octonato — APPROVED** [review]
LGTM
