### PR TITLE
Fix repeated content type headers in WS on POST

### LINKED ISSUE #4681: Repeated content type headers in WS on POST
From https://groups.google.com/d/topic/play-framework/mF-Rqh_ljEA/discussion

wenn I do that:

```scala
WS.url(url)
     .withHeaders("x-api-version" -> "1.0")
     .withRequestTimeout(2000)
     .post(authData)
     .map { response =>
     response.status match {
       case s if s < 300 =>
         Ok(response.json)
       case _ =>
         Ok("Status: " + response.status + "/ Error: " + response.body)
     }
   }
```

I see this request:

```
Request DefaultHttpRequest(chunked: false)
POST /api/login/ HTTP/1.1
Host: 62.67.13.54
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Accept: */*
User-Agent: HbbTVPlugin
Content-Length: 37
```

The the target system has a problem processing `"charset=utf-8"`, so I tried his:

```scala
WS.url(url)
     .withHeaders("x-api-version" -> "1.0")
     .withHeaders(CONTENT_TYPE -> "application/json")
     .withRequestTimeout(2000)
     .post(authData)
     .map { response =>
     response.status match {
       case s if s < 300 =>
         Ok(response.json)
       case _ =>
         Ok("Status: " + response.status + "/ Error: " + response.body)
     }
   }
```

and I get this request:

```
Request DefaultHttpRequest(chunked: false)
POST /api/login/ HTTP/1.1
Host: 62.67.13.54
Content-Type: application/json
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Accept: */*
User-Agent: HbbTVPlugin
Content-Length: 37
```

I did not expect to get the same header key (`Content-Type`) twice?

What can I do to change the content type, without getting two content-type header?

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #4681

### CODE REVIEW

File: framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala [hunk 1]
```diff
@@ -113,14 +113,12 @@ object AhcWSSpec extends PlaySpecification with Mockito {
...
-      //        .withHeaders("Content-Type" -> "text/plain").withBody(<aaa>value1</aaa>).asInstanceOf[AhcWSRequest]
-      //        .buildRequest()
-      //      req.getHeaders.get("Content-Type").asScala must containTheSameElementsAs(Seq("text/plain"))
-      pending("disabled until discussion about charset handling")
+      import scala.collection.JavaConverters._
+      val req: AHCRequest = WS.url("http://playframework.com/")
+        .withHeaders("Content-Type" -> "text/plain").withBody(<aaa>value1</aaa>).asInstanceOf[AhcWSRequest]
+        .buildRequest()
+      req.getHeaders.get("Content-Type").asScala must containTheSameElementsAs(Seq("text/plain; charset=utf-8"))
     }
```
Comment (mkurz) [inline framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala]: I did enable this again because this is how it actually behaves right now (even before this PR when using Java WS - I did not introduce this behaviour).
@wsargent @jroper Is this OK?

**Comment by wsargent** [comment]
Failed on a couple of tests

```
[error]   x Only send first content type header and add charset=utf-8 to the Content-Type header if it's manually adding but lacking charset
[error]    Buffer(application/json, application/xml)
[error]      is missing: application/json; charset=utf-8
[error]      must not contain: application/json, application/xml (AhcWSRequestSpec.scala:46)
[error]   x Only send first content type header and keep the charset if it has been set manually with a charset
[error]    Buffer(application/json; charset=US-ASCII, application/xml)
[error]      must not contain: application/xml (AhcWSRequestSpec.scala:56)
```

**Comment by mkurz** [comment]
Strange, the tests passed on my machine.

**Comment by mkurz** [comment]
I will check tomorrow.

**Comment by mkurz** [comment]
Build is green now good to go now.

File: framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala (hunk 1 above)
Comment (wsargent) [inline framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala]: IIRC, that note's in there because at one point the charset handling was inconsistent between Scala WS and Java WS.

https://github.com/playframework/playframework/blob/master/framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java#L442

vs 

https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala#L262

need to review and see that they're the same logic...

Comment (mkurz) [inline framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala]: I know this was different before. Actually this pull request here makes Scala WS and Java WS behave the same now.
Before only Java WS [always added a charset](https://github.com/playframework/playframework/blob/master/framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java#L443-L448) to the content-type header if it wasn't present already, but Scala WS did not ([the lines](https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala#L265-L266) were commented out).
If you look at `AhcWS.scala` of my PR you will see that also the Scala WS now always adds a charset to the content-type header if if isn't present.

Comment (wsargent) [inline framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala]: Great!

**Comment by wsargent** [comment]
LGTM

**Comment by mkurz** [comment]
@wsargent Could you also review #5478?
