### PR TITLE
Fix iterator for Cookies created via play.api.test.Helpers.cookies

### LINKED ISSUE #13271: play.api.test.Helpers.cookies drops duplicate-named cookies when iterated (except in foreach)
Possible Issue in `play.api.test.Helpers.cookies`: Inconsistent Iteration with Duplicate Cookie Names

```scala
import play.api.mvc._
import play.api.test.Helpers._
import scala.concurrent._

val ckies = Seq(Cookie(name = "a", value = "1"), Cookie(name = "a", value = "2"))
```

There’s no problem creating a `Cookies` object with duplicate cookie names:

```scala
play.api.mvc.Cookies(ckies).toSeq
// Result: List(Cookie(a,1,...), Cookie(a,2,...))
```

However, when using `play.api.test.Helpers.cookies` with a result, elements seem to be dropped during iteration—except when using `foreach`:

```scala
val result = Future.successful(Results.NoContent.withCookies(ckies: _*))

play.api.test.Helpers.cookies(result).toSeq
// Result: List(Cookie(a,1,...))  // Cookie "a" with value "2" is missing

play.api.test.Helpers.cookies(result).foreach(c => println(c.name, c.value))
// Output:
// (a,1)
// (a,2)
```

This seems to be caused by the fact that the `iterator` method in [`Helpers.cookies`](https://github.com/playframework/playframework/blob/3.0.x/testkit/play-test/src/main/scala/play/api/test/Helpers.scala#L537) uses `cookiesByName`, which only keeps one cookie per name.

Should this be changed to return `cookies.iterator`, like `play.api.mvc.Cookies.apply` does?
If keeping `cookiesByName` is intentional, perhaps it should return the *.last* value instead of the *.head*, since browsers usually respect the last `Set-Cookie` header when duplicate names are sent.

---

additional info:
It can be reproduced with Scala2.13 or higher
```scala
// play2.8.22 with Scala2.12
scala> play.api.test.Helpers.cookies(result).size
res1: Int = 2

// play2.8.22 with Scala2.13
scala> play.api.test.Helpers.cookies(result).size
res1: Int = 1
```

### PR DESCRIPTION
**Pull request by murosan**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #13271

## Purpose

Fix iterator for Cookies created via `play.api.test.Helpers.cookies`.

## Background Context

- Cookies.iterator: https://github.com/playframework/playframework/blob/3.0.x/core/play/src/main/scala/play/api/mvc/Cookie.scala#L206

### CODE REVIEW

File: testkit/play-test/src/main/scala/play/api/test/Helpers.scala [hunk 1]
```diff
@@ -530,11 +530,14 @@ trait ResultExtractors {
       of.map { result =>
         val cookies = result.newCookies
         new Cookies {
-          lazy val cookiesByName: Map[String, Cookie]    = cookies.groupBy(_.name).view.mapValues(_.head).toMap
+          // Takes the last value, since browsers usually respect
+          // the last Set-Cookie header when duplicate names are sent.
+          lazy val cookiesByName: Map[String, Cookie] = cookies.groupBy(_.name).view.mapValues(_.last).toMap
```
Comment (mkurz) [inline testkit/play-test/src/main/scala/play/api/test/Helpers.scala:535]: Wait a moment....
we do use `_.head` here: https://github.com/playframework/playframework/blob/3.0.7/core/play/src/main/scala/play/api/mvc/Cookie.scala#L200

So either our code there is wrong or in this PR it's a mistake...

Comment (murosan) [reply testkit/play-test/src/main/scala/play/api/test/Helpers.scala:535]: I went with `.last` since the cookies in `Result` are what get sent to the client, so it felt more accurate for the test.
But if a change to `play.api.mvc.Cookies.apply` is needed, it would have a broader impact, so it's probably better not to make that change in this PR. I'll switch it back to `.head`.
 Thanks!

**Review by mkurz — APPROVED** [review]
I pushed a commit to change back to `_.head` - specially because I will backport the PR to 3.0.x/2.9.x.

If you want you can open another PR where we change _all_ the behaviour to `_.last` - but this one I will not backport to not break compatibility for the stable branches.

**Comment by mkurz** [comment]
@Mergifyio backport 2.9.x 3.0.x

**Comment by murosan** [comment]
Thanks a lot!
