### PR TITLE
Fix missed ContextInitializer#configureByResource

### LINKED ISSUE #11907: logback-classic 1.4.9 contains breaking change that breaks Play
logback-classic 1.4.9 removed a public method from their API that's used by Play. I haven't looked more closely, but I suspect this version would break any Play app that uses Logback? This is the stacktrace I get from our integration tests:

```
[error] java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:125)
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:73)
[error] 	at play.api.inject.guice.GuiceApplicationBuilder.$anonfun$configureLoggerFactory$1(GuiceApplicationBuilder.scala:137)
[error] 	at scala.Option.map(Option.scala:242)
[error] 	at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:136)
[error] 	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:112)
[error] 	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
[error] 	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
[...stacktrace continues]
```

To be clear: this sucks, and IMO they shouldn't do this. But apparently [their guidance on this is "just copy the method into your own code"](https://mailman.qos.ch/pipermail/logback-user/2023-August/005284.html). This is the commit that removed the method: https://github.com/qos-ch/logback/commit/4b06e062488e4cb87f22be6ae96e4d7d6350ed6b Presumably this is the newest version of this code.

### Play Version
2.8.19, but likely older as well

### API
Scala, but probably either

### Operating System
Linux, but probably all OS

### JDK
JDK 11 ("Amazon.com Inc. Java 11.0.18"), but probably others as well

### Library Dependencies
ch.qos.logback:logback-classic 1.4.9

### Expected Behavior
Play doesn't crash on startup and logback logging works.

### Actual Behavior
Play crashes on startup. This is the stacktrace when actually running the application:
```
VM settings:
    Max. Heap Size (Estimated): 10.67G
    Using VM: OpenJDK 64-Bit Server VM

Oops, cannot start the server.
java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:125)
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:73)
	at play.api.inject.guice.GuiceApplicationBuilder.$anonfun$configureLoggerFactory$1(GuiceApplicationBuilder.scala:137)
	at scala.Option.map(Option.scala:242)
	at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:136)
	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:112)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:53)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

### PR DESCRIPTION
**Pull request by tsuyoshizawa**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [ ] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #11907

## Purpose

Library users can update their Logback libraries to the latest version by porting ContextInitializer#configureByResource, which was removed in Logback 1.4.9 and 1.3.9.

## Background Context

As noted in the referenced issue, this is due to the fact that Logback has removed the deprecated method.

## References

Nothing

### CODE REVIEW

**Comment by mkurz** [comment]
Hi @tsuyoshizawa, you need to rebase, there is already a conflict, probably because I just merge some pull requests from scala-steward that upgrade dependencies. Thanks!!!

**Comment by tsuyoshizawa** [comment]
@mkurz Thank you for the point. I had been satisfied with syncing with GitHub's Sync fork 😂
I rebased and re-pushed.

**Comment by mkurz** [comment]
@tsuyoshizawa 
```
[warn] scalafmt: /home/runner/work/playframework/playframework/core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala isn't formatted properly!
```
please run `scalafmt`, thanks!

**Comment by tsuyoshizawa** [comment]
@mkurz Oh, sorry. Formatted!

File: core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala [hunk 1]
```diff
@@ -132,6 +133,21 @@ class LogbackLoggerConfigurator extends LoggerConfigurator {
...
+    val urlString = url.toString
+    if (urlString.endsWith("xml")) {
+      val configurator = new JoranConfigurator()
+      configurator.setContext(ctx)
+      configurator.doConfigure(url)
+    } else {
+      throw new LogbackException("Unexpected filename extension of file [" + url + "]. Should be .xml")
+    }
+  }
+
```
Comment (mkurz) [inline core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala:150]: I think instead of duplicating code here it might be better to use the `configureByResource` method provided by `DefaultJoranConfigurator`, see [here](https://github.com/qos-ch/logback/blob/v_1.4.11/logback-classic/src/main/java/ch/qos/logback/classic/util/DefaultJoranConfigurator.java#L60-L73).

However I want to wait what the logback maintainers say before:
* https://mailman.qos.ch/pipermail/logback-user/2023-August/005290.html
* https://github.com/qos-ch/logback/pull/697

I already updated my `fix-missed-configureByResource` branch and pushed my suggestion https://github.com/mkurz/playframework/commit/8fb181718394faadad2cde0a50a9d4e3629d91b4

After we hear back from logback I just might fast forward this PR to my patch and merge.

Comment (mkurz) [reply core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala]: My suggestion got accepted from the logback maintainer, so I pushed to this PR as well and will merge.

**Review by mkurz — APPROVED** [review]

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x
