### PR TITLE
Set correct Locale in Databinder

### LINKED ISSUE #2065: Passed locale in custom formatter is wrong
[Play 2.2.1]
I'd like to configure my own DateFormatter to parse and print the date based on my current user's locale. (gregorian for 'en' and jalali for 'fa' users)
I extend SimpleFormatter and everything is fine. But I have a problem, I think the passed locale in my custom formatter is wrong, it always passes me "en" locale that is default and resolved by the header request. In my project I changed the user's locale (by calling changeLang method in controller) and it is set in the user's cookie.
The bigger problem is in printing error messages. When I throw an exception in the case of an invalid date string, it prints the 'en' message whilst other parts of page are being rendered in 'fa'.

I think there exists some kind of bug on play.

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #2065 

Now the `locale` param is set correctly for both the `parse` and `print` method.

### CODE REVIEW

File: framework/src/play-java/src/main/java/play/data/Form.java [hunk 1]
```diff
@@ -351,7 +352,16 @@ protected String getMessageForConstraintViolation(ConstraintViolation<Object> vi
         dataBinder.setValidator(validator);
         dataBinder.setConversionService(play.data.format.Formatters.conversion);
         dataBinder.setAutoGrowNestedPaths(true);
-        dataBinder.bind(new MutablePropertyValues(objectData));
+        try {
```
Comment (marcospereira) [inline framework/src/play-java/src/main/java/play/data/Form.java]: Maybe this `try-catch` can be extracted to a small method, since the same code appears again below.

**Comment by wsargent** [comment]
@mkurz any tests for this?

**Comment by marcospereira** [comment]
+1 for tests here. Also, a small doubt: is this behavior consistent with the scala form api?

**Comment by mkurz** [comment]
Done. I added tests and put the code into a method.

@marcospereira Scala API works different, there is no need to change something. Look at the [docs](https://www.playframework.com/documentation/2.4.x/ScalaForms#Defining-constraints-on-the-form) and [Format.scala](https://github.com/playframework/playframework/blob/2.5.0-M2/framework/src/play/src/main/scala/play/api/data/format/Format.scala#L189-L206). Scala API does not use spring Binder functionality.

Please review again, thanks!

File: framework/src/play-java/src/test/java/play/data/Formats.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+         *
+         * @param annotation the annotation that trigerred this formatter
+         * @param value the value to unbind
+         * @param locale the current <code>Locale</code>
+         * @return printable version of the value
+         */
+        @Override
+        public String print(final Currency annotation, final BigDecimal value, final Locale locale) {
+            if(value == null) {
+                return "";
```
Comment (marcospereira) [inline framework/src/play-java/src/test/java/play/data/Formats.java]: Should we use `java.util.Optional`s here instead of returning an empty `String`?

File: framework/src/play-java/src/test/java/play/data/Formats.java [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+        /**
+         * Unbinds this field - converts a concrete value to plain string
+         *
+         * @param annotation the annotation that trigerred this formatter
+         * @param value the value to unbind
+         * @param locale the current <code>Locale</code>
+         * @return printable version of the value
+         */
+        @Override
+        public String print(final Currency annotation, final BigDecimal value, final Locale locale) {
```
Comment (marcospereira) [inline framework/src/play-java/src/test/java/play/data/Formats.java]: `format` looks like a better name to me.

Comment (marcospereira) [inline framework/src/play-java/src/test/java/play/data/Formats.java]: Forget it! I just saw this name comes from `Formatters.AnnotationFormatter`.

File: framework/src/play-java/src/test/java/play/data/Formats.java (hunk 2 above)
Comment (marcospereira) [inline framework/src/play-java/src/test/java/play/data/Formats.java]: Forget it! I just saw that the method signature comes from `Formatters.AnnotationFormatter`.

**Comment by marcospereira** [comment]
LGTM.
