### PR TITLE
Prevent TemporaryFile to be deleted before returning a response

### LINKED ISSUE #12770: Temporary file is deleted before a controller returns a response
### Play Version

3.0.4

### API

Scala

### Operating System

macOS 14.4.1

### JDK

```
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-21.0.2.13.1 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (build 21.0.2+13-LTS, mixed mode, sharing)
```

### Library Dependencies

None

### Expected Behavior

I have prepared the following Controller method.

```scala
  def fileSize() =
    Action.async(parse.multipartFormData) { implicit request =>
      request.body.file("file") match {
        case Some(image) =>
          for {
            path <- Future(image.ref.path)
            _ <- Future(System.gc())
            _ <- Future(Thread.sleep(100))
          } yield Ok(Files.size(path).toString)
        case None =>
          Future.successful(BadRequest("No image supplied"))
      }
    }
```

The endpoint is as follows.

```
POST    /fileSize                   controllers.HomeController.fileSize()
```

1. Send a POST request.
    - `echo -n Hello > /tmp/a; curl -X POST http://localhost:9000/fileSize -F"file=@/tmp/a"`
2. The server returns the file size and the command displays 5.

### Actual Behavior

1. Send a POST request.
    - `echo -n Hello > /tmp/a; curl -X POST http://localhost:9000/fileSize -F"file=@/tmp/a"`
2. The server returns an error page.
3. The server logs following

```
2024-06-18 18:25:01 ERROR p.api.http.DefaultHttpErrorHandler  

! @85ph4o99f - Internal server error, for (POST) [/fileSize] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NoSuchFileException: /var/folders/r2/qjlxkmsn49v6mtmb6dgs3xrc0000gr/T/playtemp8649900777384842915/multipartBody4548848415921731547asTemporaryFile]]
	at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$2(HttpErrorHandler.scala:400)
	at scala.Option.map(Option.scala:242)
	at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:398)
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:390)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
	at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:482)
	at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:474)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
	at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
	at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.nio.file.NoSuchFileException: /var/folders/r2/qjlxkmsn49v6mtmb6dgs3xrc0000gr/T/playtemp8649900777384842915/multipartBody4548848415921731547asTemporaryFile
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1853)
	at java.base/java.nio.file.Files.size(Files.java:2462)
	at controllers.HomeController.$anonfun$fileSize$7(HomeController.scala:36)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	... 5 common frames omitted
```

The file pointed to by TemporaryFile seems to be erased during GC, but I suppose that it would not be GC'd until it returns a response.

### Reproducible Test Case

https://github.com/tkawachi/play-tmpfile-deleted/commit/c9dbcd7c00863afc5b2f070cdc7fe9ceabe85dda

### PR DESCRIPTION
**Pull request by tkawachi**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #12770

## Purpose

If the Path of a temporary file is retrieved and processed, the TemporaryFile may be deleted before the response is finished (#12770). This pull request will prevent TemporaryFile from being deleted until the response is finished.

cc/ @mkurz

### CODE REVIEW

**Comment by tkawachi** [comment]
I am not familiar with the test structure of this project, so can you please guide me on where it would be appropriate to add tests in this case. @mkurz

**Comment by tkawachi** [comment]
I wrote a test. I confirmed locally that the test fails without a change I made.

**Comment by mkurz** [comment]
Thanks, I will take a look in the coming days.

File: core/play/src/main/scala/play/api/mvc/Action.scala [hunk 1]
```diff
@@ -432,6 +432,12 @@ trait ActionBuilder[+R[_], B] extends ActionFunction[Request, R] {
       def apply(request: Request[A]) =
         try {
           invokeBlock(request, block)
+            .andThen { _ =>
+              // This andThen block is used to keep a reference to the request until invokeBlock() is completed.
+              // If the request contains TemporaryFiles, it will be deleted when it's garbage collected.
```
Comment (mkurz) [inline core/play/src/main/scala/play/api/mvc/Action.scala:437]:
```suggestion
              // If the request contains TemporaryFiles, they will be deleted when they are garbage collected.
```

File: core/play/src/main/scala/play/api/mvc/Action.scala [hunk 2]
```diff
@@ -432,6 +432,12 @@ trait ActionBuilder[+R[_], B] extends ActionFunction[Request, R] {
...
+              // By keeping a reference to the request, it prevents the TemporaryFile from becoming a GC target.
```
Comment (mkurz) [inline core/play/src/main/scala/play/api/mvc/Action.scala:438]:
```suggestion
              // By keeping a reference to the request, it prevents the TemporaryFiles from becoming GC targets.
```

File: core/play/src/main/scala/play/api/mvc/Action.scala [hunk 3]
```diff
@@ -432,6 +432,12 @@ trait ActionBuilder[+R[_], B] extends ActionFunction[Request, R] {
       def apply(request: Request[A]) =
         try {
           invokeBlock(request, block)
+            .andThen { _ =>
+              // This andThen block is used to keep a reference to the request until invokeBlock() is completed.
+              // If the request contains TemporaryFiles, they will be deleted when they are garbage collected.
+              // By keeping a reference to the request, it prevents the TemporaryFiles from becoming GC targets.
+              request
+            }(self.executionContext)
```
Comment (mkurz) [inline core/play/src/main/scala/play/api/mvc/Action.scala:440]: We can use trampoline here to avoid thread switching, because the code that get's executed is a total no-op.
```suggestion
            }(Execution.trampoline)
```

**Review by mkurz — APPROVED** [review]
Thank you very much @tkawachi - this is a very nice improvement. I guess this will prevent people from running into random exceptions that are hard to figure out if you are not really familiar with the internals of how things work.
During review, it dawned on me that this will only fix the Scala API, but the Java API will have the same problem. Therefore, I added a test for Java actions as well and applied the same fix you did. Now, it's working for both APIs. I also tested locally and can confirm that both tests fail without the fix applied.

This will be backported for the next patch releases as well.
Thanks!

**Comment by mkurz** [comment]
@Mergifyio backport main 2.9.x
