### PR TITLE
Catch Throwable instead of NonFatal when starting prod server

### LINKED ISSUE #10681: UnsatisfiedLinkError in loader.load should stop the server
### Operating System: Ubuntu 20.04

Linux ip-xyz 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:56:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

### Expected Behavior

1. ProdServerStart.start() calls loader.load(context)  
2. loader.load(context) throws an UnsatisfiedLinkError
3. **The java process exits**

### Actual Behavior

1. ProdServerStart.start() calls loader.load(context)  
2. loader.load(context) throws an UnsatisfiedLinkError
3. **The java process continues running but does not respond to HTTP requests**

### Reproducible Test Case

Create a play app with this custom application loader: 
```scala
package misc
class MyApplicationLoader extends ApplicationLoader {
  def load(context: Context): Application = {
    throw new UnsatisfiedLinkError("Test")
  }
}
```
In `application.conf` add
```
play.application.loader = misc.MyApplicationLoader
```

### Fix

1. [The pidfile should be cleaned](https://github.com/playframework/playframework/blob/master/transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala#L87) for both Exceptions and Errors, so should be `case e: Throwable`, not `case NonFatal(e):`
2. [`process.exit()`](https://github.com/playframework/playframework/blob/master/transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala#L92) should be called for both Exceptions and Errors, so should also be `case e: Throwable`, not `case NonFatal(e):`

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #10681

### CODE REVIEW

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Comment by jxtps** [comment]
Looks good to me, thanks!

File: transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala [hunk 1]
```diff
@@ -82,14 +81,14 @@ object ProdServerStart {
 
         server
       } catch {
-        case NonFatal(e) =>
+        case e: Throwable =>
```
Comment (gmethvin) [inline transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala:84]: I think this change is fine, but I'm wondering if this `catch` block should look like:
```scala
  case e: Throwable =>
    try {
      pidFile.foreach(_.delete())
    } finally {
      throw e // ignore any exception thrown by `delete`
    }
```

**Review by gmethvin — APPROVED** [review]
