### PR TITLE
Fixes #7659:  The session module doesn't work after LegacyCookiesModule is enabled.

### LINKED ISSUE #7659: The session module doesn't work after LegacyCookiesModule is enabled.
### Play Version 
2.6.2

### API
Scala

### Operating System 
Windows 10

### JDK 
Oracle 1.8.0_72
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
Paste the output from `java -version` at the command line.

### Expected Behavior
The session module works normally after LegacyCookiesModule is enabled.

### Actual Behavior
After LegacyCookiesModule is enabled, the session cookies of results are encoded by CookiesModule, but not LegacyCookiesModule.

### Reproducible Test Case
This issue occurs after LegacyCookiesModule is enabled in application.conf.
```
play.modules.disabled += "play.api.mvc.CookiesModule"
play.modules.enabled += "play.api.mvc.LegacyCookiesModule"
```

### PR DESCRIPTION
**Pull request by joymufeng**
Obtain the CookieBakers from application.requestFactory for ServerResultUtils.

Fixes #7659.

### CODE REVIEW

**Comment by joymufeng** [comment]
@gmethvin I have finished the refactor, could you please have a check, thanks!

File: framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala [hunk 1]
```diff
@@ -17,13 +17,18 @@ import play.api.mvc.request.RequestAttrKey
...
+    sessionBaker: SessionCookieBaker,
+    flashBaker: FlashCookieBaker,
+    cookieHeaderEncoding: CookieHeaderEncoding) {
 
-  private val cookieSigner = new CookieSignerProvider(httpConfiguration.secret).get
-
-  val cookieHeaderEncoding: CookieHeaderEncoding = new DefaultCookieHeaderEncoding(httpConfiguration.cookies)
-  val sessionBaker: SessionCookieBaker = new DefaultSessionCookieBaker(httpConfiguration.session, httpConfiguration.secret, cookieSigner)
-  val flashBaker: FlashCookieBaker = new DefaultFlashCookieBaker(httpConfiguration.flash, httpConfiguration.secret, cookieSigner)
+  def this(httpConfig: HttpConfiguration) = this(
```
Comment (gmethvin) [inline framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala]: Since this class is `private[play]` I don't think we need this other constructor. From an API standpoint it's not considered public so we can add a filter in MiMa.

File: framework/src/play-server/src/main/scala/play/core/server/common/ReloadCache.scala [hunk 2]
```diff
@@ -36,11 +39,31 @@ private[play] abstract class ReloadCache[+T] {
...
+
+        (
+          httpConfig,
+          new DefaultSessionCookieBaker(httpConfig.session, httpConfig.secret, cookieSigner),
+          new DefaultFlashCookieBaker(httpConfig.flash, httpConfig.secret, cookieSigner),
+          new DefaultCookieHeaderEncoding(httpConfig.cookies)
+        )
     }
-    new ServerResultUtils(httpConfiguration)
+    new ServerResultUtils(httpConfiguration, sessionBaker, flashBaker, cookieHeaderEncoding)
```
Comment (gmethvin) [inline framework/src/play-server/src/main/scala/play/core/server/common/ReloadCache.scala]: Would probably be clearer to do the `new ServerResultUtils` for each case.

**Comment by joymufeng** [comment]
@gmethvin I have added the test and removed the auxiliary constructor of ServerResultUtils.

**Comment by gmethvin** [comment]
There is a build failure because you still need to add mima filters: https://travis-ci.org/playframework/playframework/jobs/257188904#L789

These can be added to the `mimaBinaryIssueFilters` in `BuildSettings`: https://github.com/playframework/playframework/blob/7948b92bc483a80ee92693650e59dc9c31a8c471/framework/project/BuildSettings.scala#L173

It's ok to do that since this API is `private[play]` and even though it's in the bytecode, it won't actually compile if used in Scala code outside `play` and is not part of the public Play API.

**Comment by joymufeng** [comment]
@gmethvin Hi Methvin, I have added the ignored methods to mima filters.

**Comment by marcospereira** [comment]
Backport to 2.6.x: 038fb28f1e68267c59cf562927d9916eec3a5c7e
