### PR TITLE
shutdown hooks will now be called correctly in dev mode

### LINKED ISSUE #6433: Evolution makes modules and singleton injected classes to be instantiated twice
I am trying to create a periodic job from a module. The POC code is this:
```
package modules
import akka.actor._
import javax.inject._

import com.google.inject.AbstractModule
import play.api.libs.concurrent.AkkaGuiceSupport

import scala.concurrent.ExecutionContext
import scala.concurrent.duration._
import play.api.Logger

class JobModule extends AbstractModule with AkkaGuiceSupport {
  Logger info "Job module created"
  def configure() = {
    bind(classOf[Scheduler]).asEagerSingleton
  }
}

object Scheduler
{
  Logger info "Scheduler object created"
  var ticker = 0
}

class Scheduler @Inject() (val system: ActorSystem)(implicit ec: ExecutionContext)
{
  import Scheduler._
  Logger info "Scheduler class created"

  system.scheduler.schedule(0.seconds, 1.second) {
    Logger debug s"tick $ticker"
    ticker += 1
  }
}
```
I use in-memory H2 DB driver, so every time I restart the application, it needs an evolution. Unfortunately, my JobModule, all the dependencies and even the companion object are instantiated twice, once before the evolution and then again after the evolution has been applied. I end up with the same task scheduled twice.
From the log it looks as if the Logger instance and HikariPool are also instantiated twice.

Log before evolution:
```
(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 1 Scala source to /home/arunasr/Projects/play/bnitracker/target/scala-2.11/classes...
Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which in some cases may be orders of magnitude slower than using node.js.
13 21:55:00.003 [info]application: Job module created
13 21:55:00.491 [info]application: Creating Pool for datasource 'default'
13 21:55:00.503 [info]c.z.h.HikariDataSource: HikariPool-0 - is starting.
13 21:55:00.666 [info]p.a.d.DefaultDBApi: Database [default] connected at jdbc:h2:mem:bnitracker
13 21:55:00.782 [info]a.e.s.Slf4jLogger: Slf4jLogger started
13 21:55:00.791 [info]application: Scheduler class created
13 21:55:00.798 [info]application: Scheduler object created
13 21:55:00.798 [debug]application: tick 0
13 21:55:00.869 [error]application: 

! @7145bjbge - Internal server error, for (GET) [/] ->
 
play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:77)
```
After evolution:
```
13 21:55:01.799 [debug]application: tick 1
13 21:55:02.810 [debug]application: tick 2
13 21:55:03.810 [debug]application: tick 3
13 21:55:04.810 [debug]application: tick 4
13 21:55:05.810 [debug]application: tick 5
13 21:55:05.975 [info]application: Job module created
13 21:55:06.025 [info]application: Creating Pool for datasource 'default'
13 21:55:06.026 [info]c.z.h.HikariDataSource: HikariPool-1 - is starting.
13 21:55:06.029 [info]p.a.d.DefaultDBApi: Database [default] connected at jdbc:h2:mem:bnitracker
13 21:55:06.061 [info]a.e.s.Slf4jLogger: Slf4jLogger started
13 21:55:06.064 [info]application: Scheduler class created
13 21:55:06.067 [info]application: Scheduler object created
13 21:55:06.067 [debug]application: tick 0
13 21:55:06.161 [info]play.api.Play: Application started (Dev)
13 21:55:06.810 [debug]application: tick 6
13 21:55:07.076 [debug]application: tick 1
13 21:55:07.810 [debug]application: tick 7
13 21:55:08.076 [debug]application: tick 2
13 21:55:08.810 [debug]application: tick 8
13 21:55:09.077 [debug]application: tick 3
13 21:55:09.810 [debug]application: tick 9
13 21:55:10.077 [debug]application: tick 4
13 21:55:10.810 [debug]application: tick 10
```
### Operating System (Ubuntu 15.10)
Linux fuji 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (OpenJDK 1.8.x)
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

### Expected Behaviour

I expect singleton classes and their companion objects to be instantiated once.

### Actual Behaviour

I get two instances of singleton class and two scheduled jobs running in parallel.

### PR DESCRIPTION
**Pull request by schmitch**
# Helpful things

## Fixes

Fixes #6433

## Purpose

It actually ensure's that Shutdown Hooks will be only called **once** and that they will **always** be called in dev mode. This ensure's that nothing can go stale.

## Background Context

Actually without breaking backwards compatibility I didn't see any other way of having a good way to do it.

So this isn't back portable since it will break mima and definitly add some problems when people **didn't** used BuiltInComponentsWithContext.

Another problem still happens or at least I don't if it will, it still never garbage collects the ReloadableClassLoader which I can't actually fix without a profiler like Yourkit (VisualVM is too dumb), I guess something still holds a reference to something but since nothing is running there it isn't a big deal.

### CODE REVIEW

**Comment by schmitch** [comment]
Just in case if somebody asks, I used the ConcurrentLinkedQueue, since in some rare circumstances the stop hooks won't be called by Play.stop() (after the first migration run and I created a second one). Calling the stop methods of the stop hooks after a `Play.stop()` ensure's that stop hooks can only be called one, no matter how often I call `stop()`

File: framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala [hunk 1]
```diff
@@ -89,12 +88,16 @@ class DefaultApplicationLifecycle @Inject() () extends ApplicationLifecycle {
...
     import play.core.Execution.Implicits.trampoline
 
-    hooks.foldLeft(Future.successful[Any](())) { (future, hook) =>
-      future.flatMap { _ =>
-        hook().recover {
-          case e => Logger.error("Error executing stop hook", e)
-        }
-      }
+    @tailrec
+    def clearHooks(previous: Future[Any] = Future.successful[Any](())): Future[Any] = {
```
Comment (wsargent) [inline framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala]: Can we add a test to call a bunch of lifecycles with hooks at once?

Comment (schmitch) [inline framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala]: ah I've seen a problem here. I shouldn't use FIFO queue I need a LIFO qeue..

Comment (schmitch) [inline framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala]: done. without the test we would probably had a FIFO ordering of hooks, but from our Docs: `The ApplicationLifecycle will stop all components in reverse order from when they were created.`

**Comment by schmitch** [comment]
One Question remains: How to fix it in 2.5.x

File: framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala (hunk 1 above)
Comment (wsargent) [inline framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala]: That is documented behavior, and we have closed bugs as a result of that line :-)

Comment (schmitch) [inline framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala]: yeah, however I read that bug **before** I implemented and had LIFO in my mind, and still my first implementation was FIFO. probably cause it was too late at night ;)

**Comment by wsargent** [comment]
LGTM

**Comment by tsuyoshizawa** [comment]
@schmitch  Does this PR fix #4682 problem too?
If the problem will be fixed, please close the issue.

I hope you make a backport commit for 2.5 branch.

**Comment by schmitch** [comment]
I guess it will fix it. So I close it, but if it doesn't fix it just reopen it.

I'm not sure for a backport tough, it would break Mima. @gmethvin should we backport this? It will break MIMA.

**Comment by gmethvin** [comment]
@schmitch No we should not backport as-is. If we can find a workaround that doesn't involve modifying `ApplicationLoader.Context` we could do that. Otherwise it's a pretty serious break in API compatibility.

**Comment by schmitch** [comment]
We could hijack the DefaultWebCommands and add a reference to that inside DefaultApplicationLoader and add a stop command to them for 2.5. Just kidding.

**Comment by gmethvin** [comment]
What we could do is:
```scala
case class Context(environment: Environment, sourceMapper: Option[SourceMapper], webCommands: WebCommands, initialConfiguration: Configuration) {
  val lifecycle: ApplicationLifecycle = new DefaultApplicationLifecycle()
}
```
Then in `DevServerStart` we could set:
```scala
val context = ApplicationLoader.createContext(environment, dirAndDevSettings, Some(sourceMapper), webCommands)
lastLifecycle = Some(context.lifecyle)
```

**Comment by schmitch** [comment]
That would still break stuff since I need to add it to `NettyServerComponents` I guess.

**Comment by gmethvin** [comment]
@schmitch We could just not add it to `NettyServerComponents` and fix it in dev mode only.

**Comment by schmitch** [comment]
hm okai, btw. should we add docs that if people want the DevServer to work in compile time DI, that they need to use the lifecycle from the context?

**Comment by gmethvin** [comment]
When you use compile time DI in dev mode you're not using the NettyServerComponents cake, so it still goes through `DevServerStart`. Your `ApplicationLoader` just constructs the components for your application.

**Comment by gmethvin** [comment]
I think the only place we use `NettyServerComponents` is in https://www.playframework.com/documentation/2.5.x/ScalaEmbeddingPlay

**Comment by schmitch** [comment]
I mean if somebody overrides `BuiltInComponents`, then he can still use the DevServer but he can just ignore the context provided.

**Comment by gmethvin** [comment]
I think it should still be safe to add it to `BuiltInComponentsFromContext` though, since it's an abstract class. I believe changing a method from abstract to non-abstract should be binary compatible. We can document it but I think adding to `BuiltInComponentsFromContext is enough.

**Comment by schmitch** [comment]
Backport here: https://github.com/playframework/playframework/pull/6449
