### PR TITLE
In DEV mode, only set the editor in the error handler if config is valid

### LINKED ISSUE #9020: Malformed Config Files Kill Server With Useless Error Message [2.7.0]
### Play Version (2.5.x / etc)

2.7.0

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

### Library Dependencies

N/A

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Malformed application.conf is placed in ./conf
2. Run Play dev-mode
3. Attempt to load a page
4. Error: Malformed application.conf is logged/reported.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "the page renders a 500 error code with no body content."  Copy and paste logs, and include any URLs.  Turn on internal Play logging with `<logger name="play" value="TRACE"/>` if there is no log output.  

* Error 500 is provided to the browser with no body.
* At step 4 above, the following output has been provided to the log (with "TRACE" enabled as described above), producing:  
```console
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000

(Server started, use Enter to stop and go back to the console...)

[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:504)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
```

### Reproducible Test Case

Sample project available here:
https://github.com/SattaiLanfear/play27malformedconf/

This project was generated using the play scala giter8 on 2/10/2019.
application.conf and logback.xml are the only files that should have been changed from default.

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #9020
If `application.conf` is invalid the error handler will be called. So far so good, normal behaviour.
But now the default error handler tries to actually read that invalid config, which will of course fail, because, yeah, the config is invalid ;) So this ends up failing as well and now no result will be produced and [this bizarre and completely useles error message](https://github.com/playframework/playframework/issues/9020#issue-408672151) will be thrown by the akka-http backend.
(Actually it was not me, but @ctoomey [who deserves all the credit](https://github.com/playframework/playframework/issues/9020#issuecomment-564184187))
I can confirm the [reproducer posted in the original issue](https://github.com/SattaiLanfear/play27malformedconf/) now runs fine.

### CODE REVIEW

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x 2.7.x

File: core/play/src/main/scala/play/api/http/HttpErrorHandler.scala [hunk 1]
```diff
@@ -499,10 +502,11 @@ class JsonHttpErrorHandler(environment: Environment, sourceMapper: Option[Source
...
     extends DefaultHttpErrorHandler(HttpErrorConfig(showDevErrors = true, playEditor = None), None, None) {
-  private lazy val setEditor: Unit = {
-    val conf = Configuration.load(Environment.simple())
-    conf.getOptional[String]("play.editor").foreach(setPlayEditor)
-  }
+  private lazy val setEditor: Unit =
+    Try(Configuration.load(Environment.simple())) match {
+      case Success(conf) => conf.getOptional[String]("play.editor").foreach(setPlayEditor)
+      case Failure(_)    => // Very likely invalid config, not able to set the editor
+    }
```
Comment (ignasi35) [inline core/play/src/main/scala/play/api/http/HttpErrorHandler.scala:509]: Would it make sense to log the failure with some helpful message in the case of `Failure(_)`? How about:

```suggestion
  private val logger = Logger(getClass)
  private lazy val setEditor: Unit =
    Try(Configuration.load(Environment.simple())) match {
      case Success(conf) => conf.getOptional[String]("play.editor").foreach(setPlayEditor)
      case Failure(t) => // Very likely invalid config, not able to set the editor
        logger.error("Failed to load the configuration setup. This uusally means there's a syntax error in your conf files.", t)
    }
```

PS: I haven't tested the code in the suggestion

**Review by ignasi35 — APPROVED** [review]

File: core/play/src/main/scala/play/api/http/HttpErrorHandler.scala (hunk 1 above)
Comment (mkurz) [reply core/play/src/main/scala/play/api/http/HttpErrorHandler.scala]: Thanks @ignasi35 - I added a error message but changed the wording a little bit so it talks about `play.editor`, I think otherwise it's too generic.
